environments:
  dev:

repositories:
  - name: yesodot
    url: https://harborreg-2.northeurope.cloudapp.azure.com/chartrepo/library
    username: {{ requiredEnv "HARBOR_USER" }}
    password: {{ requiredEnv "HARBOR_PASSWORD" }}

releases:
  - name: storage-service
    namespace: jaws
    chart: yesodot/common
    version: {{ env "COMMON_VERSION" | default "0.8.0" }}
    values:
      - ./values.yaml

helmDefaults:
  recreatePods: true
  createNamespace: false
