name: "relationship-template-manager"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/relationship-template-manager
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /isAlive
    port: 8000

readinessProbe:
  httpGet:
    path: /isAlive
    port: 8000
  initialDelaySeconds: 30

config:
  configmaps: []
  env:
    - name: PORT
      value: 8000
    - name: MONGO_URI
      value: mongodb+srv://jaws:jcfVBJQW73BobDvr@cluster0.t8onr.mongodb.net/templates?retryWrites=true&w=majority
    - name: MONGO_RELATIONSHIP_TEMPLATE_COLLECTION_NAME
      value: relationshipTemplate    
    - name: MONGO_RULE_COLLECTION_NAME
      value: rules
    - name: ENTITY_TEMPLATE_MANAGER_URI
      value: http://entity-template-manager:8000

resources:
  limits:
    cpu: 400m
    memory: 400Mi
  requests:
    cpu: 400m
    memory: 400Mi
