name: "relationship-template-service"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/relationship-template-service
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /isAlive
    port: 8000

readinessProbe:
  httpGet:
    path: /isAlive
    port: 8000

config:
  configmaps: []
  env:
    - name: PORT
      value: 8000
    - name: MONGO_URL
      value: mongodb+srv://jaws:jcfVBJQW73BobDvr@cluster0.t8onr.mongodb.net/relationship-template-service?retryWrites=true&w=majority
    - name: MONGO_RELATIONSHIP_TEMPLATES_COLLECTION_NAME
      value: relationship-templates    
    - name: MONGO_RULE_COLLECTION_NAME
      value: rules
    - name: ENTITY_TEMPLATE_SERVICE_URL
      value: http://entity-template-service:8000
