FROM node:22-alpine AS builder
WORKDIR /usr/src/app

# Copy root files
COPY package*.json ./
COPY tsconfig.json ./


# Copy shared
COPY shared/package*.json ./shared/
COPY shared/ ./shared/

# Use an ARG to decide which service to build
ARG SERVICE_NAME
COPY ${SERVICE_NAME}/package*.json ./${SERVICE_NAME}/
COPY ${SERVICE_NAME}/ ./${SERVICE_NAME}/

# Install dependencies & build 'shared'
RUN npm ci --silent
RUN npm run build -w @microservices/shared
RUN npm run build -w ${SERVICE_NAME}

EXPOSE 8000

RUN echo "Finish building: ${SERVICE_NAME} image"