version: "3.4"

services:
  #-------------------------------------------#
  #*   Service infrastructure dependencies:   #
  #-------------------------------------------#
  mongo:
    image: mongo:5.0.11
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    ports:
      - 27017:27017

  mongosetup:
    image: mongo:5.0.11
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: ["bash", "/scripts/setup_mongo.sh"]

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
      - "4000:4000"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: "minio server --console-address :4000 /data"
    restart: always

  neo4j:
    build:
      context: ./instance-service
      dockerfile: Dockerfile-neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_secURLty_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  mock-service:
    build: ./mock-service
    environment:
      ENTITY_TEMPLATE_SERVICE_URL: ${ENTITY_TEMPLATE_SERVICE_URL}
      RELATIONSHIP_TEMPLATE_SERVICE_URL: ${RELATIONSHIP_TEMPLATE_SERVICE_URL}
      INSTANCE_SERVICE_URL: ${INSTANCE_SERVICE_URL}
      PERMISSION_SERVICE_URL: ${PERMISSION_SERVICE_URL}
      PROCESS_SERVICE_URL: ${PROCESS_SERVICE_URL}
      STORAGE_SERVICE_URL: ${STORAGE_SERVICE_URL}
      GANTT_SERVICE_URL: ${GANTT_SERVICE_URL}
      PERMISSION_SERVICE_MANAGERS_KARTOFFEL_IDS: 5e5688324203fc40043591aa,61d37cb5e4de0300121e31ef
      PROCESS_SERVICE_REVIEWERS_KARTOFFEL_IDS: 5e5688d54203fc40043591ac,626e4e5be8e4d7001101b794,5ebbd53f64fe6f2b1c5777ae
    depends_on:
      - neo4j
      - entity-template-service
      - relationship-template-service
      - storage-service
      - instance-service
      - permission-service
      - process-service
      - gantt-service
    restart: on-failure

  #-------------------------------------------#
  #        microservices:                     #
  #-------------------------------------------#
  entity-template-service:
    ports:
      - 8001:8000
    restart: always

  relationship-template-service:
    ports:
      - 8002:8000
    restart: always

  gateway-service:
    ports:
      - 8003:8000
    restart: always

  permission-service:
    ports:
      - 8005:8000
    restart: always

  storage-service:
    ports:
      - 8006:8000
    restart: always

  instance-service:
    ports:
      - 8007:8000
    restart: always

  nginx:
    ports:
      - 80:80
    restart: always

  global-search-service:
    restart: always

  notification-service:
    restart: always

  rule-breach-service:
    restart: always

  process-service:
    ports:
      - 8008:8000
    restart: always

  gantt-service:
    ports:
      - 8009:8000
    restart: always

  # mailer-service:
  #   depends_on:
  #     - redis
  #   ports:
  #     - 8010:8000
  #   restart: always

  preview-service:
    ports:
      - 8011:8000
    restart: always

  workspace-service:
    ports:
      - 8012:8000
    restart: always
