apiVersion: batch/v1
kind: CronJob
metadata:
    name: date-notification-check
    namespace: default
spec:
    schedule: '* * * * *'
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: date-notification-check
                          image: melta-gateway-service:latest
                          command: ['node', '/usr/src/app/src/utils/notifications/dateNotificationsCheck.ts']
                    restartPolicy: OnFailure
