name: "rule-breach-service"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/rule-breach-service
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /isAlive
    port: 8000

readinessProbe:
  httpGet:
    path: /isAlive
    port: 8000
  initialDelaySeconds: 45

config:
  configmaps: []
  env:
    - name: PORT
      value: 8000
    - name: MONGO_URI
      value: mongodb+srv://jaws:jcfVBJQW73BobDvr@cluster0.t8onr.mongodb.net/rule-breaches?retryWrites=true&w=majority
    - name: MONGO_RULE_BREACH_ALERTS_COLLECTION_NAME
      value: rule-breach-alerts
    - name: MONGO_RULE_BREACH_REQUESTS_COLLECTION_NAME
      value: rule-breach-requests

resources:
  limits:
    cpu: 400m
    memory: 400Mi
  requests:
    cpu: 400m
    memory: 400Mi
