version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  rule-breach-service:
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      MONGO_URL: mongodb://mongo/rule-breach-service
