const hebrew = {
    titles: {
        meltaNotificationTitlePrefix: 'התראה מערכת מלתעות -',
        ruleBreachAlert: `התראת חריגת חוקה`,
        ruleBreachRequest: `בקשה לאישור חריגת חוקה`,
        ruleBreachResponse: `בקשה לחריגת חוקה נסגרה`,
        processReviewerUpdate: `עדכון הרשאות לתהליך`,
        processStatusUpdate: `עדכון סטטוס`,
        newProcess: `יצירת תהליך חדש`,
        dateAboutToExpire: ` תאריך תפוגה של ישות`,
        deleteProcess: `מחיקת תהליך`,
        archivedProcess: `פעולת ארכיון על תהליך`,
    },
    archiveProcess: {
        theProcess: 'התהליך',
        sendToArchive: 'שליחת תהליך לארכיון',
        removeFromArchive: 'הסרת תהליך מארכיון',
        sendToArchiveSuccessfully: 'נשלח לארכיון בהצלחה',
        removeFromArchiveSuccessfully: 'הוסר מהארכיון בהצלחה',
    },
    deleteProcess: {
        theProcess: ' התהליך',
        deleteProcess: 'מחיקת תהליך',
        deleteSuccessfully: ' נמחק בהצלחה ',
    },
    newProcess: {
        createNewProcess: 'יצירת תהליך חדש',
        processName: 'נוצר תהליך חדש בשם: ',
    },
    processStatusUpdate: {
        updateStatus: ' עדכון סטטוס',
        step: 'שלב',
        process: 'תהליך',
        stepStatus: 'הסטטוס של השלב: ',
        processStatus: ' הסטטוס של התהליך: ',
        inProcess: 'בתהליך: ',
        updatedTo: 'עודכן ל: ',
    },
    processReviwerUpdate: {
        processReviwerUpdate: 'עדכון הרשאות לתהליך',
        inProcess: 'בתהליך:',
        addToReviwers: 'התווספת לגורמים המאשרים בשלבים: ',
        removeFromReviwers: 'הוסרת מהגורמים המאשרים בשלבים: ',
        removeFromReviwersInProcess: 'הוסרת מהגורמים המאשרים של התהליך: ',
    },
    ruleBreach: {
        note: 'שים לב,',
        RequestPendingApproval: 'בקשה ממתינה לאישור',
        theRequestForAction: 'הבקשה לביצוע הפעולה',
        approved: 'אושרה ',
        denied: 'סורבה ',
        relationshipCreation: 'יצירת קשר',
        relationshipDeletion: 'מחיקת קשר',
        fromEntity: 'מישות',
        toEntity: ' לישות',
        unknownEntity: 'לא ידוע',
        updateEntityStatusActionInfo: {
            toDisabled: ' למושבת ',
            toActive: ' למופעל ',
        },
        by: 'על ידי ',
        moreDetails: 'לפרטים נוספים, ',
        clickHere: 'לחץ כאן',
        ruleBreachAlertTitle: 'התראת חריגת חוקה',
        ruleBreachRequestTitle: 'בקשה לאישור חריגת חוקה ',
        ruleBreachResponseTitle: 'מענה חריגת חוקה',
    },
    brokenRules: {
        breakingRules: 'הפרה את החוקים הבאים:',
        description: 'תיאור: ',
    },
    updateEntityActionInfo: {
        updatingEntity: ' עדכון ישות',
        createEntity: 'יצירת ישות',
        duplicateEntity: 'שכפול ישות ',
        updatingEntityStatus: ' עדכון סטטוס ישות',
    },
    dateAboutToExpireNotification: {
        dateAboutToExpireHeadline: 'שים לב,\n',
        propertyValue: 'התאריך ',
        entityTemplateName: ' בישות ',
        aboutToExpire: ' מתקרב',
    },
    status: {
        approved: 'בוצע',
        rejected: 'נדחה',
        pending: 'ממתין',
    },
};

export default hebrew;
