apiVersion: v1
kind: Service
metadata:
    name: template-service
spec:
    selector:
        app: template-service
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
# kubectl delete service --all
# kubectl apply -f ~/melta/melta/template-service/scripts/template-service-service.yaml
