version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  gantt-service:
    build: .
    environment:
      PORT: 8000
      MONGO_URL: mongodb://mongo/gantt-service
      MONGO_GANTTS_COLLECTION_NAME: gantts
      MONGO_IFRAMES_COLLECTION_NAME: iFrames
    ports:
      - 8001:8000
