name: "global-search-index-creator"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/global-search-index-creator
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

config:
  configmaps: []
  env:
    - name: NEO4J_USERNAME
      value: neo4j
    - name: NEO4J_PASSWORD
      value: test
    - name: NEO4J_DATABASE
      value: neo4j
    - name: NEO4J_URL
      value: neo4j://neo4j
    - name: TEMPLATE_MANAGER_URL
      value: http://entity-template-manager:8000
    - name: RELATIONSHIP_MANAGER_URL
      value: http://relationship-template-manager:8000      
    - name: REDIS_HOST
      value: redis://:ZjtUJvwPOY@redis:6379  
    - name: RABBIT_URI
      value: amqp://jaws:jawsAreTheBest@20.105.9.117:5672/jaws
