import React, { CSSProperties } from 'react';
import i18next from 'i18next';
import { Box, Typography } from '@mui/material';
import { EntityWizardValues } from './index';
import { StepComponentProps } from '../index';
import { formatToString } from '../../EntityProperties';
import { lightTheme } from '../../../theme';

const summaryTitleStyle: CSSProperties = {
    fontSize: '28px',
    color: '#000000',
    lineHeight: '45px',
};

const titleStyle: CSSProperties = {
    fontSize: '18px',
    color: lightTheme.palette.primary.main,
    lineHeight: '40px',
};

const textStyle: CSSProperties = {
    fontSize: '16px',
    color: '#000000',
    lineHeight: '30px',
    paddingRight: '20px',
};

const Summary: React.FC<StepComponentProps<EntityWizardValues>> = ({ values }) => {
    const categoryName = values.template.category.displayName;
    const entityTemplateName = values.template.displayName;

    const properties = Object.entries(values.template.properties.properties).map(([key, value]) => {
        if (value.format === 'fileId') {
            return { title: value.title, value: values.attachmentsProperties[key]?.name ?? '-' };
        }
        if (value.hasOwnProperty('serialCurrent')) {
            return { title: value.title, value: i18next.t('wizard.entity.serialNumberAutoGenerated') };
        }

        return { title: value.title, value: formatToString(values.properties[key], value.type, value.format) };
    });

    return (
        <Box
            sx={{
                border: `1px solid ${lightTheme.palette.primary.main}`,
                width: 400,
                margin: 'auto',
                borderRadius: '8px',
            }}
        >
            <div style={{ marginRight: '20px', width: 370, maxHeight: '300px', overflowY: 'scroll' }}>
                <div>
                    <div style={{ position: 'relative' }}>
                        <div
                            style={{
                                backgroundColor: lightTheme.palette.primary.main,
                                height: '7px',
                                width: '7px',
                                borderRadius: '50%',
                                position: 'absolute',
                                marginTop: '62px',
                            }}
                        />
                        <div
                            style={{
                                borderRight: '2px solid #DBDBDB',
                                height: '95px',
                                position: 'absolute',
                                marginTop: '69px',
                                marginRight: '2px',
                            }}
                        />
                        <div
                            style={{
                                backgroundColor: 'white',
                                height: '7px',
                                width: '7px',
                                borderRadius: '50%',
                                border: '1px solid #A9A9A9',
                                position: 'absolute',
                                marginTop: '162px',
                            }}
                        />
                    </div>
                    <Typography style={summaryTitleStyle}>{i18next.t('wizard.entity.summary')}</Typography>
                </div>
                <div>
                    <div style={{ paddingRight: '15px' }}>
                        <Typography style={titleStyle}>{i18next.t('wizard.entity.classificationCategory')}</Typography>
                    </div>
                    <Typography style={textStyle}>{`${i18next.t('category')}: ${categoryName}`}</Typography>
                    <Typography style={textStyle}>{`${i18next.t('entityTemplate')}: ${entityTemplateName}`}</Typography>
                </div>
                <div
                    style={{
                        borderRight: '2px dashed #DBDBDB',
                        marginRight: '2px',
                    }}
                >
                    <div style={{ paddingRight: '10px' }}>
                        <Typography style={titleStyle}>{i18next.t('wizard.entity.anotherParams')}</Typography>
                    </div>
                    {properties.map((propsValue) => (
                        <div key={propsValue.title}>
                            <Typography style={textStyle}>{`${propsValue.title}: ${propsValue.value}`}</Typography>
                        </div>
                    ))}
                    <div
                        style={{
                            backgroundColor: 'white',
                            height: '7px',
                            width: '7px',
                            borderRadius: '50%',
                            border: '2px solid #A9A9A9',
                            marginRight: '-4px',
                            marginBottom: '2px',
                        }}
                    />
                </div>
            </div>
        </Box>
    );
};

export { Summary };
