import i18next from 'i18next';
import { NotificationType } from './interfaces/notifications';
import { ILabelIcon } from './utils/graph/helperTypes';

export const environment = {
    api: {
        login: '/api/auth/login',
        config: '/config',
        getAllTemplates: '/templates/all',
        getAllClientSideTemplates: '/client-side/templates/all',
        categories: '/templates/categories',
        entityTemplates: '/templates/entities',
        childTemplates: '/templates/child',
        clientSideRoutes: '/client-side',
        templatesConfig: '/templates/config',
        relationshipTemplates: '/templates/relationships',
        printingTemplates: '/templates/print',
        rules: '/templates/rules',
        entities: '/instances/entities',
        relationships: '/instances/relationships',
        processTemplates: '/processes/templates',
        processes: '/processes/instances',
        gantts: '/gantts',
        iFrames: '/iframes',
        charts: '/charts',
        storage: '/files',
        preview: '/preview',
        permissions: '/permissions',
        units: '/units',
        users: '/users',
        roles: '/users/roles',
        activityLog: '/activity-log',
        notifications: '/notifications',
        ruleBreachesRequests: '/rule-breaches/requests',
        ruleBreachesAlerts: '/rule-breaches/alerts',
        workspaces: '/workspaces',
        dashboard: '/dashboard',
    },
    twinWalletId: '$twin',
    unauthorizedId: 'unauthorized',
    clientSideId: 'client-side',
    defaultTitle: 'Melta',
    workspaceIdHeaderName: 'workspace-id',
    searchPath: '/search',
    searchParams: {
        viewModeKey: 'viewMode',
        semanticSearchKey: 'semanticSearch',
        searchKey: 'search',
        viewModeOptions: {
            templatesTables: 'templates-tables-view',
            card: 'cards-view',
        },
    },
    graphSettings: {
        nodeConnectionsCountRangesToNodeSize: {
            '0-2': 3,
            '3-4': 4,
            '5-6': 5,
            '7-8': 6,
            '9-10': 8,
        },
        maxNodeSize: 7,
        nodeSizeMultiplier: 4,
        nodeIconSizeMultiplier: 0.7,
        nodeHoverSizeMultiplier: 1.2,
        labelBackgroundColor: 'rgba(255, 255, 255, 0.8)',
        linkLabelFontSize: 2,
        labelIconsSizeMultiplier: 0.6,
        labelIcons: {
            original: { icon: '⊛', color: '#5dc457' },
            locked: { icon: '⊗', color: '#0090d0' },
            highlighted: { icon: '⊙', color: '#FF8C00' },
            mainHighlighted: { icon: '⊚', color: '#ff0000' },
        } as Record<string, ILabelIcon>,
        lookAt: {
            duration: 250,
            scale: 5,
        },
        lookAt3D: {
            distance: 250,
        },
        is3DViewLocalStorageKey: 'isGraph3DView',
        detailsResolution3D: 100,
        BatchSize: 50,
        limit3DConnections: 100,
    },
    mui: {
        activationKey: '8c5d3fd6a4390125cf8590dea55dbb05Tz1HdXksRT0yMDAwMDAwMDAwMDAwLFM9cHJlbWl1bSxMTT1zdWJzY3JpcHRpb24sS1Y9Mg==',
    },
    cesium: {
        activationKey:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjZWI5M2EyNC1lODE3LTQwYTQtYTUxZi00NDlhODAyZDM0NTMiLCJpZCI6MjcwNDM5LCJpYXQiOjE3Mzc0NDk3MzN9.WLi4Zcm4D_PMstHcM3YNMJsw1xPhiNGuJyizwg_4nbg',
        cesiumSource: 'node_modules/cesium/Build/Cesium',
        cesiumBaseUrl: 'cesiumStatic',
    },
    canvasSettings: {
        heightPaddingMultiplier: 0.3,
        widthPaddingMultiplier: 0.6,
    },
    excludedFormats: ['text-area', 'fileId', 'relationshipReference', 'user', 'location', 'signature', 'comment'] as string[],
    signatureFields: ['signedByDetails', 'stampedByDetails'],
    signatureFieldDetails: ['fullName', 'rank', 'personalNumber', 'signature'],
    users: {
        kartoffelProfile: 'kartoffelProfile',
    },
    ganttSettings: {
        infiniteScrollPageCount: 10,
        isSidebarOpenLocalStorageKey: 'isGanttSidebarOpen',
        ganttEntitiesChunkSize: 1000,
        groupByEntitiesChunkSize: 1000,
        tablesPerLoadingChunkSize: 5,
        separators: {
            startEnd: ' 🡠 ',
            field: ' × ',
            entity: ' ⬤ ',
            template: ' & ',
            related: ' ⇄ ',
        },
        heatmapColors: {
            now: '#ff4b3b',
            idle: '#8bb8ec',
        },
        refetchInterval: 5000,
        searchParams: {
            selectedViewKey: 'selectedView',
            selectedDateKey: 'selectedDate',
            heatmapModeKey: 'heatmapMode',
        },
    },
    entitiesProperties: {
        maxNumOfCharactersNotInFullWidth: 700,
        numOfFixedDigits: 18,
    },
    entitiesCardsView: {
        infiniteScrollPageCount: 12,
    },
    permission: {
        infiniteScrollPageCount: 13,
    },
    cardsView: {
        infiniteScrollPageCount: 13,
    },
    activityLog: {
        infiniteScrollPageCount: 10,
    },
    datePickerViews: ['year', 'month', 'day'],
    processInstances: {
        infiniteScrollPageCount: 10,
    },
    processDetailsContentDisplay: {
        summary: 'SUMMARY',
        reviewers: 'REVIEWERS',
    },
    iFrames: {
        iFrameDimensionKey: 'iFrameDimension_',
        iFramesOrderKey: 'iFramesOrder',
        sideBarOpenKey: 'isSideBarOpen',
        infiniteScrollPageCount: 6,
        sideBarWidth: 200,
        iFrameSpace: 10,
        sideBarOpenWidth: 320,
        sideBarCloseWidth: 140,
        relativeMaxHight: 160,
    },
    charts: {
        defaultColumnSizes: { lg: 12, md: 12, sm: 12, xs: 12, xxs: 12 },
        chartsOrderKey: 'chartsOrder_',
        pieChartColors: [
            '#F098ED',
            '#F9FB85',
            '#FFBB6D',
            '#86FB83',
            '#6DCBFF',
            '#F09898',
            '#AF98F0',
            '#85FBED',
            '#C0FB85',
            '#FFDF6D',
            '#6D96FF',
            '#FB8383',
            '#D498F0',
        ],
        cols: 12,
        itemWidth: 4,
    },
    dashboard: {
        dashboardOrderKey: 'dashboardOrder',
        dashboardPath: '/dashboard',
        chartPath: '/charts',
        tablePath: '/table',
        iFramePath: '/iframe',
    },
    notifications: {
        updateInterval: 1000 * 60 * 10,
        infiniteScrollPageCount: 10,
        color: '#FF006B',
        groups: {
            requests: [NotificationType.ruleBreachRequest],
            general: [
                NotificationType.ruleBreachAlert,
                NotificationType.ruleBreachResponse,
                NotificationType.ruleIndicatorAlert,
                NotificationType.processReviewerUpdate,
                NotificationType.processStatusUpdate,
                NotificationType.newProcess,
                NotificationType.dateAboutToExpire,
                NotificationType.deleteProcess,
                NotificationType.archivedProcess,
            ],
            // colors: {
            //     RuleBreachAlertNotification: '#4752B6',
            //     RuleBreachRequestNotification: '#4752B6',
            //     RuleBreachResponseNotification: '#4752B6',
            //     NewProcessNotification: '#4752B6',
            //     ProcessStatusUpdateNotification: '#4752B6',
            //     ProcessReviewerUpdateNotification: '#4752B6',
            //     DeleteProcessNotification: '#4752B6',
            //     ArchiveProcessNotification: '#4752B6',
            // },
        },
        notificationsMoreData: {
            requests: [
                {
                    color: '#DD3500',
                    type: NotificationType.ruleBreachRequest,
                    displayName: () => i18next.t('notifications.displayNames.ruleBreachRequest'),
                },
            ],
            general: [
                {
                    color: '#cc5083',
                    type: NotificationType.dateAboutToExpire,
                    displayName: () => i18next.t('notifications.displayNames.dateAboutToExpire'),
                },
                {
                    color: '#FFAC2F',
                    type: NotificationType.ruleBreachAlert,
                    displayName: () => i18next.t('notifications.displayNames.ruleBreachAlert'),
                },
                {
                    color: '#DD3500',
                    type: NotificationType.ruleBreachResponse,
                    displayName: () => i18next.t('notifications.displayNames.ruleBreachResponse'),
                },
                {
                    color: '#FF0000',
                    type: NotificationType.ruleIndicatorAlert,
                    displayName: () => i18next.t('notifications.displayNames.ruleIndicatorAlert'),
                },
                {
                    color: '#8FBC8F',
                    type: NotificationType.archivedProcess,
                    displayName: () => i18next.t('notifications.displayNames.archivedProcess'),
                },
                {
                    color: '#FF6347',
                    type: NotificationType.deleteProcess,
                    displayName: () => i18next.t('notifications.displayNames.deleteProcess'),
                },
                {
                    color: '#DA70D6',
                    type: NotificationType.newProcess,
                    displayName: () => i18next.t('notifications.displayNames.newProcess'),
                },
                {
                    color: '#FFC0CB',
                    type: NotificationType.processReviewerUpdate,
                    displayName: () => i18next.t('notifications.displayNames.processReviewerUpdate'),
                },
                {
                    color: '#7BE7FF',
                    type: NotificationType.processStatusUpdate,
                    displayName: () => i18next.t('notifications.displayNames.processStatusUpdate'),
                },
            ],
        },
    },
    agGrid: {
        rowCount: 5,
        defaultExpandedRowCount: 13,
        rowCountInfiniteModeWithoutExpand: 6,
        defaultRowHeight: 50,
        defaultFontSize: 14,
        cacheBlockSize: 5,
        maxBlocksInCache: 50,
        maxConcurrentDatasourceRequests: 1,
        infiniteInitialRowCount: 1,
        defaultExpandedTableHeight: 650,
        paginationPageSizeSelector: [5, 10, 25, 50],
        actionsWidth: 200,
        actionPrefix: 'actions-',
        localStorage: {
            visibleColumns: 'visibleColumns-',
            columnsOrder: 'columnsOrder-',
            columnWidths: 'columnWidths-',
        },
        unitFieldSplitDepth: 2,
    },
    filterOptions: {
        string: ['contains', 'notContains', 'equals', 'notEqual', 'startsWith', 'endsWith'],
        text: ['contains', 'notContains', 'equals', 'notEqual', 'startsWith', 'endsWith'],
        number: ['equals', 'notEqual', 'greaterThan', 'greaterThanOrEqual', 'lessThan', 'lessThanOrEqual'],
        date: [
            'equals',
            'notEqual',
            'greaterThan',
            'greaterThanOrEqual',
            'lessThan',
            'lessThanOrEqual',
            'inRange',
            'thisWeek',
            'thisMonth',
            'thisYear',
            'untilToday',
            'fromToday',
        ],
        field: ['equals', 'notEqual'],
    },
    relativeDateFilters: ['thisWeek', 'thisMonth', 'thisYear', 'untilToday', 'fromToday'] as readonly string[],
    accessTokenName: 'rabaz-access-token',
    brokenRulesFakeEntityIdPrefix: '$',
    minimumSupportedChromeVersion: 85,
    fileIdLength: 32,
    maxDateTimestamp: 8640000000000000,
    attemptInterval: 100,
    unit: 'px',
    errorCodes: {
        ruleBlock: 'RULE_BLOCK',
        failedToCreateConstraints: 'FAILED_TO_CREATE_CONSTRAINTS',
        failedConstraintsValidation: 'FAILED_CONSTRAINTS_VALIDATION',
        failedToDeleteField: 'FAILED_DELETE_FIELD',
        actionsCustomError: 'ACTIONS_CUSTOM_ERROR',
        entityHasRelationships: 'ENTITY_HAS_RELATIONSHIPS',
    },
    loadExcel: { excelExtension: '.xlsx', acceptedFilesTypes: { 'excel/xlsx': ['.xlsx', '.xls'] }, entityId: '$0._id' },
    draftAutoSaveDebounce: 250,
    map: {
        maxRadius: 30000,
        squareLength: 2500,
        polygon: { polygonPrefix: 'POLYGON((', polygonSuffix: '))' },
        polygonDefaultColor: '#11695a',
        coordinateDefaultColor: '#FF006B',
        mapSearchPropertiesLimit: 2,
        epsgCode: { epsg: 'EPSG', wgs84: 'EPSG:4326', southHemiUTM: '327', northHemiUTM: '326' },
        utm: {
            minZone: 1,
            maxZone: 60,
            minEasting: 160000,
            maxEasting: 834000,
            minNorthing: 0,
            maxNorthing: 10000000,
            utmRegex: /\b([1-9]|[1-5][0-9]|60)([C-HJ-NP-X])\s([0-9]+(?:\.[0-9]+)?)\s([0-9]+(?:\.[0-9]+)?)\b/,
            utmPolygonRegex: /\b([1-9]|[1-5][0-9]|60)([C-HJ-NP-X])\s([0-9]+(?:\.[0-9]+)?)\s([0-9]+(?:\.[0-9]+)?)\b/g,
        },
        wgs84: { maxLongitude: 180, maxLatitude: 90 },
        minSearchLength: 2,
        maxNumberOfSearchResults: 1000,
        textValueOfLinkTag: '#text',
        tileMatrixSetIdentifiers: ['WorldCRS84', 'EPSG:4326', 'GoogleMapsCompatible'],
        tilingSchemeId: '3857',
    },
    signaturePrefix: 'data:image/png;base64,',
    meltaUpdatesShown: 'meltaUpdatesShown',
    profileIconsCount: 19,
    avatarIconPath: '/icons/profileAvatar/',
    uuidFormat: /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{8}/,
    dateRegex: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/,
    dateTimeRegex: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,
    objectIdRegex: /^[0-9a-fA-F]{24}$/,
    print: {
        maxPrintLevel: 4,
        neoIdsPathSeparator: ' ',
        relationshipPathSeparator: '&',
        neoRelIdsSeparator: ',',
    },
    formats: {
        date: 'dd/MM/yyyy',
        dateTime: 'dd/MM/yyyy HH:mm',
        time: 'HH:mm',
        fullTime: 'HH:mm:ss',
        loggingDate: 'yyyy-MM-dd',
        loggingDateTime: 'yyyy-MM-dd HH:mm:ss',
    },
    fieldFilterPrefix: '$$current.properties.',
    fileExtensions: {
        defaultImage: 'png',
        image: ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'ico', 'psd', 'raw', 'heif', 'indd', 'ai', 'eps'],
        imageToManipulate: ['png', 'jpg', 'jpeg', 'svg'] as string[],
        video: ['mp4', 'mov', 'avi', 'wmv', 'flv', 'mkv', 'webm', 'avchd', '3gp', '3g2', '3gpp', '3gpp2', 'm4v'],
        audio: ['mp3', 'wav', 'ogg', 'flac', 'wma', 'aac', 'm4a'],
        document: [
            'pdf',
            'doc',
            'docx',
            'xls',
            'xlsx',
            'ppt',
            'pptx',
            'pps',
            'ppsx',
            'odt',
            'ods',
            'odp',
            'txt',
            'rtf',
            'csv',
            'svg',
            'xml',
            'epub',
            'abap',
            'asc',
            'ash',
            'ampl',
            'mod',
            'g4',
            'apib',
            'apl',
            'dyalog',
            'asp',
            'asax',
            'ascx',
            'ashx',
            'asmx',
            'aspx',
            'axd',
            'dats',
            'hats',
            'sats',
            'as',
            'adb',
            'ada',
            'ads',
            'agda',
            'als',
            'apacheconf',
            'vhost',
            'cls',
            'applescript',
            'scpt',
            'arc',
            'ino',
            'asciidoc',
            'adoc',
            'asc',
            'aj',
            'asm',
            'a51',
            'inc',
            'nasm',
            'aug',
            'ahk',
            'ahkl',
            'au3',
            'awk',
            'auk',
            'gawk',
            'mawk',
            'nawk',
            'bat',
            'cmd',
            'befunge',
            'bison',
            'bb',
            'bb',
            'decls',
            'bmx',
            'bsv',
            'boo',
            'b',
            'bf',
            'brs',
            'bro',
            'c',
            'cats',
            'h',
            'idc',
            'w',
            'cs',
            'cake',
            'cshtml',
            'csx',
            'cpp',
            'c++',
            'cc',
            'cp',
            'cxx',
            'h',
            'h++',
            'hh',
            'hpp',
            'hxx',
            'inc',
            'inl',
            'ipp',
            'tcc',
            'tpp',
            'c-objdump',
            'chs',
            'clp',
            'cmake',
            'cmake.in',
            'cob',
            'cbl',
            'ccp',
            'cobol',
            'cpy',
            'css',
            'csv',
            'capnp',
            'mss',
            'ceylon',
            'chpl',
            'ch',
            'ck',
            'cirru',
            'clw',
            'icl',
            'dcl',
            'click',
            'clj',
            'boot',
            'cl2',
            'cljc',
            'cljs',
            'cljs.hl',
            'cljscm',
            'cljx',
            'hic',
            'coffee',
            '_coffee',
            'cake',
            'cjsx',
            'cson',
            'iced',
            'cfm',
            'cfml',
            'cfc',
            'lisp',
            'asd',
            'cl',
            'l',
            'lsp',
            'ny',
            'podsl',
            'sexp',
            'cp',
            'cps',
            'cl',
            'coq',
            'v',
            'cppobjdump',
            'c++-objdump',
            'c++objdump',
            'cpp-objdump',
            'cxx-objdump',
            'creole',
            'cr',
            'feature',
            'cu',
            'cuh',
            'cy',
            'pyx',
            'pxd',
            'pxi',
            'd',
            'di',
            'd-objdump',
            'com',
            'dm',
            'zone',
            'arpa',
            'd',
            'darcspatch',
            'dpatch',
            'dart',
            'diff',
            'patch',
            'dockerfile',
            'djs',
            'dylan',
            'dyl',
            'intr',
            'lid',
            'E',
            'ecl',
            'eclxml',
            'ecl',
            'sch',
            'brd',
            'epj',
            'e',
            'ex',
            'exs',
            'elm',
            'el',
            'emacs',
            'emacs.desktop',
            'em',
            'emberscript',
            'erl',
            'es',
            'escript',
            'hrl',
            'xrl',
            'yrl',
            'node:fs',
            'fsi',
            'fsx',
            'fx',
            'flux',
            'f90',
            'f',
            'f03',
            'f08',
            'f77',
            'f95',
            'for',
            'fpp',
            'factor',
            'fy',
            'fancypack',
            'fan',
            'node:fs',
            'for',
            'eam.fs',
            'fth',
            '4th',
            'f',
            'for',
            'forth',
            'fr',
            'frt',
            'node:fs',
            'ftl',
            'fr',
            'g',
            'gco',
            'gcode',
            'gms',
            'g',
            'gap',
            'gd',
            'gi',
            'tst',
            's',
            'ms',
            'gd',
            'glsl',
            'fp',
            'frag',
            'frg',
            'node:fs',
            'fsh',
            'fshader',
            'geo',
            'geom',
            'glslv',
            'gshader',
            'shader',
            'vert',
            'vrx',
            'vsh',
            'vshader',
            'gml',
            'kid',
            'ebuild',
            'eclass',
            'po',
            'pot',
            'glf',
            'gp',
            'gnu',
            'gnuplot',
            'plot',
            'plt',
            'go',
            'golo',
            'gs',
            'gst',
            'gsx',
            'vark',
            'grace',
            'gradle',
            'gf',
            'gml',
            'graphql',
            'dot',
            'gv',
            'man',
            '1',
            '1in',
            '1m',
            '1x',
            '2',
            '3',
            '3in',
            '3m',
            '3qt',
            '3x',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'l',
            'me',
            'ms',
            'n',
            'rno',
            'roff',
            'groovy',
            'grt',
            'gtpl',
            'gvy',
            'gsp',
            'hcl',
            'tf',
            'hlsl',
            'fx',
            'fxh',
            'hlsli',
            'html',
            'htm',
            'html.hl',
            'inc',
            'st',
            'xht',
            'xhtml',
            'mustache',
            'jinja',
            'eex',
            'erb',
            'erb.deface',
            'phtml',
            'node:http',
            'hh',
            'php',
            'haml',
            'haml.deface',
            'handlebars',
            'hbs',
            'hb',
            'hs',
            'hsc',
            'hx',
            'hxsl',
            'hy',
            'bf',
            'pro',
            'dlm',
            'ipf',
            'ini',
            'cfg',
            'prefs',
            'pro',
            'properties',
            'irclog',
            'weechatlog',
            'idr',
            'lidr',
            'ni',
            'i7x',
            'iss',
            'io',
            'ik',
            'thy',
            'ijs',
            'flex',
            'jflex',
            'json',
            'geojson',
            'lock',
            'topojson',
            'json5',
            'jsonld',
            'jq',
            'jsx',
            'jade',
            'j',
            'java',
            'jsp',
            'js',
            '_js',
            'bones',
            'es',
            'es6',
            'frag',
            'gs',
            'jake',
            'jsb',
            'jscad',
            'jsfl',
            'jsm',
            'jss',
            'njs',
            'pac',
            'sjs',
            'ssjs',
            'sublime-build',
            'sublime-commands',
            'sublime-completions',
            'sublime-keymap',
            'sublime-macro',
            'sublime-menu',
            'sublime-mousemap',
            'sublime-project',
            'sublime-settings',
            'sublime-theme',
            'sublime-workspace',
            'sublime_metrics',
            'sublime_session',
            'xsjs',
            'xsjslib',
            'jl',
            'ipynb',
            'krl',
            'sch',
            'brd',
            'kicad_pcb',
            'kit',
            'kt',
            'ktm',
            'kts',
            'lfe',
            'll',
            'lol',
            'lsl',
            'lslp',
            'lvproj',
            'lasso',
            'las',
            'lasso8',
            'lasso9',
            'ldml',
            'latte',
            'lean',
            'hlean',
            'less',
            'l',
            'lex',
            'ly',
            'ily',
            'b',
            'm',
            'ld',
            'lds',
            'mod',
            'liquid',
            'lagda',
            'litcoffee',
            'lhs',
            'ls',
            '_ls',
            'xm',
            'x',
            'xi',
            'lgt',
            'logtalk',
            'lookml',
            'ls',
            'lua',
            'fcgi',
            'nse',
            'pd_lua',
            'rbxs',
            'wlua',
            'mumps',
            'm',
            'm4',
            'm4',
            'ms',
            'mcr',
            'mtml',
            'muf',
            'm',
            'mak',
            'd',
            'mk',
            'mkfile',
            'mako',
            'mao',
            'md',
            'markdown',
            'mkd',
            'mkdn',
            'mkdown',
            'ron',
            'mask',
            'mathematica',
            'cdf',
            'm',
            'ma',
            'mt',
            'nb',
            'nbp',
            'wl',
            'wlt',
            'matlab',
            'm',
            'maxpat',
            'maxhelp',
            'maxproj',
            'mxt',
            'pat',
            'mediawiki',
            'wiki',
            'm',
            'moo',
            'metal',
            'minid',
            'druby',
            'duby',
            'mir',
            'mirah',
            'mo',
            'mod',
            'mms',
            'mmk',
            'monkey',
            'moo',
            'moon',
            'myt',
            'ncl',
            'nl',
            'nsi',
            'nsh',
            'n',
            'axs',
            'axi',
            'axs.erb',
            'axi.erb',
            'nlogo',
            'nl',
            'lisp',
            'lsp',
            'nginxconf',
            'vhost',
            'nim',
            'nimrod',
            'ninja',
            'nit',
            'nix',
            'nu',
            'numpy',
            'numpyw',
            'numsc',
            'ml',
            'eliom',
            'eliomi',
            'ml4',
            'mli',
            'mll',
            'mly',
            'objdump',
            'm',
            'h',
            'mm',
            'j',
            'sj',
            'omgrofl',
            'opa',
            'opal',
            'cl',
            'opencl',
            'p',
            'cls',
            'scad',
            'org',
            'ox',
            'oxh',
            'oxo',
            'oxygene',
            'oz',
            'pwn',
            'inc',
            'php',
            'aw',
            'ctp',
            'fcgi',
            'inc',
            'php3',
            'php4',
            'php5',
            'phps',
            'phpt',
            'pls',
            'pck',
            'pkb',
            'pks',
            'plb',
            'plsql',
            'sql',
            'sql',
            'pov',
            'inc',
            'pan',
            'psc',
            'parrot',
            'pasm',
            'pir',
            'pas',
            'dfm',
            'dpr',
            'inc',
            'lpr',
            'pp',
            'pl',
            'al',
            'cgi',
            'fcgi',
            'perl',
            'ph',
            'plx',
            'pm',
            'pod',
            'psgi',
            't',
            '6pl',
            '6pm',
            'nqp',
            'p6',
            'p6l',
            'p6m',
            'pl',
            'pl6',
            'pm',
            'pm6',
            't',
            'pkl',
            'l',
            'pig',
            'pike',
            'pmod',
            'pod',
            'pogo',
            'pony',
            'ps',
            'eps',
            'ps1',
            'psd1',
            'psm1',
            'pde',
            'pl',
            'pro',
            'prolog',
            'yap',
            'spin',
            'proto',
            'asc',
            'pub',
            'pp',
            'pd',
            'pb',
            'pbi',
            'purs',
            'py',
            'bzl',
            'cgi',
            'fcgi',
            'gyp',
            'lmi',
            'pyde',
            'pyp',
            'pyt',
            'pyw',
            'rpy',
            'tac',
            'wsgi',
            'xpy',
            'pytb',
            'qml',
            'qbs',
            'pro',
            'pri',
            'r',
            'rd',
            'rsx',
            'raml',
            'rdoc',
            'rbbas',
            'rbfrm',
            'rbmnu',
            'rbres',
            'rbtbar',
            'rbuistate',
            'rhtml',
            'rmd',
            'rkt',
            'rktd',
            'rktl',
            'scrbl',
            'rl',
            'raw',
            'reb',
            'r',
            'r2',
            'r3',
            'rebol',
            'red',
            'reds',
            'cw',
            'rpy',
            'rs',
            'rsh',
            'robot',
            'rg',
            'rb',
            'builder',
            'fcgi',
            'gemspec',
            'god',
            'irbrc',
            'jbuilder',
            'mspec',
            'pluginspec',
            'podspec',
            'rabl',
            'rake',
            'rbuild',
            'rbw',
            'rbx',
            'ru',
            'ruby',
            'thor',
            'watchr',
            'rs',
            'rs.in',
            'sas',
            'scss',
            'smt2',
            'smt',
            'sparql',
            'rq',
            'sqf',
            'hqf',
            'sql',
            'cql',
            'ddl',
            'inc',
            'prc',
            'tab',
            'udf',
            'viw',
            'sql',
            'db2',
            'ston',
            'sage',
            'sagews',
            'sls',
            'sass',
            'scala',
            'sbt',
            'sc',
            'scaml',
            'scm',
            'sld',
            'sls',
            'sps',
            'ss',
            'sci',
            'sce',
            'tst',
            'self',
            'sh',
            'bash',
            'bats',
            'cgi',
            'command',
            'fcgi',
            'ksh',
            'sh.in',
            'tmux',
            'tool',
            'zsh',
            'sh-session',
            'shen',
            'sl',
            'slim',
            'smali',
            'st',
            'cs',
            'tpl',
            'sp',
            'inc',
            'sma',
            'nut',
            'stan',
            'ML',
            'fun',
            'sig',
            'sml',
            'do',
            'ado',
            'doh',
            'ihlp',
            'mata',
            'matah',
            'sthlp',
            'styl',
            'sc',
            'scd',
            'swift',
            'sv',
            'svh',
            'vh',
            'toml',
            'txl',
            'tcl',
            'adp',
            'tm',
            'tcsh',
            'csh',
            'tex',
            'aux',
            'bbx',
            'bib',
            'cbx',
            'cls',
            'dtx',
            'ins',
            'lbx',
            'ltx',
            'mkii',
            'mkiv',
            'mkvi',
            'sty',
            'toc',
            'tea',
            't',
            'txt',
            'fr',
            'nb',
            'ncl',
            'no',
            'textile',
            'thrift',
            't',
            'tu',
            'ttl',
            'twig',
            'ts',
            'tsx',
            'upc',
            'anim',
            'asset',
            'mat',
            'meta',
            'prefab',
            'unity',
            'uno',
            'uc',
            'ur',
            'urs',
            'vcl',
            'vhdl',
            'vhd',
            'vhf',
            'vhi',
            'vho',
            'vhs',
            'vht',
            'vhw',
            'vala',
            'vapi',
            'v',
            'veo',
            'vim',
            'vb',
            'bas',
            'cls',
            'frm',
            'frx',
            'vba',
            'vbhtml',
            'vbs',
            'volt',
            'vue',
            'owl',
            'webidl',
            'x10',
            'xc',
            'xml',
            'ant',
            'axml',
            'ccxml',
            'clixml',
            'cproject',
            'csl',
            'csproj',
            'ct',
            'dita',
            'ditamap',
            'ditaval',
            'dll.config',
            'dotsettings',
            'filters',
            'fsproj',
            'fxml',
            'glade',
            'gml',
            'grxml',
            'iml',
            'ivy',
            'jelly',
            'jsproj',
            'kml',
            'launch',
            'mdpolicy',
            'mm',
            'mod',
            'mxml',
            'nproj',
            'nuspec',
            'odd',
            'osm',
            'plist',
            'pluginspec',
            'props',
            'ps1xml',
            'psc1',
            'pt',
            'rdf',
            'rss',
            'scxml',
            'srdf',
            'storyboard',
            'stTheme',
            'sublime-snippet',
            'targets',
            'tmCommand',
            'tml',
            'tmLanguage',
            'tmPreferences',
            'tmSnippet',
            'tmTheme',
            'ts',
            'tsx',
            'ui',
            'urdf',
            'ux',
            'vbproj',
            'vcxproj',
            'vssettings',
            'vxml',
            'wsdl',
            'wsf',
            'wxi',
            'wxl',
            'wxs',
            'x3d',
            'xacro',
            'xaml',
            'xib',
            'xlf',
            'xliff',
            'xmi',
            'xml.dist',
            'xproj',
            'xsd',
            'xul',
            'zcml',
            'xsp-config',
            'xsp.metadata',
            'xpl',
            'xproc',
            'xquery',
            'xq',
            'xql',
            'xqm',
            'xqy',
            'xs',
            'xslt',
            'xsl',
            'xojo_code',
            'xojo_menu',
            'xojo_report',
            'xojo_script',
            'xojo_toolbar',
            'xojo_window',
            'xtend',
            'yml',
            'reek',
            'rviz',
            'sublime-syntax',
            'syntax',
            'yaml',
            'yaml-tmlanguage',
            'yang',
            'y',
            'yacc',
            'yy',
            'zep',
            'zimpl',
            'zmpl',
            'zpl',
            'desktop',
            'desktop.in',
            'ec',
            'eh',
            'edn',
            'fish',
            'mu',
            'nc',
            'ooc',
            'rst',
            'rest',
            'rest.txt',
            'rst.txt',
            'wisp',
            'prg',
            'ch',
            'prw',
        ],
    },
    emptyHtmlStringValues: ['<p><br/></p>', '<p><br></p>'] as string[],
    color: {
        error: '#d32f2f',
        warning: '#FFAC2F',
        enforcement: '#DD3500',
        failed: '#A40000',
        success: '#4FC318',
    },
    systemManagement: {
        actions: {
            unusedPropertyErrorCodeTs: '6133',
            noTypeGivenErrorCodeTs: '7044',
        },
    },
    formulaGetTodayVarName: '!TODAY_VAR', // '!' at start to not intersect with other variables
    isDev: import.meta.env.DEV && !import.meta.env.VITE_APP_IS_DOCKER,
} as const;
