// Icons 3
/** biome-ignore-all lint/suspicious/noShadowRestrictedNames: <explanation> */
import {
    BiAbacus as Abacus,
    BiAlarmExclamation as AlarmExclamation,
    BiAlarmSnooze as AlarmSnooze,
    BiAlignMiddle as AlignMiddle,
    BiAnalyse as Analyse,
    BiAperture as Aperture,
    BiArch as Arch,
    BiArchiveIn as ArchiveIn,
    BiArchiveOut as ArchiveOut,
    BiArea as Area,
    BiArrowFromBottom as ArrowFromBottom,
    BiArrowFromLeft as ArrowFromLeft,
    BiArrowFromRight as ArrowFromRight,
    BiArrowFromTop as ArrowFromTop,
    BiArrowToBottom as ArrowToBottom,
    BiArrowToLeft as ArrowToLeft,
    BiArrowToRight as ArrowToRight,
    BiArrowToTop as ArrowToTop,
    BiBadgeCheck as BadgeCheck,
    BiBaguette as Baguette,
    BiBall as Ball,
    BiBarChartAlt as BarChartAlt,
    BiBarChartAlt2 as BarChartAlt2,
    BiBarChartSquare as BarChartSquare,
    BiBarcodeReader as BarcodeReader,
    BiBaseball as Baseball,
    BiBasket as Basket,
    BiBasketball as Basketball,
    BiBattery as Battery,
    BiBeenHere as BeenHere,
    BiBellMinus as BellMinus,
    BiBellOff as BellOff,
    BiBellPlus as BellPlus,
    BiBlanket as Blanket,
    BiBody as Body,
    BiBoltCircle as BoltCircle,
    BiBookAdd as BookAdd,
    BiBookAlt as BookAlt,
    BiBookBookmark as BookBookmark,
    BiBookContent as BookContent,
    BiBookHeart as BookHeart,
    BiBookmarkAlt as BookmarkAlt,
    BiBookmarkAltMinus as BookmarkAltMinus,
    BiBookmarkAltPlus as BookmarkAltPlus,
    BiBookmarkHeart as BookmarkHeart,
    BiBookmarkMinus as BookmarkMinus,
    BiBookmarkPlus as BookmarkPlus,
    BiBorderRadius as BorderRadius,
    BiBot as Bot,
    BiBowlHot as BowlHot,
    BiBowlRice as BowlRice,
    BiBracket as Bracket,
    BiBriefcaseAlt as BriefcaseAlt,
    BiBriefcaseAlt2 as BriefcaseAlt2,
    BiBrightness as Brightness,
    BiBrightnessHalf as BrightnessHalf,
    BiBroadcast as Broadcast,
    BiBrushAlt as BrushAlt,
    BiBugAlt as BugAlt,
    BiBuildingHouse as BuildingHouse,
    BiBuildings as Buildings,
    BiBulb as Bulb,
    BiBuoy as Buoy,
    BiBusSchool as BusSchool,
    BiCabinet as Cabinet,
    BiCableCar as CableCar,
    BiCalendarEdit as CalendarEdit,
    BiCalendarEvent as CalendarEvent,
    BiCalendarExclamation as CalendarExclamation,
    BiCalendarHeart as CalendarHeart,
    BiCalendarStar as CalendarStar,
    BiCalendarX as CalendarX,
    BiCameraHome as CameraHome,
    BiCameraMovie as CameraMovie,
    BiCameraOff as CameraOff,
    BiCandles as Candles,
    BiCapsule as Capsule,
    BiCaptions as Captions,
    BiCard as Card,
    BiCaretDownCircle as CaretDownCircle,
    BiCaretDownSquare as CaretDownSquare,
    BiCaretLeftCircle as CaretLeftCircle,
    BiCaretLeftSquare as CaretLeftSquare,
    BiCaretRightCircle as CaretRightCircle,
    BiCaretRightSquare as CaretRightSquare,
    BiCaretUpCircle as CaretUpCircle,
    BiCaretUpSquare as CaretUpSquare,
    BiCarousel as Carousel,
    BiCart as Cart,
    BiCartAdd as CartAdd,
    BiCartAlt as CartAlt,
    BiCartDownload as CartDownload,
    BiCategoryAlt as CategoryAlt,
    BiCctv as Cctv,
    BiCertification as Certification,
    BiChart as Chart,
    BiCheckbox as Checkbox,
    BiCheckboxChecked as CheckboxChecked,
    BiCheckboxMinus as CheckboxMinus,
    BiCheckboxSquare as CheckboxSquare,
    BiCheckShield as CheckShield,
    BiChevronDownCircle as ChevronDownCircle,
    BiChevronDownSquare as ChevronDownSquare,
    BiChevronLeftCircle as ChevronLeftCircle,
    BiChevronLeftSquare as ChevronLeftSquare,
    BiChevronRightCircle as ChevronRightCircle,
    BiChevronRightSquare as ChevronRightSquare,
    BiChevronsDown as ChevronsDown,
    BiChevronsLeft as ChevronsLeft,
    BiChevronsRight as ChevronsRight,
    BiChevronsUp as ChevronsUp,
    BiChevronUpCircle as ChevronUpCircle,
    BiChevronUpSquare as ChevronUpSquare,
    BiChip as Chip,
    BiCircleHalf as CircleHalf,
    BiCircleQuarter as CircleQuarter,
    BiCircleThreeQuarter as CircleThreeQuarter,
    BiClinic as Clinic,
    BiCloset as Closet,
    BiCloudDrizzle as CloudDrizzle,
    BiCloudLightning as CloudLightning,
    BiCloudLightRain as CloudLightRain,
    BiCloudSnow as CloudSnow,
    BiCodeAlt as CodeAlt,
    BiCodeBlock as CodeBlock,
    BiCodeCurly as CodeCurly,
    BiCoffeeTogo as CoffeeTogo,
    BiCoin as Coin,
    BiCoinStack as CoinStack,
    BiCollapse as Collapse,
    BiCollapseAlt as CollapseAlt,
    BiCollapseHorizontal as CollapseHorizontal,
    BiCollapseVertical as CollapseVertical,
    BiCollection as Collection,
    BiColor as Color,
    BiColorFill as ColorFill,
    BiCommand as Command,
    BiCommentAdd as CommentAdd,
    BiCommentCheck as CommentCheck,
    BiCommentDetail as CommentDetail,
    BiCommentEdit as CommentEdit,
    BiCommentError as CommentError,
    BiCommentMinus as CommentMinus,
    BiCommentX as CommentX,
    BiConfused as Confused,
    BiConversation as Conversation,
    BiCool as Cool,
    BiCopyAlt as CopyAlt,
    BiCreditCardAlt as CreditCardAlt,
    BiCreditCardFront as CreditCardFront,
    BiCricketBall as CricketBall,
    BiCrosshair as Crosshair,
    BiCubeAlt as CubeAlt,
    BiCuboid as Cuboid,
    BiCurrentLocation as CurrentLocation,
    BiCustomize as Customize,
    BiCycling as Cycling,
    BiCylinder as Cylinder,
    BiData as Data,
    BiDetail as Detail,
    BiDialpadAlt as DialpadAlt,
    BiDice1 as Dice1,
    BiDice2 as Dice2,
    BiDice3 as Dice3,
    BiDice4 as Dice4,
    BiDice5 as Dice5,
    BiDice6 as Dice6,
    BiDisc as Disc,
    BiDish as Dish,
    BiDislike as Dislike,
    BiDockBottom as DockBottom,
    BiDockLeft as DockLeft,
    BiDockRight as DockRight,
    BiDockTop as DockTop,
    BiDollar as Dollar,
    BiDollarCircle as DollarCircle,
    BiDonateBlood as DonateBlood,
    BiDonateHeart as DonateHeart,
    BiDotsHorizontal as DotsHorizontal,
    BiDotsHorizontalRounded as DotsHorizontalRounded,
    BiDotsVertical as DotsVertical,
    BiDotsVerticalRounded as DotsVerticalRounded,
    BiDoughnutChart as DoughnutChart,
    BiDownArrow as DownArrow,
    BiDownArrowAlt as DownArrowAlt,
    BiDownArrowCircle as DownArrowCircle,
    BiDownvote as Downvote,
    BiDrink as Drink,
    BiDroplet as Droplet,
    BiDuplicate as Duplicate,
    BiEditAlt as EditAlt,
    BiErrorAlt as ErrorAlt,
    BiErrorCircle as ErrorCircle,
    BiExclude as Exclude,
    BiExit as Exit,
    BiExitFullscreen as ExitFullscreen,
    BiExpandHorizontal as ExpandHorizontal,
    BiExpandVertical as ExpandVertical,
    BiExport as Export,
    BiFastForwardCircle as FastForwardCircle,
    BiFemaleSign as FemaleSign,
    BiFileBlank as FileBlank,
    BiFileFind as FileFind,
    BiFontColor as FontColor,
    BiFontFamily as FontFamily,
    BiFontSize as FontSize,
    BiFoodMenu as FoodMenu,
    BiFoodTag as FoodTag,
    BiFootball as Football,
    BiFork as Fork,
    BiFridge as Fridge,
    BiGame as Game,
    BiGitBranch as GitBranch,
    BiGitCommit as GitCommit,
    BiGitCompare as GitCompare,
    BiGitMerge as GitMerge,
    BiGitPullRequest as GitPullRequest,
    BiGitRepoForked as GitRepoForked,
    BiGlassesAlt as GlassesAlt,
    BiGlobeAlt as GlobeAlt,
    BiGrid as Grid,
    BiGridAlt as GridAlt,
    BiGridHorizontal as GridHorizontal,
    BiGridSmall as GridSmall,
    BiGridVertical as GridVertical,
    BiHandicap as Handicap,
    BiHappy as Happy,
    BiHappyAlt as HappyAlt,
    BiHappyBeaming as HappyBeaming,
    BiHappyHeartEyes as HappyHeartEyes,
    BiHash as Hash,
    BiHeadphone as Headphone,
    BiHealth as Health,
    BiHeartCircle as HeartCircle,
    BiHeartSquare as HeartSquare,
    BiHelpCircle as HelpCircle,
    BiHide as Hide,
    BiHomeAlt as HomeAlt,
    BiHomeAlt2 as HomeAlt2,
    BiHomeCircle as HomeCircle,
    BiHomeHeart as HomeHeart,
    BiHomeSmile as HomeSmile,
    BiHorizontalCenter as HorizontalCenter,
    BiHorizontalLeft as HorizontalLeft,
    BiHorizontalRight as HorizontalRight,
    BiImageAdd as ImageAdd,
    BiImageAlt as ImageAlt,
    BiImport as Import,
    BiInfinite as Infinite,
    BiInfoSquare as InfoSquare,
    BiInjection as Injection,
    BiIntersect as Intersect,
    BiJoystick as Joystick,
    BiJoystickAlt as JoystickAlt,
    BiJoystickButton as JoystickButton,
    BiKnife as Knife,
    BiLayer as Layer,
    BiLayerMinus as LayerMinus,
    BiLayerPlus as LayerPlus,
    BiLayout as Layout,
    BiLeftArrow as LeftArrow,
    BiLeftArrowAlt as LeftArrowAlt,
    BiLeftArrowCircle as LeftArrowCircle,
    BiLeftDownArrowCircle as LeftDownArrowCircle,
    BiLeftIndent as LeftIndent,
    BiLeftTopArrowCircle as LeftTopArrowCircle,
    BiLibrary as Library,
    BiLike as Like,
    BiLineChart as LineChart,
    BiLineChartDown as LineChartDown,
    BiLinkAlt as LinkAlt,
    BiLinkExternal as LinkExternal,
    BiLira as Lira,
    BiListCheck as ListCheck,
    BiListMinus as ListMinus,
    BiListPlus as ListPlus,
    BiLoader as Loader,
    BiLoaderAlt as LoaderAlt,
    BiLoaderCircle as LoaderCircle,
    BiLocationPlus as LocationPlus,
    BiLockAlt as LockAlt,
    BiLockOpenAlt as LockOpenAlt,
    BiLogIn as LogIn,
    BiLogInCircle as LogInCircle,
    BiLogOut as LogOut,
    BiLogOutCircle as LogOutCircle,
    BiLogo99Designs as Logo99Designs,
    BiLogo500Px as Logo500Px,
    BiLogoAdobe as LogoAdobe,
    BiLogoAirbnb as LogoAirbnb,
    BiLogoAlgolia as LogoAlgolia,
    BiLogoAmazon as LogoAmazon,
    BiLogoAndroid as LogoAndroid,
    BiLogoAngular as LogoAngular,
    BiLogoApple as LogoApple,
    BiLogoAudible as LogoAudible,
    BiLogoAws as LogoAws,
    BiLogoBaidu as LogoBaidu,
    BiLogoBehance as LogoBehance,
    BiLogoBing as LogoBing,
    BiLogoBitcoin as LogoBitcoin,
    BiLogoBlender as LogoBlender,
    BiLogoBlogger as LogoBlogger,
    BiLogoBootstrap as LogoBootstrap,
    BiLogoChrome as LogoChrome,
    BiLogoCodepen as LogoCodepen,
    BiLogoCPlusPlus as LogoCPlusPlus,
    BiLogoCreativeCommons as LogoCreativeCommons,
    BiLogoCss3 as LogoCss3,
    BiLogoDailymotion as LogoDailymotion,
    BiLogoDeezer as LogoDeezer,
    BiLogoDeviantart as LogoDeviantart,
    BiLogoDevTo as LogoDevTo,
    BiLogoDigg as LogoDigg,
    BiLogoDigitalocean as LogoDigitalocean,
    BiLogoDiscord as LogoDiscord,
    BiLogoDiscordAlt as LogoDiscordAlt,
    BiLogoDiscourse as LogoDiscourse,
    BiLogoDjango as LogoDjango,
    BiLogoDocker as LogoDocker,
    BiLogoDribbble as LogoDribbble,
    BiLogoDropbox as LogoDropbox,
    BiLogoDrupal as LogoDrupal,
    BiLogoEbay as LogoEbay,
    BiLogoEdge as LogoEdge,
    BiLogoEtsy as LogoEtsy,
    BiLogoFacebook as LogoFacebook,
    BiLogoFacebookCircle as LogoFacebookCircle,
    BiLogoFacebookSquare as LogoFacebookSquare,
    BiLogoFigma as LogoFigma,
    BiLogoFirebase as LogoFirebase,
    BiLogoFirefox as LogoFirefox,
    BiLogoFlask as LogoFlask,
    BiLogoFlickr as LogoFlickr,
    BiLogoFlickrSquare as LogoFlickrSquare,
    BiLogoFlutter as LogoFlutter,
    BiLogoFoursquare as LogoFoursquare,
    BiLogoGit as LogoGit,
    BiLogoGithub as LogoGithub,
    BiLogoGitlab as LogoGitlab,
    BiLogoGmail as LogoGmail,
    BiLogoGoLang as LogoGoLang,
    BiLogoGoogle as LogoGoogle,
    BiLogoGoogleCloud as LogoGoogleCloud,
    BiLogoGooglePlus as LogoGooglePlus,
    BiLogoGooglePlusCircle as LogoGooglePlusCircle,
    BiLogoGraphql as LogoGraphql,
    BiLogoHeroku as LogoHeroku,
    BiLogoHtml5 as LogoHtml5,
    BiLogoImdb as LogoImdb,
    BiLogoInstagram as LogoInstagram,
    BiLogoInstagramAlt as LogoInstagramAlt,
    BiLogoInternetExplorer as LogoInternetExplorer,
    BiLogoInvision as LogoInvision,
    BiLogoJava as LogoJava,
    BiLogoJavascript as LogoJavascript,
    BiLogoJoomla as LogoJoomla,
    BiLogoJquery as LogoJquery,
    BiLogoJsfiddle as LogoJsfiddle,
    BiLogoKickstarter as LogoKickstarter,
    BiLogoKubernetes as LogoKubernetes,
    BiLogoLess as LogoLess,
    BiLogoLinkedin as LogoLinkedin,
    BiLogoLinkedinSquare as LogoLinkedinSquare,
    BiLogoMagento as LogoMagento,
    BiLogoMailchimp as LogoMailchimp,
    BiLogoMarkdown as LogoMarkdown,
    BiLogoMastercard as LogoMastercard,
    BiLogoMastodon as LogoMastodon,
    BiLogoMedium as LogoMedium,
    BiLogoMediumOld as LogoMediumOld,
    BiLogoMediumSquare as LogoMediumSquare,
    BiLogoMessenger as LogoMessenger,
    BiLogoMeta as LogoMeta,
    BiLogoMicrosoft as LogoMicrosoft,
    BiLogoMicrosoftTeams as LogoMicrosoftTeams,
    BiLogoMongodb as LogoMongodb,
    BiLogoNetlify as LogoNetlify,
    BiLogoNodejs as LogoNodejs,
    BiLogoOkRu as LogoOkRu,
    BiLogoOpera as LogoOpera,
    BiLogoPatreon as LogoPatreon,
    BiLogoPaypal as LogoPaypal,
    BiLogoPeriscope as LogoPeriscope,
    BiLogoPhp as LogoPhp,
    BiLogoPinterest as LogoPinterest,
    BiLogoPinterestAlt as LogoPinterestAlt,
    BiLogoPlayStore as LogoPlayStore,
    BiLogoPocket as LogoPocket,
    BiLogoPostgresql as LogoPostgresql,
    BiLogoProductHunt as LogoProductHunt,
    BiLogoPython as LogoPython,
    BiLogoQuora as LogoQuora,
    BiLogoReact as LogoReact,
    BiLogoRedbubble as LogoRedbubble,
    BiLogoReddit as LogoReddit,
    BiLogoRedux as LogoRedux,
    BiLogoSass as LogoSass,
    BiLogoShopify as LogoShopify,
    BiLogoSketch as LogoSketch,
    BiLogoSkype as LogoSkype,
    BiLogoSlack as LogoSlack,
    BiLogoSlackOld as LogoSlackOld,
    BiLogoSnapchat as LogoSnapchat,
    BiLogoSoundcloud as LogoSoundcloud,
    BiLogoSpotify as LogoSpotify,
    BiLogoSpringBoot as LogoSpringBoot,
    BiLogoSquarespace as LogoSquarespace,
    BiLogoStackOverflow as LogoStackOverflow,
    BiLogoSteam as LogoSteam,
    BiLogoStripe as LogoStripe,
    BiLogoTailwindCss as LogoTailwindCss,
    BiLogoTelegram as LogoTelegram,
    BiLogoTiktok as LogoTiktok,
    BiLogoTrello as LogoTrello,
    BiLogoTripAdvisor as LogoTripAdvisor,
    BiLogoTumblr as LogoTumblr,
    BiLogoTux as LogoTux,
    BiLogoTwitch as LogoTwitch,
    BiLogoTwitter as LogoTwitter,
    BiLogoTypescript as LogoTypescript,
    BiLogoUnity as LogoUnity,
    BiLogoUnsplash as LogoUnsplash,
    BiLogoUpwork as LogoUpwork,
    BiLogoVenmo as LogoVenmo,
    BiLogoVimeo as LogoVimeo,
    BiLogoVisa as LogoVisa,
    BiLogoVisualStudio as LogoVisualStudio,
    BiLogoVk as LogoVk,
    BiLogoVuejs as LogoVuejs,
    BiLogoWhatsapp as LogoWhatsapp,
    BiLogoWhatsappSquare as LogoWhatsappSquare,
    BiLogoWikipedia as LogoWikipedia,
    BiLogoWindows as LogoWindows,
    BiLogoWix as LogoWix,
    BiLogoWordpress as LogoWordpress,
    BiLogoXing as LogoXing,
    BiLogoYahoo as LogoYahoo,
    BiLogoYelp as LogoYelp,
    BiLogoYoutube as LogoYoutube,
    BiLogoZoom as LogoZoom,
    BiMailSend as MailSend,
    BiMaleFemale as MaleFemale,
    BiMaleSign as MaleSign,
    BiMapAlt as MapAlt,
    BiMath as Math,
    BiMehAlt as MehAlt,
    BiMemoryCard as MemoryCard,
    BiMenuAltLeft as MenuAltLeft,
    BiMenuAltRight as MenuAltRight,
    BiMessageAdd as MessageAdd,
    BiMessageAlt as MessageAlt,
    BiMessageAltAdd as MessageAltAdd,
    BiMessageAltCheck as MessageAltCheck,
    BiMessageAltDetail as MessageAltDetail,
    BiMessageAltDots as MessageAltDots,
    BiMessageAltEdit as MessageAltEdit,
    BiMessageAltError as MessageAltError,
    BiMessageAltMinus as MessageAltMinus,
    BiMessageAltX as MessageAltX,
    BiMessageCheck as MessageCheck,
    BiMessageDetail as MessageDetail,
    BiMessageDots as MessageDots,
    BiMessageEdit as MessageEdit,
    BiMessageError as MessageError,
    BiMessageMinus as MessageMinus,
    BiMessageRounded as MessageRounded,
    BiMessageRoundedAdd as MessageRoundedAdd,
    BiMessageRoundedCheck as MessageRoundedCheck,
    BiMessageRoundedDetail as MessageRoundedDetail,
    BiMessageRoundedDots as MessageRoundedDots,
    BiMessageRoundedEdit as MessageRoundedEdit,
    BiMessageRoundedError as MessageRoundedError,
    BiMessageRoundedMinus as MessageRoundedMinus,
    BiMessageRoundedX as MessageRoundedX,
    BiMessageSquare as MessageSquare,
    BiMessageSquareAdd as MessageSquareAdd,
    BiMessageSquareCheck as MessageSquareCheck,
    BiMessageSquareDetail as MessageSquareDetail,
    BiMessageSquareDots as MessageSquareDots,
    BiMessageSquareEdit as MessageSquareEdit,
    BiMessageSquareError as MessageSquareError,
    BiMessageSquareMinus as MessageSquareMinus,
    BiMessageSquareX as MessageSquareX,
    BiMessageX as MessageX,
    BiMicrophoneOff as MicrophoneOff,
    BiMinusBack as MinusBack,
    BiMinusFront as MinusFront,
    BiMobileLandscape as MobileLandscape,
    BiMobileVibration as MobileVibration,
    BiMoneyWithdraw as MoneyWithdraw,
    BiMouseAlt as MouseAlt,
    BiMove as Move,
    BiMoveHorizontal as MoveHorizontal,
    BiMoveVertical as MoveVertical,
    BiMoviePlay as MoviePlay,
    BiNetworkChart as NetworkChart,
    BiNews as News,
    BiNoEntry as NoEntry,
    BiNoSignal as NoSignal,
    BiNotepad as Notepad,
    BiNotification as Notification,
    BiNotificationOff as NotificationOff,
    BiObjectsHorizontalCenter as ObjectsHorizontalCenter,
    BiObjectsHorizontalLeft as ObjectsHorizontalLeft,
    BiObjectsHorizontalRight as ObjectsHorizontalRight,
    BiObjectsVerticalBottom as ObjectsVerticalBottom,
    BiObjectsVerticalCenter as ObjectsVerticalCenter,
    BiObjectsVerticalTop as ObjectsVerticalTop,
    BiOutline as Outline,
    BiPackage as Package,
    BiPaint as Paint,
    BiPaintRoll as PaintRoll,
    BiParty as Party,
    BiPencil as Pencil,
    BiPhoneCall as PhoneCall,
    BiPhoneIncoming as PhoneIncoming,
    BiPhoneOff as PhoneOff,
    BiPhoneOutgoing as PhoneOutgoing,
    BiPieChartAlt as PieChartAlt,
    BiPieChartAlt2 as PieChartAlt2,
    BiPlanet as Planet,
    BiPlusMedical as PlusMedical,
    BiPointer as Pointer,
    BiPolygon as Polygon,
    BiPopsicle as Popsicle,
    BiPound as Pound,
    BiPrinter as Printer,
    BiPulse as Pulse,
    BiPurchaseTag as PurchaseTag,
    BiPurchaseTagAlt as PurchaseTagAlt,
    BiPyramid as Pyramid,
    BiQr as Qr,
    BiQrScan as QrScan,
    BiRadioCircle as RadioCircle,
    BiRadioCircleMarked as RadioCircleMarked,
    BiReflectHorizontal as ReflectHorizontal,
    BiReflectVertical as ReflectVertical,
    BiRename as Rename,
    BiRepost as Repost,
    BiReset as Reset,
    BiRevision as Revision,
    BiRewind as Rewind,
    BiRewindCircle as RewindCircle,
    BiRfid as Rfid,
    BiRightArrow as RightArrow,
    BiRightArrowAlt as RightArrowAlt,
    BiRightArrowCircle as RightArrowCircle,
    BiRightDownArrowCircle as RightDownArrowCircle,
    BiRightIndent as RightIndent,
    BiRightTopArrowCircle as RightTopArrowCircle,
    BiRuble as Ruble,
    BiRun as Run,
    BiRupee as Rupee,
    BiSad as Sad,
    BiScan as Scan,
    BiScatterChart as ScatterChart,
    BiSearchAlt as SearchAlt,
    BiSearchAlt2 as SearchAlt2,
    BiSelection as Selection,
    BiSelectMultiple as SelectMultiple,
    BiShapeCircle as ShapeCircle,
    BiShapePolygon as ShapePolygon,
    BiShapeSquare as ShapeSquare,
    BiShapeTriangle as ShapeTriangle,
    BiShekel as Shekel,
    BiShieldAlt2 as ShieldAlt2,
    BiShieldMinus as ShieldMinus,
    BiShieldPlus as ShieldPlus,
    BiShieldQuarter as ShieldQuarter,
    BiShieldX as ShieldX,
    BiShocked as Shocked,
    BiShow as Show,
    BiShowAlt as ShowAlt,
    BiSidebar as Sidebar,
    BiSignal1 as Signal1,
    BiSignal2 as Signal2,
    BiSignal3 as Signal3,
    BiSignal4 as Signal4,
    BiSignal5 as Signal5,
    BiSkipNextCircle as SkipNextCircle,
    BiSkipPreviousCircle as SkipPreviousCircle,
    BiSleepy as Sleepy,
    BiSlider as Slider,
    BiSliderAlt as SliderAlt,
    BiSolidAddToQueue as SolidAddToQueue,
    BiSolidAdjust as SolidAdjust,
    BiSolidAdjustAlt as SolidAdjustAlt,
    BiSolidAlarm as SolidAlarm,
    BiSolidAlarmAdd as SolidAlarmAdd,
    BiSolidAlarmExclamation as SolidAlarmExclamation,
    BiSolidAlarmOff as SolidAlarmOff,
    BiSolidAlarmSnooze as SolidAlarmSnooze,
    BiSolidAlbum as SolidAlbum,
    BiSolidAmbulance as SolidAmbulance,
    BiSolidAnalyse as SolidAnalyse,
    BiSolidAngry as SolidAngry,
    BiSolidArch as SolidArch,
    BiSolidArchive as SolidArchive,
    BiSolidArchiveIn as SolidArchiveIn,
    BiSolidArchiveOut as SolidArchiveOut,
    BiSolidArea as SolidArea,
    BiSolidArrowFromBottom as SolidArrowFromBottom,
    BiSolidArrowFromLeft as SolidArrowFromLeft,
    BiSolidArrowFromRight as SolidArrowFromRight,
    BiSolidArrowFromTop as SolidArrowFromTop,
    BiSolidArrowToBottom as SolidArrowToBottom,
    BiSolidArrowToLeft as SolidArrowToLeft,
    BiSolidArrowToRight as SolidArrowToRight,
    BiSolidArrowToTop as SolidArrowToTop,
    BiSolidAward as SolidAward,
    BiSolidBabyCarriage as SolidBabyCarriage,
    BiSolidBackpack as SolidBackpack,
    BiSolidBadge as SolidBadge,
    BiSolidBadgeCheck as SolidBadgeCheck,
    BiSolidBadgeDollar as SolidBadgeDollar,
    BiSolidBaguette as SolidBaguette,
    BiSolidBall as SolidBall,
    BiSolidBalloon as SolidBalloon,
    BiSolidBandAid as SolidBandAid,
    BiSolidBank as SolidBank,
    BiSolidBarChartAlt2 as SolidBarChartAlt2,
    BiSolidBarChartSquare as SolidBarChartSquare,
    BiSolidBarcode as SolidBarcode,
    BiSolidBaseball as SolidBaseball,
    BiSolidBasket as SolidBasket,
    BiSolidBasketball as SolidBasketball,
    BiSolidBath as SolidBath,
    BiSolidBattery as SolidBattery,
    BiSolidBatteryCharging as SolidBatteryCharging,
    BiSolidBatteryFull as SolidBatteryFull,
    BiSolidBatteryLow as SolidBatteryLow,
    BiSolidBed as SolidBed,
    BiSolidBeenHere as SolidBeenHere,
    BiSolidBeer as SolidBeer,
    BiSolidBell as SolidBell,
    BiSolidBellMinus as SolidBellMinus,
    BiSolidBellOff as SolidBellOff,
    BiSolidBellPlus as SolidBellPlus,
    BiSolidBellRing as SolidBellRing,
    BiSolidBible as SolidBible,
    BiSolidBinoculars as SolidBinoculars,
    BiSolidBlanket as SolidBlanket,
    BiSolidBolt as SolidBolt,
    BiSolidBoltCircle as SolidBoltCircle,
    BiSolidBomb as SolidBomb,
    BiSolidBone as SolidBone,
    BiSolidBong as SolidBong,
    BiSolidBook as SolidBook,
    BiSolidBookAdd as SolidBookAdd,
    BiSolidBookAlt as SolidBookAlt,
    BiSolidBookBookmark as SolidBookBookmark,
    BiSolidBookContent as SolidBookContent,
    BiSolidBookHeart as SolidBookHeart,
    BiSolidBookmark as SolidBookmark,
    BiSolidBookmarkAlt as SolidBookmarkAlt,
    BiSolidBookmarkAltMinus as SolidBookmarkAltMinus,
    BiSolidBookmarkAltPlus as SolidBookmarkAltPlus,
    BiSolidBookmarkHeart as SolidBookmarkHeart,
    BiSolidBookmarkMinus as SolidBookmarkMinus,
    BiSolidBookmarkPlus as SolidBookmarkPlus,
    BiSolidBookmarkStar as SolidBookmarkStar,
    BiSolidBookmarks as SolidBookmarks,
    BiSolidBookOpen as SolidBookOpen,
    BiSolidBookReader as SolidBookReader,
    BiSolidBot as SolidBot,
    BiSolidBowlHot as SolidBowlHot,
    BiSolidBowlingBall as SolidBowlingBall,
    BiSolidBowlRice as SolidBowlRice,
    BiSolidBox as SolidBox,
    BiSolidBrain as SolidBrain,
    BiSolidBriefcase as SolidBriefcase,
    BiSolidBriefcaseAlt as SolidBriefcaseAlt,
    BiSolidBriefcaseAlt2 as SolidBriefcaseAlt2,
    BiSolidBrightness as SolidBrightness,
    BiSolidBrightnessHalf as SolidBrightnessHalf,
    BiSolidBrush as SolidBrush,
    BiSolidBrushAlt as SolidBrushAlt,
    BiSolidBug as SolidBug,
    BiSolidBugAlt as SolidBugAlt,
    BiSolidBuilding as SolidBuilding,
    BiSolidBuildingHouse as SolidBuildingHouse,
    BiSolidBuildings as SolidBuildings,
    BiSolidBulb as SolidBulb,
    BiSolidBullseye as SolidBullseye,
    BiSolidBuoy as SolidBuoy,
    BiSolidBus as SolidBus,
    BiSolidBusiness as SolidBusiness,
    BiSolidBusSchool as SolidBusSchool,
    BiSolidCabinet as SolidCabinet,
    BiSolidCableCar as SolidCableCar,
    BiSolidCake as SolidCake,
    BiSolidCalculator as SolidCalculator,
    BiSolidCalendar as SolidCalendar,
    BiSolidCalendarAlt as SolidCalendarAlt,
    BiSolidCalendarCheck as SolidCalendarCheck,
    BiSolidCalendarEdit as SolidCalendarEdit,
    BiSolidCalendarEvent as SolidCalendarEvent,
    BiSolidCalendarExclamation as SolidCalendarExclamation,
    BiSolidCalendarHeart as SolidCalendarHeart,
    BiSolidCalendarMinus as SolidCalendarMinus,
    BiSolidCalendarPlus as SolidCalendarPlus,
    BiSolidCalendarStar as SolidCalendarStar,
    BiSolidCalendarWeek as SolidCalendarWeek,
    BiSolidCalendarX as SolidCalendarX,
    BiSolidCamera as SolidCamera,
    BiSolidCameraHome as SolidCameraHome,
    BiSolidCameraMovie as SolidCameraMovie,
    BiSolidCameraOff as SolidCameraOff,
    BiSolidCameraPlus as SolidCameraPlus,
    BiSolidCapsule as SolidCapsule,
    BiSolidCaptions as SolidCaptions,
    BiSolidCar as SolidCar,
    BiSolidCarBattery as SolidCarBattery,
    BiSolidCarCrash as SolidCarCrash,
    BiSolidCard as SolidCard,
    BiSolidCaretDownCircle as SolidCaretDownCircle,
    BiSolidCaretDownSquare as SolidCaretDownSquare,
    BiSolidCaretLeftCircle as SolidCaretLeftCircle,
    BiSolidCaretLeftSquare as SolidCaretLeftSquare,
    BiSolidCaretRightCircle as SolidCaretRightCircle,
    BiSolidCaretRightSquare as SolidCaretRightSquare,
    BiSolidCaretUpCircle as SolidCaretUpCircle,
    BiSolidCaretUpSquare as SolidCaretUpSquare,
    BiSolidCarGarage as SolidCarGarage,
    BiSolidCarMechanic as SolidCarMechanic,
    BiSolidCarousel as SolidCarousel,
    BiSolidCart as SolidCart,
    BiSolidCartAdd as SolidCartAdd,
    BiSolidCartAlt as SolidCartAlt,
    BiSolidCartDownload as SolidCartDownload,
    BiSolidCarWash as SolidCarWash,
    BiSolidCastle as SolidCastle,
    BiSolidCat as SolidCat,
    BiSolidCategory as SolidCategory,
    BiSolidCategoryAlt as SolidCategoryAlt,
    BiSolidCctv as SolidCctv,
    BiSolidCertification as SolidCertification,
    BiSolidChalkboard as SolidChalkboard,
    BiSolidChart as SolidChart,
    BiSolidChat as SolidChat,
    BiSolidCheckbox as SolidCheckbox,
    BiSolidCheckboxChecked as SolidCheckboxChecked,
    BiSolidCheckboxMinus as SolidCheckboxMinus,
    BiSolidCheckCircle as SolidCheckCircle,
    BiSolidCheckShield as SolidCheckShield,
    BiSolidCheckSquare as SolidCheckSquare,
    BiSolidCheese as SolidCheese,
    BiSolidChess as SolidChess,
    BiSolidChevronDown as SolidChevronDown,
    BiSolidChevronDownCircle as SolidChevronDownCircle,
    BiSolidChevronDownSquare as SolidChevronDownSquare,
    BiSolidChevronLeft as SolidChevronLeft,
    BiSolidChevronLeftCircle as SolidChevronLeftCircle,
    BiSolidChevronLeftSquare as SolidChevronLeftSquare,
    BiSolidChevronRight as SolidChevronRight,
    BiSolidChevronRightCircle as SolidChevronRightCircle,
    BiSolidChevronRightSquare as SolidChevronRightSquare,
    BiSolidChevronsDown as SolidChevronsDown,
    BiSolidChevronsLeft as SolidChevronsLeft,
    BiSolidChevronsRight as SolidChevronsRight,
    BiSolidChevronsUp as SolidChevronsUp,
    BiSolidChevronUp as SolidChevronUp,
    BiSolidChevronUpCircle as SolidChevronUpCircle,
    BiSolidChevronUpSquare as SolidChevronUpSquare,
    BiSolidChip as SolidChip,
    BiSolidChurch as SolidChurch,
    BiSolidCircle as SolidCircle,
    BiSolidCircleHalf as SolidCircleHalf,
    BiSolidCircleQuarter as SolidCircleQuarter,
    BiSolidCircleThreeQuarter as SolidCircleThreeQuarter,
    BiSolidCity as SolidCity,
    BiSolidClinic as SolidClinic,
    BiSolidCloud as SolidCloud,
    BiSolidCloudDownload as SolidCloudDownload,
    BiSolidCloudLightning as SolidCloudLightning,
    BiSolidCloudRain as SolidCloudRain,
    BiSolidCloudUpload as SolidCloudUpload,
    BiSolidCoffee as SolidCoffee,
    BiSolidCoffeeAlt as SolidCoffeeAlt,
    BiSolidCoffeeBean as SolidCoffeeBean,
    BiSolidCoffeeTogo as SolidCoffeeTogo,
    BiSolidCog as SolidCog,
    BiSolidCoin as SolidCoin,
    BiSolidCoinStack as SolidCoinStack,
    BiSolidCollection as SolidCollection,
    BiSolidColor as SolidColor,
    BiSolidColorFill as SolidColorFill,
    BiSolidComment as SolidComment,
    BiSolidCommentAdd as SolidCommentAdd,
    BiSolidCommentCheck as SolidCommentCheck,
    BiSolidCommentDetail as SolidCommentDetail,
    BiSolidCommentDots as SolidCommentDots,
    BiSolidCommentEdit as SolidCommentEdit,
    BiSolidCommentError as SolidCommentError,
    BiSolidCommentMinus as SolidCommentMinus,
    BiSolidCommentX as SolidCommentX,
    BiSolidCompass as SolidCompass,
    BiSolidComponent as SolidComponent,
    BiSolidConfused as SolidConfused,
    BiSolidContact as SolidContact,
    BiSolidConversation as SolidConversation,
    BiSolidCookie as SolidCookie,
    BiSolidCool as SolidCool,
    BiSolidCopy as SolidCopy,
    BiSolidCopyAlt as SolidCopyAlt,
    BiSolidCopyright as SolidCopyright,
    BiSolidCoupon as SolidCoupon,
    BiSolidCreditCard as SolidCreditCard,
    BiSolidCreditCardAlt as SolidCreditCardAlt,
    BiSolidCreditCardFront as SolidCreditCardFront,
    BiSolidCricketBall as SolidCricketBall,
    BiSolidCrop as SolidCrop,
    BiSolidCrown as SolidCrown,
    BiSolidCube as SolidCube,
    BiSolidCubeAlt as SolidCubeAlt,
    BiSolidCuboid as SolidCuboid,
    BiSolidCustomize as SolidCustomize,
    BiSolidCylinder as SolidCylinder,
    BiSolidDashboard as SolidDashboard,
    BiSolidData as SolidData,
    BiSolidDetail as SolidDetail,
    BiSolidDevices as SolidDevices,
    BiSolidDiamond as SolidDiamond,
    BiSolidDice1 as SolidDice1,
    BiSolidDice2 as SolidDice2,
    BiSolidDice3 as SolidDice3,
    BiSolidDice4 as SolidDice4,
    BiSolidDice5 as SolidDice5,
    BiSolidDice6 as SolidDice6,
    BiSolidDirectionLeft as SolidDirectionLeft,
    BiSolidDirectionRight as SolidDirectionRight,
    BiSolidDirections as SolidDirections,
    BiSolidDisc as SolidDisc,
    BiSolidDiscount as SolidDiscount,
    BiSolidDish as SolidDish,
    BiSolidDislike as SolidDislike,
    BiSolidDizzy as SolidDizzy,
    BiSolidDockBottom as SolidDockBottom,
    BiSolidDockLeft as SolidDockLeft,
    BiSolidDockRight as SolidDockRight,
    BiSolidDockTop as SolidDockTop,
    BiSolidDog as SolidDog,
    BiSolidDollarCircle as SolidDollarCircle,
    BiSolidDonateBlood as SolidDonateBlood,
    BiSolidDonateHeart as SolidDonateHeart,
    BiSolidDoorOpen as SolidDoorOpen,
    BiSolidDoughnutChart as SolidDoughnutChart,
    BiSolidDownArrow as SolidDownArrow,
    BiSolidDownArrowAlt as SolidDownArrowAlt,
    BiSolidDownArrowCircle as SolidDownArrowCircle,
    BiSolidDownArrowSquare as SolidDownArrowSquare,
    BiSolidDownload as SolidDownload,
    BiSolidDownvote as SolidDownvote,
    BiSolidDrink as SolidDrink,
    BiSolidDroplet as SolidDroplet,
    BiSolidDropletHalf as SolidDropletHalf,
    BiSolidDryer as SolidDryer,
    BiSolidDuplicate as SolidDuplicate,
    BiSolidEdit as SolidEdit,
    BiSolidEditAlt as SolidEditAlt,
    BiSolidEditLocation as SolidEditLocation,
    BiSolidEject as SolidEject,
    BiSolidEnvelope as SolidEnvelope,
    BiSolidEnvelopeOpen as SolidEnvelopeOpen,
    BiSolidEraser as SolidEraser,
    BiSolidError as SolidError,
    BiSolidErrorAlt as SolidErrorAlt,
    BiSolidErrorCircle as SolidErrorCircle,
    BiSolidEvStation as SolidEvStation,
    BiSolidExit as SolidExit,
    BiSolidExtension as SolidExtension,
    BiSolidEyedropper as SolidEyedropper,
    BiSolidFace as SolidFace,
    BiSolidFaceMask as SolidFaceMask,
    BiSolidFactory as SolidFactory,
    BiSolidFastForwardCircle as SolidFastForwardCircle,
    BiSolidFile as SolidFile,
    BiSolidFileArchive as SolidFileArchive,
    BiSolidFileBlank as SolidFileBlank,
    BiSolidFileCss as SolidFileCss,
    BiSolidFileDoc as SolidFileDoc,
    BiSolidFileExport as SolidFileExport,
    BiSolidFileFind as SolidFileFind,
    BiSolidFileGif as SolidFileGif,
    BiSolidFileHtml as SolidFileHtml,
    BiSolidFileImage as SolidFileImage,
    BiSolidFileImport as SolidFileImport,
    BiSolidFileJpg as SolidFileJpg,
    BiSolidFileJs as SolidFileJs,
    BiSolidFileJson as SolidFileJson,
    BiSolidFileMd as SolidFileMd,
    BiSolidFilePdf as SolidFilePdf,
    BiSolidFilePlus as SolidFilePlus,
    BiSolidFilePng as SolidFilePng,
    BiSolidFileTxt as SolidFileTxt,
    BiSolidFilm as SolidFilm,
    BiSolidFilterAlt as SolidFilterAlt,
    BiSolidFirstAid as SolidFirstAid,
    BiSolidFlag as SolidFlag,
    BiSolidFlagAlt as SolidFlagAlt,
    BiSolidFlagCheckered as SolidFlagCheckered,
    BiSolidFlame as SolidFlame,
    BiSolidFlask as SolidFlask,
    BiSolidFlorist as SolidFlorist,
    BiSolidFolder as SolidFolder,
    BiSolidFolderMinus as SolidFolderMinus,
    BiSolidFolderOpen as SolidFolderOpen,
    BiSolidFolderPlus as SolidFolderPlus,
    BiSolidFoodMenu as SolidFoodMenu,
    BiSolidFridge as SolidFridge,
    BiSolidGame as SolidGame,
    BiSolidGasPump as SolidGasPump,
    BiSolidGhost as SolidGhost,
    BiSolidGift as SolidGift,
    BiSolidGraduation as SolidGraduation,
    BiSolidGrid as SolidGrid,
    BiSolidGridAlt as SolidGridAlt,
    BiSolidGroup as SolidGroup,
    BiSolidGuitarAmp as SolidGuitarAmp,
    BiSolidHand as SolidHand,
    BiSolidHandDown as SolidHandDown,
    BiSolidHandLeft as SolidHandLeft,
    BiSolidHandRight as SolidHandRight,
    BiSolidHandUp as SolidHandUp,
    BiSolidHappy as SolidHappy,
    BiSolidHappyAlt as SolidHappyAlt,
    BiSolidHappyBeaming as SolidHappyBeaming,
    BiSolidHappyHeartEyes as SolidHappyHeartEyes,
    BiSolidHardHat as SolidHardHat,
    BiSolidHdd as SolidHdd,
    BiSolidHeart as SolidHeart,
    BiSolidHeartCircle as SolidHeartCircle,
    BiSolidHeartSquare as SolidHeartSquare,
    BiSolidHelpCircle as SolidHelpCircle,
    BiSolidHide as SolidHide,
    BiSolidHome as SolidHome,
    BiSolidHomeAlt2 as SolidHomeAlt2,
    BiSolidHomeCircle as SolidHomeCircle,
    BiSolidHomeHeart as SolidHomeHeart,
    BiSolidHomeSmile as SolidHomeSmile,
    BiSolidHot as SolidHot,
    BiSolidHotel as SolidHotel,
    BiSolidHourglass as SolidHourglass,
    BiSolidHourglassBottom as SolidHourglassBottom,
    BiSolidHourglassTop as SolidHourglassTop,
    BiSolidIdCard as SolidIdCard,
    BiSolidImage as SolidImage,
    BiSolidImageAdd as SolidImageAdd,
    BiSolidImageAlt as SolidImageAlt,
    BiSolidInbox as SolidInbox,
    BiSolidInfoCircle as SolidInfoCircle,
    BiSolidInfoSquare as SolidInfoSquare,
    BiSolidInjection as SolidInjection,
    BiSolidInstitution as SolidInstitution,
    BiSolidInvader as SolidInvader,
    BiSolidJoystick as SolidJoystick,
    BiSolidJoystickAlt as SolidJoystickAlt,
    BiSolidJoystickButton as SolidJoystickButton,
    BiSolidKey as SolidKey,
    BiSolidKeyboard as SolidKeyboard,
    BiSolidLabel as SolidLabel,
    BiSolidLandmark as SolidLandmark,
    BiSolidLandscape as SolidLandscape,
    BiSolidLaugh as SolidLaugh,
    BiSolidLayer as SolidLayer,
    BiSolidLayerMinus as SolidLayerMinus,
    BiSolidLayerPlus as SolidLayerPlus,
    BiSolidLayout as SolidLayout,
    BiSolidLeaf as SolidLeaf,
    BiSolidLeftArrow as SolidLeftArrow,
    BiSolidLeftArrowAlt as SolidLeftArrowAlt,
    BiSolidLeftArrowCircle as SolidLeftArrowCircle,
    BiSolidLeftArrowSquare as SolidLeftArrowSquare,
    BiSolidLeftDownArrowCircle as SolidLeftDownArrowCircle,
    BiSolidLeftTopArrowCircle as SolidLeftTopArrowCircle,
    BiSolidLemon as SolidLemon,
    BiSolidLike as SolidLike,
    BiSolidLocationPlus as SolidLocationPlus,
    BiSolidLock as SolidLock,
    BiSolidLockAlt as SolidLockAlt,
    BiSolidLockOpen as SolidLockOpen,
    BiSolidLockOpenAlt as SolidLockOpenAlt,
    BiSolidLogIn as SolidLogIn,
    BiSolidLogInCircle as SolidLogInCircle,
    BiSolidLogOut as SolidLogOut,
    BiSolidLogOutCircle as SolidLogOutCircle,
    BiSolidLowVision as SolidLowVision,
    BiSolidMagicWand as SolidMagicWand,
    BiSolidMagnet as SolidMagnet,
    BiSolidMap as SolidMap,
    BiSolidMapAlt as SolidMapAlt,
    BiSolidMapPin as SolidMapPin,
    BiSolidMask as SolidMask,
    BiSolidMedal as SolidMedal,
    BiSolidMegaphone as SolidMegaphone,
    BiSolidMeh as SolidMeh,
    BiSolidMehAlt as SolidMehAlt,
    BiSolidMehBlank as SolidMehBlank,
    BiSolidMemoryCard as SolidMemoryCard,
    BiSolidMessage as SolidMessage,
    BiSolidMessageAdd as SolidMessageAdd,
    BiSolidMessageAlt as SolidMessageAlt,
    BiSolidMessageAltAdd as SolidMessageAltAdd,
    BiSolidMessageAltCheck as SolidMessageAltCheck,
    BiSolidMessageAltDetail as SolidMessageAltDetail,
    BiSolidMessageAltDots as SolidMessageAltDots,
    BiSolidMessageAltEdit as SolidMessageAltEdit,
    BiSolidMessageAltError as SolidMessageAltError,
    BiSolidMessageAltMinus as SolidMessageAltMinus,
    BiSolidMessageAltX as SolidMessageAltX,
    BiSolidMessageCheck as SolidMessageCheck,
    BiSolidMessageDetail as SolidMessageDetail,
    BiSolidMessageDots as SolidMessageDots,
    BiSolidMessageEdit as SolidMessageEdit,
    BiSolidMessageError as SolidMessageError,
    BiSolidMessageMinus as SolidMessageMinus,
    BiSolidMessageRounded as SolidMessageRounded,
    BiSolidMessageRoundedAdd as SolidMessageRoundedAdd,
    BiSolidMessageRoundedCheck as SolidMessageRoundedCheck,
    BiSolidMessageRoundedDetail as SolidMessageRoundedDetail,
    BiSolidMessageRoundedDots as SolidMessageRoundedDots,
    BiSolidMessageRoundedEdit as SolidMessageRoundedEdit,
    BiSolidMessageRoundedError as SolidMessageRoundedError,
    BiSolidMessageRoundedMinus as SolidMessageRoundedMinus,
    BiSolidMessageRoundedX as SolidMessageRoundedX,
    BiSolidMessageSquare as SolidMessageSquare,
    BiSolidMessageSquareAdd as SolidMessageSquareAdd,
    BiSolidMessageSquareCheck as SolidMessageSquareCheck,
    BiSolidMessageSquareDetail as SolidMessageSquareDetail,
    BiSolidMessageSquareDots as SolidMessageSquareDots,
    BiSolidMessageSquareEdit as SolidMessageSquareEdit,
    BiSolidMessageSquareError as SolidMessageSquareError,
    BiSolidMessageSquareMinus as SolidMessageSquareMinus,
    BiSolidMessageSquareX as SolidMessageSquareX,
    BiSolidMessageX as SolidMessageX,
    BiSolidMeteor as SolidMeteor,
    BiSolidMicrochip as SolidMicrochip,
    BiSolidMicrophone as SolidMicrophone,
    BiSolidMicrophoneAlt as SolidMicrophoneAlt,
    BiSolidMicrophoneOff as SolidMicrophoneOff,
    BiSolidMinusCircle as SolidMinusCircle,
    BiSolidMinusSquare as SolidMinusSquare,
    BiSolidMobile as SolidMobile,
    BiSolidMobileVibration as SolidMobileVibration,
    BiSolidMoon as SolidMoon,
    BiSolidMouse as SolidMouse,
    BiSolidMouseAlt as SolidMouseAlt,
    BiSolidMovie as SolidMovie,
    BiSolidMoviePlay as SolidMoviePlay,
    BiSolidMusic as SolidMusic,
    BiSolidNavigation as SolidNavigation,
    BiSolidNetworkChart as SolidNetworkChart,
    BiSolidNews as SolidNews,
    BiSolidNoEntry as SolidNoEntry,
    BiSolidNote as SolidNote,
    BiSolidNotepad as SolidNotepad,
    BiSolidNotification as SolidNotification,
    BiSolidNotificationOff as SolidNotificationOff,
    BiSolidObjectsHorizontalCenter as SolidObjectsHorizontalCenter,
    BiSolidObjectsHorizontalLeft as SolidObjectsHorizontalLeft,
    BiSolidObjectsHorizontalRight as SolidObjectsHorizontalRight,
    BiSolidObjectsVerticalBottom as SolidObjectsVerticalBottom,
    BiSolidObjectsVerticalCenter as SolidObjectsVerticalCenter,
    BiSolidObjectsVerticalTop as SolidObjectsVerticalTop,
    BiSolidOffer as SolidOffer,
    BiSolidPackage as SolidPackage,
    BiSolidPaint as SolidPaint,
    BiSolidPaintRoll as SolidPaintRoll,
    BiSolidPalette as SolidPalette,
    BiSolidPaperPlane as SolidPaperPlane,
    BiSolidParking as SolidParking,
    BiSolidParty as SolidParty,
    BiSolidPaste as SolidPaste,
    BiSolidPear as SolidPear,
    BiSolidPen as SolidPen,
    BiSolidPencil as SolidPencil,
    BiSolidPhone as SolidPhone,
    BiSolidPhoneCall as SolidPhoneCall,
    BiSolidPhoneIncoming as SolidPhoneIncoming,
    BiSolidPhoneOff as SolidPhoneOff,
    BiSolidPhoneOutgoing as SolidPhoneOutgoing,
    BiSolidPhotoAlbum as SolidPhotoAlbum,
    BiSolidPiano as SolidPiano,
    BiSolidPieChart as SolidPieChart,
    BiSolidPieChartAlt as SolidPieChartAlt,
    BiSolidPieChartAlt2 as SolidPieChartAlt2,
    BiSolidPin as SolidPin,
    BiSolidPizza as SolidPizza,
    BiSolidPlane as SolidPlane,
    BiSolidPlaneAlt as SolidPlaneAlt,
    BiSolidPlaneLand as SolidPlaneLand,
    BiSolidPlaneTakeOff as SolidPlaneTakeOff,
    BiSolidPlanet as SolidPlanet,
    BiSolidPlaylist as SolidPlaylist,
    BiSolidPlug as SolidPlug,
    BiSolidPlusCircle as SolidPlusCircle,
    BiSolidPlusSquare as SolidPlusSquare,
    BiSolidPointer as SolidPointer,
    BiSolidPolygon as SolidPolygon,
    BiSolidPopsicle as SolidPopsicle,
    BiSolidPrinter as SolidPrinter,
    BiSolidPurchaseTag as SolidPurchaseTag,
    BiSolidPurchaseTagAlt as SolidPurchaseTagAlt,
    BiSolidPyramid as SolidPyramid,
    BiSolidQuoteAltLeft as SolidQuoteAltLeft,
    BiSolidQuoteAltRight as SolidQuoteAltRight,
    BiSolidQuoteLeft as SolidQuoteLeft,
    BiSolidQuoteRight as SolidQuoteRight,
    BiSolidQuoteSingleLeft as SolidQuoteSingleLeft,
    BiSolidQuoteSingleRight as SolidQuoteSingleRight,
    BiSolidRadiation as SolidRadiation,
    BiSolidRadio as SolidRadio,
    BiSolidReceipt as SolidReceipt,
    BiSolidRectangle as SolidRectangle,
    BiSolidRegistered as SolidRegistered,
    BiSolidRename as SolidRename,
    BiSolidReport as SolidReport,
    BiSolidRewindCircle as SolidRewindCircle,
    BiSolidRightArrow as SolidRightArrow,
    BiSolidRightArrowAlt as SolidRightArrowAlt,
    BiSolidRightArrowCircle as SolidRightArrowCircle,
    BiSolidRightArrowSquare as SolidRightArrowSquare,
    BiSolidRightDownArrowCircle as SolidRightDownArrowCircle,
    BiSolidRightTopArrowCircle as SolidRightTopArrowCircle,
    BiSolidRocket as SolidRocket,
    BiSolidRuler as SolidRuler,
    BiSolidSad as SolidSad,
    BiSolidSave as SolidSave,
    BiSolidSchool as SolidSchool,
    BiSolidSearch as SolidSearch,
    BiSolidSearchAlt2 as SolidSearchAlt2,
    BiSolidSelectMultiple as SolidSelectMultiple,
    BiSolidSend as SolidSend,
    BiSolidServer as SolidServer,
    BiSolidShapes as SolidShapes,
    BiSolidShare as SolidShare,
    BiSolidShareAlt as SolidShareAlt,
    BiSolidShield as SolidShield,
    BiSolidShieldAlt2 as SolidShieldAlt2,
    BiSolidShieldMinus as SolidShieldMinus,
    BiSolidShieldPlus as SolidShieldPlus,
    BiSolidShieldX as SolidShieldX,
    BiSolidShip as SolidShip,
    BiSolidShocked as SolidShocked,
    BiSolidShoppingBag as SolidShoppingBag,
    BiSolidShoppingBagAlt as SolidShoppingBagAlt,
    BiSolidShoppingBags as SolidShoppingBags,
    BiSolidShow as SolidShow,
    BiSolidShower as SolidShower,
    BiSolidSkipNextCircle as SolidSkipNextCircle,
    BiSolidSkipPreviousCircle as SolidSkipPreviousCircle,
    BiSolidSkull as SolidSkull,
    BiSolidSleepy as SolidSleepy,
    BiSolidSlideshow as SolidSlideshow,
    BiSolidSmile as SolidSmile,
    BiSolidSortAlt as SolidSortAlt,
    BiSolidSpa as SolidSpa,
    BiSolidSpeaker as SolidSpeaker,
    BiSolidSprayCan as SolidSprayCan,
    BiSolidSpreadsheet as SolidSpreadsheet,
    BiSolidSquare as SolidSquare,
    BiSolidSquareRounded as SolidSquareRounded,
    BiSolidStar as SolidStar,
    BiSolidStarHalf as SolidStarHalf,
    BiSolidSticker as SolidSticker,
    BiSolidStopwatch as SolidStopwatch,
    BiSolidStore as SolidStore,
    BiSolidStoreAlt as SolidStoreAlt,
    BiSolidSun as SolidSun,
    BiSolidSushi as SolidSushi,
    BiSolidTachometer as SolidTachometer,
    BiSolidTag as SolidTag,
    BiSolidTagAlt as SolidTagAlt,
    BiSolidTagX as SolidTagX,
    BiSolidTaxi as SolidTaxi,
    BiSolidTennisBall as SolidTennisBall,
    BiSolidTerminal as SolidTerminal,
    BiSolidThermometer as SolidThermometer,
    BiSolidTime as SolidTime,
    BiSolidTimeFive as SolidTimeFive,
    BiSolidTimer as SolidTimer,
    BiSolidTired as SolidTired,
    BiSolidToggleLeft as SolidToggleLeft,
    BiSolidToggleRight as SolidToggleRight,
    BiSolidTone as SolidTone,
    BiSolidTorch as SolidTorch,
    BiSolidToTop as SolidToTop,
    BiSolidTraffic as SolidTraffic,
    BiSolidTrafficBarrier as SolidTrafficBarrier,
    BiSolidTrafficCone as SolidTrafficCone,
    BiSolidTrain as SolidTrain,
    BiSolidTrash as SolidTrash,
    BiSolidTrashAlt as SolidTrashAlt,
    BiSolidTree as SolidTree,
    BiSolidTreeAlt as SolidTreeAlt,
    BiSolidTrophy as SolidTrophy,
    BiSolidTruck as SolidTruck,
    BiSolidTShirt as SolidTShirt,
    BiSolidTv as SolidTv,
    BiSolidUniversalAccess as SolidUniversalAccess,
    BiSolidUpArrow as SolidUpArrow,
    BiSolidUpArrowAlt as SolidUpArrowAlt,
    BiSolidUpArrowCircle as SolidUpArrowCircle,
    BiSolidUpArrowSquare as SolidUpArrowSquare,
    BiSolidUpsideDown as SolidUpsideDown,
    BiSolidUpvote as SolidUpvote,
    BiSolidUser as SolidUser,
    BiSolidUserAccount as SolidUserAccount,
    BiSolidUserBadge as SolidUserBadge,
    BiSolidUserCheck as SolidUserCheck,
    BiSolidUserCircle as SolidUserCircle,
    BiSolidUserDetail as SolidUserDetail,
    BiSolidUserMinus as SolidUserMinus,
    BiSolidUserPin as SolidUserPin,
    BiSolidUserPlus as SolidUserPlus,
    BiSolidUserRectangle as SolidUserRectangle,
    BiSolidUserVoice as SolidUserVoice,
    BiSolidUserX as SolidUserX,
    BiSolidVector as SolidVector,
    BiSolidVial as SolidVial,
    BiSolidVideo as SolidVideo,
    BiSolidVideoOff as SolidVideoOff,
    BiSolidVideoPlus as SolidVideoPlus,
    BiSolidVideoRecording as SolidVideoRecording,
    BiSolidVideos as SolidVideos,
    BiSolidVirus as SolidVirus,
    BiSolidVirusBlock as SolidVirusBlock,
    BiSolidVolume as SolidVolume,
    BiSolidVolumeFull as SolidVolumeFull,
    BiSolidVolumeLow as SolidVolumeLow,
    BiSolidVolumeMute as SolidVolumeMute,
    BiSolidWallet as SolidWallet,
    BiSolidWalletAlt as SolidWalletAlt,
    BiSolidWasher as SolidWasher,
    BiSolidWatch as SolidWatch,
    BiSolidWatchAlt as SolidWatchAlt,
    BiSolidWebcam as SolidWebcam,
    BiSolidWidget as SolidWidget,
    BiSolidWindowAlt as SolidWindowAlt,
    BiSolidWine as SolidWine,
    BiSolidWinkSmile as SolidWinkSmile,
    BiSolidWinkTongue as SolidWinkTongue,
    BiSolidWrench as SolidWrench,
    BiSolidXCircle as SolidXCircle,
    BiSolidXSquare as SolidXSquare,
    BiSolidYinYang as SolidYinYang,
    BiSolidZap as SolidZap,
    BiSolidZoomIn as SolidZoomIn,
    BiSolidZoomOut as SolidZoomOut,
    BiSortAlt2 as SortAlt2,
    BiSortAZ as SortAZ,
    BiSortZA as SortZA,
    BiSpreadsheet as Spreadsheet,
    BiSquareRounded as SquareRounded,
    BiStation as Station,
    BiStats as Stats,
    BiSticker as Sticker,
    BiSubdirectoryLeft as SubdirectoryLeft,
    BiSubdirectoryRight as SubdirectoryRight,
    BiSushi as Sushi,
    BiSwim as Swim,
    BiTachometer as Tachometer,
    BiTagAlt as TagAlt,
    BiTargetLock as TargetLock,
    BiTaskX as TaskX,
    BiTennisBall as TennisBall,
    BiTestTube as TestTube,
    BiText as Text,
    BiTime as Time,
    BiTimeFive as TimeFive,
    BiToggleLeft as ToggleLeft,
    BiToggleRight as ToggleRight,
    BiTone as Tone,
    BiTrafficCone as TrafficCone,
    BiTransfer as Transfer,
    BiTransferAlt as TransferAlt,
    BiTrim as Trim,
    BiTrip as Trip,
    BiUnite as Unite,
    BiUpArrow as UpArrow,
    BiUpArrowAlt as UpArrowAlt,
    BiUpArrowCircle as UpArrowCircle,
    BiUpsideDown as UpsideDown,
    BiUpvote as Upvote,
    BiUserPin as UserPin,
    BiUserVoice as UserVoice,
    BiUserX as UserX,
    BiVector as Vector,
    BiVerticalBottom as VerticalBottom,
    BiVerticalCenter as VerticalCenter,
    BiVerticalTop as VerticalTop,
    BiVideoOff as VideoOff,
    BiVideoPlus as VideoPlus,
    BiVideoRecording as VideoRecording,
    BiVolume as Volume,
    BiVolumeFull as VolumeFull,
    BiVolumeLow as VolumeLow,
    BiWalk as Walk,
    BiWalletAlt as WalletAlt,
    BiWebcam as Webcam,
    BiWifi0 as Wifi0,
    BiWifi1 as Wifi1,
    BiWindowAlt as WindowAlt,
    BiWindowOpen as WindowOpen,
    BiWine as Wine,
    BiWinkSmile as WinkSmile,
    BiWinkTongue as WinkTongue,
    BiWon as Won,
    BiWorld as World,
    BiX as X,
    BiXCircle as XCircle,
    BiYen as Yen,
} from 'react-icons/bi';

export {
    Abacus,
    AlarmExclamation,
    AlarmSnooze,
    AlignMiddle,
    Analyse,
    Aperture,
    Arch,
    ArchiveIn,
    ArchiveOut,
    Area,
    ArrowFromBottom,
    ArrowFromLeft,
    ArrowFromRight,
    ArrowFromTop,
    ArrowToBottom,
    ArrowToLeft,
    ArrowToRight,
    ArrowToTop,
    BadgeCheck,
    Baguette,
    Ball,
    BarChartAlt,
    BarChartAlt2,
    BarChartSquare,
    BarcodeReader,
    Baseball,
    Basket,
    Basketball,
    Battery,
    BeenHere,
    BellMinus,
    BellOff,
    BellPlus,
    Blanket,
    Body,
    BoltCircle,
    BookAdd,
    BookAlt,
    BookBookmark,
    BookContent,
    BookHeart,
    BookmarkAlt,
    BookmarkAltMinus,
    BookmarkAltPlus,
    BookmarkHeart,
    BookmarkMinus,
    BookmarkPlus,
    BorderRadius,
    Bot,
    BowlHot,
    BowlRice,
    Bracket,
    BriefcaseAlt,
    BriefcaseAlt2,
    Brightness,
    BrightnessHalf,
    Broadcast,
    BrushAlt,
    BugAlt,
    BuildingHouse,
    Buildings,
    Bulb,
    Buoy,
    BusSchool,
    Cabinet,
    CableCar,
    CalendarEdit,
    CalendarEvent,
    CalendarExclamation,
    CalendarHeart,
    CalendarStar,
    CalendarX,
    CameraHome,
    CameraMovie,
    CameraOff,
    Candles,
    Capsule,
    Captions,
    Card,
    CaretDownCircle,
    CaretDownSquare,
    CaretLeftCircle,
    CaretLeftSquare,
    CaretRightCircle,
    CaretRightSquare,
    CaretUpCircle,
    CaretUpSquare,
    Carousel,
    Cart,
    CartAdd,
    CartAlt,
    CartDownload,
    CategoryAlt,
    Cctv,
    Certification,
    Chart,
    CheckShield,
    Checkbox,
    CheckboxChecked,
    CheckboxMinus,
    CheckboxSquare,
    ChevronDownCircle,
    ChevronDownSquare,
    ChevronLeftCircle,
    ChevronLeftSquare,
    ChevronRightCircle,
    ChevronRightSquare,
    ChevronUpCircle,
    ChevronUpSquare,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    Chip,
    CircleHalf,
    CircleQuarter,
    CircleThreeQuarter,
    Clinic,
    Closet,
    CloudDrizzle,
    CloudLightRain,
    CloudLightning,
    CloudSnow,
    CodeAlt,
    CodeBlock,
    CodeCurly,
    CoffeeTogo,
    Coin,
    CoinStack,
    Collapse,
    CollapseAlt,
    CollapseHorizontal,
    CollapseVertical,
    Collection,
    Color,
    ColorFill,
    Command,
    CommentAdd,
    CommentCheck,
    CommentDetail,
    CommentEdit,
    CommentError,
    CommentMinus,
    CommentX,
    Confused,
    Conversation,
    Cool,
    CopyAlt,
    CreditCardAlt,
    CreditCardFront,
    CricketBall,
    Crosshair,
    CubeAlt,
    Cuboid,
    CurrentLocation,
    Customize,
    Cycling,
    Cylinder,
    Data,
    Detail,
    DialpadAlt,
    Dice1,
    Dice2,
    Dice3,
    Dice4,
    Dice5,
    Dice6,
    Disc,
    Dish,
    Dislike,
    DockBottom,
    DockLeft,
    DockRight,
    DockTop,
    Dollar,
    DollarCircle,
    DonateBlood,
    DonateHeart,
    DotsHorizontal,
    DotsHorizontalRounded,
    DotsVertical,
    DotsVerticalRounded,
    DoughnutChart,
    DownArrow,
    DownArrowAlt,
    DownArrowCircle,
    Downvote,
    Drink,
    Droplet,
    Duplicate,
    EditAlt,
    ErrorAlt,
    ErrorCircle,
    Exclude,
    Exit,
    ExitFullscreen,
    ExpandHorizontal,
    ExpandVertical,
    Export,
    FastForwardCircle,
    FemaleSign,
    FileBlank,
    FileFind,
    FontColor,
    FontFamily,
    FontSize,
    FoodMenu,
    FoodTag,
    Football,
    Fork,
    Fridge,
    Game,
    GitBranch,
    GitCommit,
    GitCompare,
    GitMerge,
    GitPullRequest,
    GitRepoForked,
    GlassesAlt,
    GlobeAlt,
    Grid,
    GridAlt,
    GridHorizontal,
    GridSmall,
    GridVertical,
    Handicap,
    Happy,
    HappyAlt,
    HappyBeaming,
    HappyHeartEyes,
    Hash,
    Headphone,
    Health,
    HeartCircle,
    HeartSquare,
    HelpCircle,
    Hide,
    HomeAlt,
    HomeAlt2,
    HomeCircle,
    HomeHeart,
    HomeSmile,
    HorizontalCenter,
    HorizontalLeft,
    HorizontalRight,
    ImageAdd,
    ImageAlt,
    Import,
    Infinite,
    InfoSquare,
    Injection,
    Intersect,
    Joystick,
    JoystickAlt,
    JoystickButton,
    Knife,
    Layer,
    LayerMinus,
    LayerPlus,
    Layout,
    LeftArrow,
    LeftArrowAlt,
    LeftArrowCircle,
    LeftDownArrowCircle,
    LeftIndent,
    LeftTopArrowCircle,
    Library,
    Like,
    LineChart,
    LineChartDown,
    LinkAlt,
    LinkExternal,
    Lira,
    ListCheck,
    ListMinus,
    ListPlus,
    Loader,
    LoaderAlt,
    LoaderCircle,
    LocationPlus,
    LockAlt,
    LockOpenAlt,
    LogIn,
    LogInCircle,
    LogOut,
    LogOutCircle,
    Logo500Px,
    Logo99Designs,
    LogoAdobe,
    LogoAirbnb,
    LogoAlgolia,
    LogoAmazon,
    LogoAndroid,
    LogoAngular,
    LogoApple,
    LogoAudible,
    LogoAws,
    LogoBaidu,
    LogoBehance,
    LogoBing,
    LogoBitcoin,
    LogoBlender,
    LogoBlogger,
    LogoBootstrap,
    LogoCPlusPlus,
    LogoChrome,
    LogoCodepen,
    LogoCreativeCommons,
    LogoCss3,
    LogoDailymotion,
    LogoDeezer,
    LogoDevTo,
    LogoDeviantart,
    LogoDigg,
    LogoDigitalocean,
    LogoDiscord,
    LogoDiscordAlt,
    LogoDiscourse,
    LogoDjango,
    LogoDocker,
    LogoDribbble,
    LogoDropbox,
    LogoDrupal,
    LogoEbay,
    LogoEdge,
    LogoEtsy,
    LogoFacebook,
    LogoFacebookCircle,
    LogoFacebookSquare,
    LogoFigma,
    LogoFirebase,
    LogoFirefox,
    LogoFlask,
    LogoFlickr,
    LogoFlickrSquare,
    LogoFlutter,
    LogoFoursquare,
    LogoGit,
    LogoGithub,
    LogoGitlab,
    LogoGmail,
    LogoGoLang,
    LogoGoogle,
    LogoGoogleCloud,
    LogoGooglePlus,
    LogoGooglePlusCircle,
    LogoGraphql,
    LogoHeroku,
    LogoHtml5,
    LogoImdb,
    LogoInstagram,
    LogoInstagramAlt,
    LogoInternetExplorer,
    LogoInvision,
    LogoJava,
    LogoJavascript,
    LogoJoomla,
    LogoJquery,
    LogoJsfiddle,
    LogoKickstarter,
    LogoKubernetes,
    LogoLess,
    LogoLinkedin,
    LogoLinkedinSquare,
    LogoMagento,
    LogoMailchimp,
    LogoMarkdown,
    LogoMastercard,
    LogoMastodon,
    LogoMedium,
    LogoMediumOld,
    LogoMediumSquare,
    LogoMessenger,
    LogoMeta,
    LogoMicrosoft,
    LogoMicrosoftTeams,
    LogoMongodb,
    LogoNetlify,
    LogoNodejs,
    LogoOkRu,
    LogoOpera,
    LogoPatreon,
    LogoPaypal,
    LogoPeriscope,
    LogoPhp,
    LogoPinterest,
    LogoPinterestAlt,
    LogoPlayStore,
    LogoPocket,
    LogoPostgresql,
    LogoProductHunt,
    LogoPython,
    LogoQuora,
    LogoReact,
    LogoRedbubble,
    LogoReddit,
    LogoRedux,
    LogoSass,
    LogoShopify,
    LogoSketch,
    LogoSkype,
    LogoSlack,
    LogoSlackOld,
    LogoSnapchat,
    LogoSoundcloud,
    LogoSpotify,
    LogoSpringBoot,
    LogoSquarespace,
    LogoStackOverflow,
    LogoSteam,
    LogoStripe,
    LogoTailwindCss,
    LogoTelegram,
    LogoTiktok,
    LogoTrello,
    LogoTripAdvisor,
    LogoTumblr,
    LogoTux,
    LogoTwitch,
    LogoTwitter,
    LogoTypescript,
    LogoUnity,
    LogoUnsplash,
    LogoUpwork,
    LogoVenmo,
    LogoVimeo,
    LogoVisa,
    LogoVisualStudio,
    LogoVk,
    LogoVuejs,
    LogoWhatsapp,
    LogoWhatsappSquare,
    LogoWikipedia,
    LogoWindows,
    LogoWix,
    LogoWordpress,
    LogoXing,
    LogoYahoo,
    LogoYelp,
    LogoYoutube,
    LogoZoom,
    MailSend,
    MaleFemale,
    MaleSign,
    MapAlt,
    Math,
    MehAlt,
    MemoryCard,
    MenuAltLeft,
    MenuAltRight,
    MessageAdd,
    MessageAlt,
    MessageAltAdd,
    MessageAltCheck,
    MessageAltDetail,
    MessageAltDots,
    MessageAltEdit,
    MessageAltError,
    MessageAltMinus,
    MessageAltX,
    MessageCheck,
    MessageDetail,
    MessageDots,
    MessageEdit,
    MessageError,
    MessageMinus,
    MessageRounded,
    MessageRoundedAdd,
    MessageRoundedCheck,
    MessageRoundedDetail,
    MessageRoundedDots,
    MessageRoundedEdit,
    MessageRoundedError,
    MessageRoundedMinus,
    MessageRoundedX,
    MessageSquare,
    MessageSquareAdd,
    MessageSquareCheck,
    MessageSquareDetail,
    MessageSquareDots,
    MessageSquareEdit,
    MessageSquareError,
    MessageSquareMinus,
    MessageSquareX,
    MessageX,
    MicrophoneOff,
    MinusBack,
    MinusFront,
    MobileLandscape,
    MobileVibration,
    MoneyWithdraw,
    MouseAlt,
    Move,
    MoveHorizontal,
    MoveVertical,
    MoviePlay,
    NetworkChart,
    News,
    NoEntry,
    NoSignal,
    Notepad,
    Notification,
    NotificationOff,
    ObjectsHorizontalCenter,
    ObjectsHorizontalLeft,
    ObjectsHorizontalRight,
    ObjectsVerticalBottom,
    ObjectsVerticalCenter,
    ObjectsVerticalTop,
    Outline,
    Package,
    Paint,
    PaintRoll,
    Party,
    Pencil,
    PhoneCall,
    PhoneIncoming,
    PhoneOff,
    PhoneOutgoing,
    PieChartAlt,
    PieChartAlt2,
    Planet,
    PlusMedical,
    Pointer,
    Polygon,
    Popsicle,
    Pound,
    Printer,
    Pulse,
    PurchaseTag,
    PurchaseTagAlt,
    Pyramid,
    Qr,
    QrScan,
    RadioCircle,
    RadioCircleMarked,
    ReflectHorizontal,
    ReflectVertical,
    Rename,
    Repost,
    Reset,
    Revision,
    Rewind,
    RewindCircle,
    Rfid,
    RightArrow,
    RightArrowAlt,
    RightArrowCircle,
    RightDownArrowCircle,
    RightIndent,
    RightTopArrowCircle,
    Ruble,
    Run,
    Rupee,
    Sad,
    Scan,
    ScatterChart,
    SearchAlt,
    SearchAlt2,
    SelectMultiple,
    Selection,
    ShapeCircle,
    ShapePolygon,
    ShapeSquare,
    ShapeTriangle,
    Shekel,
    ShieldAlt2,
    ShieldMinus,
    ShieldPlus,
    ShieldQuarter,
    ShieldX,
    Shocked,
    Show,
    ShowAlt,
    Sidebar,
    Signal1,
    Signal2,
    Signal3,
    Signal4,
    Signal5,
    SkipNextCircle,
    SkipPreviousCircle,
    Sleepy,
    Slider,
    SliderAlt,
    SolidAddToQueue,
    SolidAdjust,
    SolidAdjustAlt,
    SolidAlarm,
    SolidAlarmAdd,
    SolidAlarmExclamation,
    SolidAlarmOff,
    SolidAlarmSnooze,
    SolidAlbum,
    SolidAmbulance,
    SolidAnalyse,
    SolidAngry,
    SolidArch,
    SolidArchive,
    SolidArchiveIn,
    SolidArchiveOut,
    SolidArea,
    SolidArrowFromBottom,
    SolidArrowFromLeft,
    SolidArrowFromRight,
    SolidArrowFromTop,
    SolidArrowToBottom,
    SolidArrowToLeft,
    SolidArrowToRight,
    SolidArrowToTop,
    SolidAward,
    SolidBabyCarriage,
    SolidBackpack,
    SolidBadge,
    SolidBadgeCheck,
    SolidBadgeDollar,
    SolidBaguette,
    SolidBall,
    SolidBalloon,
    SolidBandAid,
    SolidBank,
    SolidBarChartAlt2,
    SolidBarChartSquare,
    SolidBarcode,
    SolidBaseball,
    SolidBasket,
    SolidBasketball,
    SolidBath,
    SolidBattery,
    SolidBatteryCharging,
    SolidBatteryFull,
    SolidBatteryLow,
    SolidBed,
    SolidBeenHere,
    SolidBeer,
    SolidBell,
    SolidBellMinus,
    SolidBellOff,
    SolidBellPlus,
    SolidBellRing,
    SolidBible,
    SolidBinoculars,
    SolidBlanket,
    SolidBolt,
    SolidBoltCircle,
    SolidBomb,
    SolidBone,
    SolidBong,
    SolidBook,
    SolidBookAdd,
    SolidBookAlt,
    SolidBookBookmark,
    SolidBookContent,
    SolidBookHeart,
    SolidBookOpen,
    SolidBookReader,
    SolidBookmark,
    SolidBookmarkAlt,
    SolidBookmarkAltMinus,
    SolidBookmarkAltPlus,
    SolidBookmarkHeart,
    SolidBookmarkMinus,
    SolidBookmarkPlus,
    SolidBookmarkStar,
    SolidBookmarks,
    SolidBot,
    SolidBowlHot,
    SolidBowlRice,
    SolidBowlingBall,
    SolidBox,
    SolidBrain,
    SolidBriefcase,
    SolidBriefcaseAlt,
    SolidBriefcaseAlt2,
    SolidBrightness,
    SolidBrightnessHalf,
    SolidBrush,
    SolidBrushAlt,
    SolidBug,
    SolidBugAlt,
    SolidBuilding,
    SolidBuildingHouse,
    SolidBuildings,
    SolidBulb,
    SolidBullseye,
    SolidBuoy,
    SolidBus,
    SolidBusSchool,
    SolidBusiness,
    SolidCabinet,
    SolidCableCar,
    SolidCake,
    SolidCalculator,
    SolidCalendar,
    SolidCalendarAlt,
    SolidCalendarCheck,
    SolidCalendarEdit,
    SolidCalendarEvent,
    SolidCalendarExclamation,
    SolidCalendarHeart,
    SolidCalendarMinus,
    SolidCalendarPlus,
    SolidCalendarStar,
    SolidCalendarWeek,
    SolidCalendarX,
    SolidCamera,
    SolidCameraHome,
    SolidCameraMovie,
    SolidCameraOff,
    SolidCameraPlus,
    SolidCapsule,
    SolidCaptions,
    SolidCar,
    SolidCarBattery,
    SolidCarCrash,
    SolidCarGarage,
    SolidCarMechanic,
    SolidCarWash,
    SolidCard,
    SolidCaretDownCircle,
    SolidCaretDownSquare,
    SolidCaretLeftCircle,
    SolidCaretLeftSquare,
    SolidCaretRightCircle,
    SolidCaretRightSquare,
    SolidCaretUpCircle,
    SolidCaretUpSquare,
    SolidCarousel,
    SolidCart,
    SolidCartAdd,
    SolidCartAlt,
    SolidCartDownload,
    SolidCastle,
    SolidCat,
    SolidCategory,
    SolidCategoryAlt,
    SolidCctv,
    SolidCertification,
    SolidChalkboard,
    SolidChart,
    SolidChat,
    SolidCheckCircle,
    SolidCheckShield,
    SolidCheckSquare,
    SolidCheckbox,
    SolidCheckboxChecked,
    SolidCheckboxMinus,
    SolidCheese,
    SolidChess,
    SolidChevronDown,
    SolidChevronDownCircle,
    SolidChevronDownSquare,
    SolidChevronLeft,
    SolidChevronLeftCircle,
    SolidChevronLeftSquare,
    SolidChevronRight,
    SolidChevronRightCircle,
    SolidChevronRightSquare,
    SolidChevronUp,
    SolidChevronUpCircle,
    SolidChevronUpSquare,
    SolidChevronsDown,
    SolidChevronsLeft,
    SolidChevronsRight,
    SolidChevronsUp,
    SolidChip,
    SolidChurch,
    SolidCircle,
    SolidCircleHalf,
    SolidCircleQuarter,
    SolidCircleThreeQuarter,
    SolidCity,
    SolidClinic,
    SolidCloud,
    SolidCloudDownload,
    SolidCloudLightning,
    SolidCloudRain,
    SolidCloudUpload,
    SolidCoffee,
    SolidCoffeeAlt,
    SolidCoffeeBean,
    SolidCoffeeTogo,
    SolidCog,
    SolidCoin,
    SolidCoinStack,
    SolidCollection,
    SolidColor,
    SolidColorFill,
    SolidComment,
    SolidCommentAdd,
    SolidCommentCheck,
    SolidCommentDetail,
    SolidCommentDots,
    SolidCommentEdit,
    SolidCommentError,
    SolidCommentMinus,
    SolidCommentX,
    SolidCompass,
    SolidComponent,
    SolidConfused,
    SolidContact,
    SolidConversation,
    SolidCookie,
    SolidCool,
    SolidCopy,
    SolidCopyAlt,
    SolidCopyright,
    SolidCoupon,
    SolidCreditCard,
    SolidCreditCardAlt,
    SolidCreditCardFront,
    SolidCricketBall,
    SolidCrop,
    SolidCrown,
    SolidCube,
    SolidCubeAlt,
    SolidCuboid,
    SolidCustomize,
    SolidCylinder,
    SolidDashboard,
    SolidData,
    SolidDetail,
    SolidDevices,
    SolidDiamond,
    SolidDice1,
    SolidDice2,
    SolidDice3,
    SolidDice4,
    SolidDice5,
    SolidDice6,
    SolidDirectionLeft,
    SolidDirectionRight,
    SolidDirections,
    SolidDisc,
    SolidDiscount,
    SolidDish,
    SolidDislike,
    SolidDizzy,
    SolidDockBottom,
    SolidDockLeft,
    SolidDockRight,
    SolidDockTop,
    SolidDog,
    SolidDollarCircle,
    SolidDonateBlood,
    SolidDonateHeart,
    SolidDoorOpen,
    SolidDoughnutChart,
    SolidDownArrow,
    SolidDownArrowAlt,
    SolidDownArrowCircle,
    SolidDownArrowSquare,
    SolidDownload,
    SolidDownvote,
    SolidDrink,
    SolidDroplet,
    SolidDropletHalf,
    SolidDryer,
    SolidDuplicate,
    SolidEdit,
    SolidEditAlt,
    SolidEditLocation,
    SolidEject,
    SolidEnvelope,
    SolidEnvelopeOpen,
    SolidEraser,
    SolidError,
    SolidErrorAlt,
    SolidErrorCircle,
    SolidEvStation,
    SolidExit,
    SolidExtension,
    SolidEyedropper,
    SolidFace,
    SolidFaceMask,
    SolidFactory,
    SolidFastForwardCircle,
    SolidFile,
    SolidFileArchive,
    SolidFileBlank,
    SolidFileCss,
    SolidFileDoc,
    SolidFileExport,
    SolidFileFind,
    SolidFileGif,
    SolidFileHtml,
    SolidFileImage,
    SolidFileImport,
    SolidFileJpg,
    SolidFileJs,
    SolidFileJson,
    SolidFileMd,
    SolidFilePdf,
    SolidFilePlus,
    SolidFilePng,
    SolidFileTxt,
    SolidFilm,
    SolidFilterAlt,
    SolidFirstAid,
    SolidFlag,
    SolidFlagAlt,
    SolidFlagCheckered,
    SolidFlame,
    SolidFlask,
    SolidFlorist,
    SolidFolder,
    SolidFolderMinus,
    SolidFolderOpen,
    SolidFolderPlus,
    SolidFoodMenu,
    SolidFridge,
    SolidGame,
    SolidGasPump,
    SolidGhost,
    SolidGift,
    SolidGraduation,
    SolidGrid,
    SolidGridAlt,
    SolidGroup,
    SolidGuitarAmp,
    SolidHand,
    SolidHandDown,
    SolidHandLeft,
    SolidHandRight,
    SolidHandUp,
    SolidHappy,
    SolidHappyAlt,
    SolidHappyBeaming,
    SolidHappyHeartEyes,
    SolidHardHat,
    SolidHdd,
    SolidHeart,
    SolidHeartCircle,
    SolidHeartSquare,
    SolidHelpCircle,
    SolidHide,
    SolidHome,
    SolidHomeAlt2,
    SolidHomeCircle,
    SolidHomeHeart,
    SolidHomeSmile,
    SolidHot,
    SolidHotel,
    SolidHourglass,
    SolidHourglassBottom,
    SolidHourglassTop,
    SolidIdCard,
    SolidImage,
    SolidImageAdd,
    SolidImageAlt,
    SolidInbox,
    SolidInfoCircle,
    SolidInfoSquare,
    SolidInjection,
    SolidInstitution,
    SolidInvader,
    SolidJoystick,
    SolidJoystickAlt,
    SolidJoystickButton,
    SolidKey,
    SolidKeyboard,
    SolidLabel,
    SolidLandmark,
    SolidLandscape,
    SolidLaugh,
    SolidLayer,
    SolidLayerMinus,
    SolidLayerPlus,
    SolidLayout,
    SolidLeaf,
    SolidLeftArrow,
    SolidLeftArrowAlt,
    SolidLeftArrowCircle,
    SolidLeftArrowSquare,
    SolidLeftDownArrowCircle,
    SolidLeftTopArrowCircle,
    SolidLemon,
    SolidLike,
    SolidLocationPlus,
    SolidLock,
    SolidLockAlt,
    SolidLockOpen,
    SolidLockOpenAlt,
    SolidLogIn,
    SolidLogInCircle,
    SolidLogOut,
    SolidLogOutCircle,
    SolidLowVision,
    SolidMagicWand,
    SolidMagnet,
    SolidMap,
    SolidMapAlt,
    SolidMapPin,
    SolidMask,
    SolidMedal,
    SolidMegaphone,
    SolidMeh,
    SolidMehAlt,
    SolidMehBlank,
    SolidMemoryCard,
    SolidMessage,
    SolidMessageAdd,
    SolidMessageAlt,
    SolidMessageAltAdd,
    SolidMessageAltCheck,
    SolidMessageAltDetail,
    SolidMessageAltDots,
    SolidMessageAltEdit,
    SolidMessageAltError,
    SolidMessageAltMinus,
    SolidMessageAltX,
    SolidMessageCheck,
    SolidMessageDetail,
    SolidMessageDots,
    SolidMessageEdit,
    SolidMessageError,
    SolidMessageMinus,
    SolidMessageRounded,
    SolidMessageRoundedAdd,
    SolidMessageRoundedCheck,
    SolidMessageRoundedDetail,
    SolidMessageRoundedDots,
    SolidMessageRoundedEdit,
    SolidMessageRoundedError,
    SolidMessageRoundedMinus,
    SolidMessageRoundedX,
    SolidMessageSquare,
    SolidMessageSquareAdd,
    SolidMessageSquareCheck,
    SolidMessageSquareDetail,
    SolidMessageSquareDots,
    SolidMessageSquareEdit,
    SolidMessageSquareError,
    SolidMessageSquareMinus,
    SolidMessageSquareX,
    SolidMessageX,
    SolidMeteor,
    SolidMicrochip,
    SolidMicrophone,
    SolidMicrophoneAlt,
    SolidMicrophoneOff,
    SolidMinusCircle,
    SolidMinusSquare,
    SolidMobile,
    SolidMobileVibration,
    SolidMoon,
    SolidMouse,
    SolidMouseAlt,
    SolidMovie,
    SolidMoviePlay,
    SolidMusic,
    SolidNavigation,
    SolidNetworkChart,
    SolidNews,
    SolidNoEntry,
    SolidNote,
    SolidNotepad,
    SolidNotification,
    SolidNotificationOff,
    SolidObjectsHorizontalCenter,
    SolidObjectsHorizontalLeft,
    SolidObjectsHorizontalRight,
    SolidObjectsVerticalBottom,
    SolidObjectsVerticalCenter,
    SolidObjectsVerticalTop,
    SolidOffer,
    SolidPackage,
    SolidPaint,
    SolidPaintRoll,
    SolidPalette,
    SolidPaperPlane,
    SolidParking,
    SolidParty,
    SolidPaste,
    SolidPear,
    SolidPen,
    SolidPencil,
    SolidPhone,
    SolidPhoneCall,
    SolidPhoneIncoming,
    SolidPhoneOff,
    SolidPhoneOutgoing,
    SolidPhotoAlbum,
    SolidPiano,
    SolidPieChart,
    SolidPieChartAlt,
    SolidPieChartAlt2,
    SolidPin,
    SolidPizza,
    SolidPlane,
    SolidPlaneAlt,
    SolidPlaneLand,
    SolidPlaneTakeOff,
    SolidPlanet,
    SolidPlaylist,
    SolidPlug,
    SolidPlusCircle,
    SolidPlusSquare,
    SolidPointer,
    SolidPolygon,
    SolidPopsicle,
    SolidPrinter,
    SolidPurchaseTag,
    SolidPurchaseTagAlt,
    SolidPyramid,
    SolidQuoteAltLeft,
    SolidQuoteAltRight,
    SolidQuoteLeft,
    SolidQuoteRight,
    SolidQuoteSingleLeft,
    SolidQuoteSingleRight,
    SolidRadiation,
    SolidRadio,
    SolidReceipt,
    SolidRectangle,
    SolidRegistered,
    SolidRename,
    SolidReport,
    SolidRewindCircle,
    SolidRightArrow,
    SolidRightArrowAlt,
    SolidRightArrowCircle,
    SolidRightArrowSquare,
    SolidRightDownArrowCircle,
    SolidRightTopArrowCircle,
    SolidRocket,
    SolidRuler,
    SolidSad,
    SolidSave,
    SolidSchool,
    SolidSearch,
    SolidSearchAlt2,
    SolidSelectMultiple,
    SolidSend,
    SolidServer,
    SolidShapes,
    SolidShare,
    SolidShareAlt,
    SolidShield,
    SolidShieldAlt2,
    SolidShieldMinus,
    SolidShieldPlus,
    SolidShieldX,
    SolidShip,
    SolidShocked,
    SolidShoppingBag,
    SolidShoppingBagAlt,
    SolidShoppingBags,
    SolidShow,
    SolidShower,
    SolidSkipNextCircle,
    SolidSkipPreviousCircle,
    SolidSkull,
    SolidSleepy,
    SolidSlideshow,
    SolidSmile,
    SolidSortAlt,
    SolidSpa,
    SolidSpeaker,
    SolidSprayCan,
    SolidSpreadsheet,
    SolidSquare,
    SolidSquareRounded,
    SolidStar,
    SolidStarHalf,
    SolidSticker,
    SolidStopwatch,
    SolidStore,
    SolidStoreAlt,
    SolidSun,
    SolidSushi,
    SolidTShirt,
    SolidTachometer,
    SolidTag,
    SolidTagAlt,
    SolidTagX,
    SolidTaxi,
    SolidTennisBall,
    SolidTerminal,
    SolidThermometer,
    SolidTime,
    SolidTimeFive,
    SolidTimer,
    SolidTired,
    SolidToTop,
    SolidToggleLeft,
    SolidToggleRight,
    SolidTone,
    SolidTorch,
    SolidTraffic,
    SolidTrafficBarrier,
    SolidTrafficCone,
    SolidTrain,
    SolidTrash,
    SolidTrashAlt,
    SolidTree,
    SolidTreeAlt,
    SolidTrophy,
    SolidTruck,
    SolidTv,
    SolidUniversalAccess,
    SolidUpArrow,
    SolidUpArrowAlt,
    SolidUpArrowCircle,
    SolidUpArrowSquare,
    SolidUpsideDown,
    SolidUpvote,
    SolidUser,
    SolidUserAccount,
    SolidUserBadge,
    SolidUserCheck,
    SolidUserCircle,
    SolidUserDetail,
    SolidUserMinus,
    SolidUserPin,
    SolidUserPlus,
    SolidUserRectangle,
    SolidUserVoice,
    SolidUserX,
    SolidVector,
    SolidVial,
    SolidVideo,
    SolidVideoOff,
    SolidVideoPlus,
    SolidVideoRecording,
    SolidVideos,
    SolidVirus,
    SolidVirusBlock,
    SolidVolume,
    SolidVolumeFull,
    SolidVolumeLow,
    SolidVolumeMute,
    SolidWallet,
    SolidWalletAlt,
    SolidWasher,
    SolidWatch,
    SolidWatchAlt,
    SolidWebcam,
    SolidWidget,
    SolidWindowAlt,
    SolidWine,
    SolidWinkSmile,
    SolidWinkTongue,
    SolidWrench,
    SolidXCircle,
    SolidXSquare,
    SolidYinYang,
    SolidZap,
    SolidZoomIn,
    SolidZoomOut,
    SortAZ,
    SortAlt2,
    SortZA,
    Spreadsheet,
    SquareRounded,
    Station,
    Stats,
    Sticker,
    SubdirectoryLeft,
    SubdirectoryRight,
    Sushi,
    Swim,
    Tachometer,
    TagAlt,
    TargetLock,
    TaskX,
    TennisBall,
    TestTube,
    Text,
    Time,
    TimeFive,
    ToggleLeft,
    ToggleRight,
    Tone,
    TrafficCone,
    Transfer,
    TransferAlt,
    Trim,
    Trip,
    Unite,
    UpArrow,
    UpArrowAlt,
    UpArrowCircle,
    UpsideDown,
    Upvote,
    UserPin,
    UserVoice,
    UserX,
    Vector,
    VerticalBottom,
    VerticalCenter,
    VerticalTop,
    VideoOff,
    VideoPlus,
    VideoRecording,
    Volume,
    VolumeFull,
    VolumeLow,
    Walk,
    WalletAlt,
    Webcam,
    Wifi0,
    Wifi1,
    WindowAlt,
    WindowOpen,
    Wine,
    WinkSmile,
    WinkTongue,
    Won,
    World,
    X,
    XCircle,
    Yen,
};

// import * as muiIcons from '../../utils/icons/materialUI';
// import * as faIcons from '../../utils/icons/fontAwesome';
// import * as biIcons from 'react-icons/bi';
// const biIconsNames: string[] = [];
// console.log(
//     `import { ${Object.entries(biIcons)
//         .map((i) => {
//             let alias = i[0].substring(2); // remove first 2 characters

//             // If alias starts with a number, prepend it with an underscore
//             if (/^[0-9]/.test(alias)) {
//                 alias = '_' + alias;
//             }
//             if (!Object.keys(muiIcons).includes(alias) && !Object.keys(faIcons).includes(alias)) {
//                 biIconsNames.push(alias);
//                 return `${i[0]} as ${alias}`;
//             } else {
//                 return ''; // return empty string when if condition is not met
//             }
//         })
//         .filter((item) => item) // filter out the empty strings
//         .join(', ')} } from 'react-icons/ai';`,
// );

// console.log(`export { ${biIconsNames.join(', ')} } `);
