// Icons 4
import {
    Fa0 as _0,
    Fa1 as _1,
    Fa2 as _2,
    Fa3 as _3,
    Fa4 as _4,
    Fa5 as _5,
    Fa6 as _6,
    Fa7 as _7,
    Fa8 as _8,
    Fa9 as _9,
    Fa42Group as _42Group,
    FaA as A,
    FaAnchorCircleCheck as AnchorCircleCheck,
    FaAnchorCircleExclamation as AnchorCircleExclamation,
    FaAnchorCircleXmark as AnchorCircleXmark,
    FaAnchorLock as AnchorLock,
    FaAnglesDown as AnglesDown,
    FaAnglesLeft as AnglesLeft,
    FaAnglesRight as AnglesRight,
    FaAnglesUp as AnglesUp,
    FaAppleWhole as AppleWhole,
    FaArrowDown19 as ArrowDown19,
    FaArrowDown91 as ArrowDown91,
    FaArrowDownAZ as ArrowDownAZ,
    FaArrowDownLong as ArrowDownLong,
    FaArrowDownShortWide as ArrowDownShortWide,
    FaArrowDownUpAcrossLine as ArrowDownUpAcrossLine,
    FaArrowDownUpLock as ArrowDownUpLock,
    FaArrowDownWideShort as ArrowDownWideShort,
    FaArrowDownZA as ArrowDownZA,
    FaArrowLeftLong as ArrowLeftLong,
    FaArrowPointer as ArrowPointer,
    FaArrowRightArrowLeft as ArrowRightArrowLeft,
    FaArrowRightFromBracket as ArrowRightFromBracket,
    FaArrowRightLong as ArrowRightLong,
    FaArrowRightToBracket as ArrowRightToBracket,
    FaArrowRightToCity as ArrowRightToCity,
    FaArrowRotateLeft as ArrowRotateLeft,
    FaArrowRotateRight as ArrowRotateRight,
    FaArrowsDownToLine as ArrowsDownToLine,
    FaArrowsDownToPeople as ArrowsDownToPeople,
    FaArrowsLeftRight as ArrowsLeftRight,
    FaArrowsLeftRightToLine as ArrowsLeftRightToLine,
    FaArrowsRotate as ArrowsRotate,
    FaArrowsSpin as ArrowsSpin,
    FaArrowsSplitUpAndLeft as ArrowsSplitUpAndLeft,
    FaArrowsToCircle as ArrowsToCircle,
    FaArrowsToDot as ArrowsToDot,
    FaArrowsToEye as ArrowsToEye,
    FaArrowsTurnRight as ArrowsTurnRight,
    FaArrowsTurnToDots as ArrowsTurnToDots,
    FaArrowsUpDown as ArrowsUpDown,
    FaArrowsUpDownLeftRight as ArrowsUpDownLeftRight,
    FaArrowsUpToLine as ArrowsUpToLine,
    FaArrowTrendDown as ArrowTrendDown,
    FaArrowTrendUp as ArrowTrendUp,
    FaArrowTurnDown as ArrowTurnDown,
    FaArrowTurnUp as ArrowTurnUp,
    FaArrowUp19 as ArrowUp19,
    FaArrowUp91 as ArrowUp91,
    FaArrowUpAZ as ArrowUpAZ,
    FaArrowUpFromBracket as ArrowUpFromBracket,
    FaArrowUpFromGroundWater as ArrowUpFromGroundWater,
    FaArrowUpFromWaterPump as ArrowUpFromWaterPump,
    FaArrowUpLong as ArrowUpLong,
    FaArrowUpRightDots as ArrowUpRightDots,
    FaArrowUpRightFromSquare as ArrowUpRightFromSquare,
    FaArrowUpShortWide as ArrowUpShortWide,
    FaArrowUpWideShort as ArrowUpWideShort,
    FaArrowUpZA as ArrowUpZA,
    FaAustralSign as AustralSign,
    FaB as B,
    FaBackwardFast as BackwardFast,
    FaBackwardStep as BackwardStep,
    FaBagShopping as BagShopping,
    FaBahtSign as BahtSign,
    FaBandage as Bandage,
    FaBangladeshiTakaSign as BangladeshiTakaSign,
    FaBanSmoking as BanSmoking,
    FaBarsProgress as BarsProgress,
    FaBarsStaggered as BarsStaggered,
    FaBaseballBatBall as BaseballBatBall,
    FaBasketShopping as BasketShopping,
    FaBedPulse as BedPulse,
    FaBeerMugEmpty as BeerMugEmpty,
    FaBellConcierge as BellConcierge,
    FaBilibili as Bilibili,
    FaBitcoinSign as BitcoinSign,
    FaBoltLightning as BoltLightning,
    FaBookAtlas as BookAtlas,
    FaBookBible as BookBible,
    FaBookJournalWhills as BookJournalWhills,
    FaBookOpenReader as BookOpenReader,
    FaBookQuran as BookQuran,
    FaBookSkull as BookSkull,
    FaBookTanakh as BookTanakh,
    FaBorderTopLeft as BorderTopLeft,
    FaBoreHole as BoreHole,
    FaBots as Bots,
    FaBottleDroplet as BottleDroplet,
    FaBottleWater as BottleWater,
    FaBowlFood as BowlFood,
    FaBoxArchive as BoxArchive,
    FaBoxesPacking as BoxesPacking,
    FaBoxesStacked as BoxesStacked,
    FaBrazilianRealSign as BrazilianRealSign,
    FaBridge as Bridge,
    FaBridgeCircleCheck as BridgeCircleCheck,
    FaBridgeCircleExclamation as BridgeCircleExclamation,
    FaBridgeCircleXmark as BridgeCircleXmark,
    FaBridgeLock as BridgeLock,
    FaBridgeWater as BridgeWater,
    FaBroomBall as BroomBall,
    FaBucket as Bucket,
    FaBugSlash as BugSlash,
    FaBugs as Bugs,
    FaBuildingCircleArrowRight as BuildingCircleArrowRight,
    FaBuildingCircleCheck as BuildingCircleCheck,
    FaBuildingCircleExclamation as BuildingCircleExclamation,
    FaBuildingCircleXmark as BuildingCircleXmark,
    FaBuildingColumns as BuildingColumns,
    FaBuildingFlag as BuildingFlag,
    FaBuildingLock as BuildingLock,
    FaBuildingNgo as BuildingNgo,
    FaBuildingShield as BuildingShield,
    FaBuildingUn as BuildingUn,
    FaBuildingUser as BuildingUser,
    FaBuildingWheat as BuildingWheat,
    FaBurger as Burger,
    FaBurst as Burst,
    FaBusSimple as BusSimple,
    FaC as C,
    FaCakeCandles as CakeCandles,
    FaCalendarDays as CalendarDays,
    FaCalendarXmark as CalendarXmark,
    FaCameraRotate as CameraRotate,
    FaCarBurst as CarBurst,
    FaCarOn as CarOn,
    FaCarRear as CarRear,
    FaCarTunnel as CarTunnel,
    FaCartFlatbed as CartFlatbed,
    FaCartFlatbedSuitcase as CartFlatbedSuitcase,
    FaCartShopping as CartShopping,
    FaCediSign as CediSign,
    FaCentSign as CentSign,
    FaChalkboardUser as ChalkboardUser,
    FaChampagneGlasses as ChampagneGlasses,
    FaChartColumn as ChartColumn,
    FaChartGantt as ChartGantt,
    FaChartSimple as ChartSimple,
    FaCheckToSlot as CheckToSlot,
    FaChildCombatant as ChildCombatant,
    FaChildDress as ChildDress,
    FaChildReaching as ChildReaching,
    FaChildren as Children,
    FaCircleArrowDown as CircleArrowDown,
    FaCircleArrowLeft as CircleArrowLeft,
    FaCircleArrowRight as CircleArrowRight,
    FaCircleArrowUp as CircleArrowUp,
    FaCircleCheck as CircleCheck,
    FaCircleChevronDown as CircleChevronDown,
    FaCircleChevronLeft as CircleChevronLeft,
    FaCircleChevronRight as CircleChevronRight,
    FaCircleChevronUp as CircleChevronUp,
    FaCircleDollarToSlot as CircleDollarToSlot,
    FaCircleDot as CircleDot,
    FaCircleDown as CircleDown,
    FaCircleExclamation as CircleExclamation,
    FaCircleH as CircleH,
    FaCircleHalfStroke as CircleHalfStroke,
    FaCircleInfo as CircleInfo,
    FaCircleLeft as CircleLeft,
    FaCircleMinus as CircleMinus,
    FaCircleNodes as CircleNodes,
    FaCirclePause as CirclePause,
    FaCirclePlay as CirclePlay,
    FaCirclePlus as CirclePlus,
    FaCircleQuestion as CircleQuestion,
    FaCircleRadiation as CircleRadiation,
    FaCircleRight as CircleRight,
    FaCircleStop as CircleStop,
    FaCircleUp as CircleUp,
    FaCircleUser as CircleUser,
    FaCircleXmark as CircleXmark,
    FaClapperboard as Clapperboard,
    FaClipboardQuestion as ClipboardQuestion,
    FaClipboardUser as ClipboardUser,
    FaClockRotateLeft as ClockRotateLeft,
    FaCloudArrowDown as CloudArrowDown,
    FaCloudArrowUp as CloudArrowUp,
    FaCloudBolt as CloudBolt,
    FaCloudShowersWater as CloudShowersWater,
    FaClover as Clover,
    FaCmplid as Cmplid,
    FaCodeCommit as CodeCommit,
    FaCodeCompare as CodeCompare,
    FaCodeFork as CodeFork,
    FaCodeMerge as CodeMerge,
    FaCodePullRequest as CodePullRequest,
    FaColonSign as ColonSign,
    FaCommentSms as CommentSms,
    FaCompassDrafting as CompassDrafting,
    FaComputerMouse as ComputerMouse,
    FaCow as Cow,
    FaCropSimple as CropSimple,
    FaCruzeiroSign as CruzeiroSign,
    FaCubesStacked as CubesStacked,
    FaD as D,
    FaDeleteLeft as DeleteLeft,
    FaDiagramNext as DiagramNext,
    FaDiagramPredecessor as DiagramPredecessor,
    FaDiagramProject as DiagramProject,
    FaDiagramSuccessor as DiagramSuccessor,
    FaDiamondTurnRight as DiamondTurnRight,
    FaDisplay as Display,
    FaDongSign as DongSign,
    FaDownLeftAndUpRightToCenter as DownLeftAndUpRightToCenter,
    FaDownLong as DownLong,
    FaDropletSlash as DropletSlash,
    FaE as E,
    FaEarDeaf as EarDeaf,
    FaEarListen as EarListen,
    FaEarthAfrica as EarthAfrica,
    FaEarthAmericas as EarthAmericas,
    FaEarthAsia as EarthAsia,
    FaEarthEurope as EarthEurope,
    FaEarthOceania as EarthOceania,
    FaEllipsis as Ellipsis,
    FaEllipsisVertical as EllipsisVertical,
    FaEnvelopeCircleCheck as EnvelopeCircleCheck,
    FaEnvelopesBulk as EnvelopesBulk,
    FaExplosion as Explosion,
    FaEyeLowVision as EyeLowVision,
    FaF as F,
    FaFaceAngry as FaceAngry,
    FaFaceDizzy as FaceDizzy,
    FaFaceFlushed as FaceFlushed,
    FaFaceFrown as FaceFrown,
    FaFaceFrownOpen as FaceFrownOpen,
    FaFaceGrimace as FaceGrimace,
    FaFaceGrin as FaceGrin,
    FaFaceGrinBeam as FaceGrinBeam,
    FaFaceGrinBeamSweat as FaceGrinBeamSweat,
    FaFaceGrinHearts as FaceGrinHearts,
    FaFaceGrinSquint as FaceGrinSquint,
    FaFaceGrinSquintTears as FaceGrinSquintTears,
    FaFaceGrinStars as FaceGrinStars,
    FaFaceGrinTears as FaceGrinTears,
    FaFaceGrinTongue as FaceGrinTongue,
    FaFaceGrinTongueSquint as FaceGrinTongueSquint,
    FaFaceGrinTongueWink as FaceGrinTongueWink,
    FaFaceGrinWide as FaceGrinWide,
    FaFaceGrinWink as FaceGrinWink,
    FaFaceKiss as FaceKiss,
    FaFaceKissBeam as FaceKissBeam,
    FaFaceKissWinkHeart as FaceKissWinkHeart,
    FaFaceLaugh as FaceLaugh,
    FaFaceLaughBeam as FaceLaughBeam,
    FaFaceLaughSquint as FaceLaughSquint,
    FaFaceLaughWink as FaceLaughWink,
    FaFaceMeh as FaceMeh,
    FaFaceMehBlank as FaceMehBlank,
    FaFaceRollingEyes as FaceRollingEyes,
    FaFaceSadCry as FaceSadCry,
    FaFaceSadTear as FaceSadTear,
    FaFaceSmile as FaceSmile,
    FaFaceSmileBeam as FaceSmileBeam,
    FaFaceSmileWink as FaceSmileWink,
    FaFaceSurprise as FaceSurprise,
    FaFaceTired as FaceTired,
    FaFaucetDrip as FaucetDrip,
    FaFeatherPointed as FeatherPointed,
    FaFerry as Ferry,
    FaFileArrowDown as FileArrowDown,
    FaFileArrowUp as FileArrowUp,
    FaFileCircleCheck as FileCircleCheck,
    FaFileCircleExclamation as FileCircleExclamation,
    FaFileCircleMinus as FileCircleMinus,
    FaFileCirclePlus as FileCirclePlus,
    FaFileCircleQuestion as FileCircleQuestion,
    FaFileCircleXmark as FileCircleXmark,
    FaFileLines as FileLines,
    FaFilePen as FilePen,
    FaFileShield as FileShield,
    FaFileWaveform as FileWaveform,
    FaFileZipper as FileZipper,
    FaFilterCircleDollar as FilterCircleDollar,
    FaFilterCircleXmark as FilterCircleXmark,
    FaFireBurner as FireBurner,
    FaFireFlameCurved as FireFlameCurved,
    FaFireFlameSimple as FireFlameSimple,
    FaFishFins as FishFins,
    FaFlaskVial as FlaskVial,
    FaFloppyDisk as FloppyDisk,
    FaFlorinSign as FlorinSign,
    FaFolderClosed as FolderClosed,
    FaFolderTree as FolderTree,
    FaForwardFast as ForwardFast,
    FaForwardStep as ForwardStep,
    FaFrancSign as FrancSign,
    FaG as G,
    FaGauge as Gauge,
    FaGaugeHigh as GaugeHigh,
    FaGaugeSimple as GaugeSimple,
    FaGaugeSimpleHigh as GaugeSimpleHigh,
    FaGear as Gear,
    FaGears as Gears,
    FaGlassWater as GlassWater,
    FaGlassWaterDroplet as GlassWaterDroplet,
    FaGolang as Golang,
    FaGolfBallTee as GolfBallTee,
    FaGrip as Grip,
    FaGroupArrowsRotate as GroupArrowsRotate,
    FaGuaraniSign as GuaraniSign,
    FaGun as Gun,
    FaH as H,
    FaHand as Hand,
    FaHandBackFist as HandBackFist,
    FaHandcuffs as Handcuffs,
    FaHandDots as HandDots,
    FaHandFist as HandFist,
    FaHandHoldingDollar as HandHoldingDollar,
    FaHandHoldingDroplet as HandHoldingDroplet,
    FaHandHoldingHand as HandHoldingHand,
    FaHandsAslInterpreting as HandsAslInterpreting,
    FaHandsBound as HandsBound,
    FaHandsBubbles as HandsBubbles,
    FaHandsClapping as HandsClapping,
    FaHandsHolding as HandsHolding,
    FaHandsHoldingChild as HandsHoldingChild,
    FaHandsHoldingCircle as HandsHoldingCircle,
    FaHandshakeAngle as HandshakeAngle,
    FaHandshakeSimple as HandshakeSimple,
    FaHandshakeSimpleSlash as HandshakeSimpleSlash,
    FaHandsPraying as HandsPraying,
    FaHardDrive as HardDrive,
    FaHashnode as Hashnode,
    FaHeadphonesSimple as HeadphonesSimple,
    FaHeartCircleBolt as HeartCircleBolt,
    FaHeartCircleCheck as HeartCircleCheck,
    FaHeartCircleExclamation as HeartCircleExclamation,
    FaHeartCircleMinus as HeartCircleMinus,
    FaHeartCirclePlus as HeartCirclePlus,
    FaHeartCircleXmark as HeartCircleXmark,
    FaHeartCrack as HeartCrack,
    FaHeartPulse as HeartPulse,
    FaHelicopterSymbol as HelicopterSymbol,
    FaHelmetSafety as HelmetSafety,
    FaHelmetUn as HelmetUn,
    FaHillAvalanche as HillAvalanche,
    FaHillRockslide as HillRockslide,
    FaHotTubPerson as HotTubPerson,
    FaHouseChimney as HouseChimney,
    FaHouseChimneyCrack as HouseChimneyCrack,
    FaHouseChimneyMedical as HouseChimneyMedical,
    FaHouseChimneyUser as HouseChimneyUser,
    FaHouseChimneyWindow as HouseChimneyWindow,
    FaHouseCircleCheck as HouseCircleCheck,
    FaHouseCircleExclamation as HouseCircleExclamation,
    FaHouseCircleXmark as HouseCircleXmark,
    FaHouseCrack as HouseCrack,
    FaHouseFire as HouseFire,
    FaHouseFlag as HouseFlag,
    FaHouseFloodWater as HouseFloodWater,
    FaHouseFloodWaterCircleArrowRight as HouseFloodWaterCircleArrowRight,
    FaHouseLaptop as HouseLaptop,
    FaHouseLock as HouseLock,
    FaHouseMedical as HouseMedical,
    FaHouseMedicalCircleCheck as HouseMedicalCircleCheck,
    FaHouseMedicalCircleExclamation as HouseMedicalCircleExclamation,
    FaHouseMedicalCircleXmark as HouseMedicalCircleXmark,
    FaHouseMedicalFlag as HouseMedicalFlag,
    FaHouseSignal as HouseSignal,
    FaHouseTsunami as HouseTsunami,
    FaHryvniaSign as HryvniaSign,
    FaHurricane as Hurricane,
    FaI as I,
    FaIdCardClip as IdCardClip,
    FaImagePortrait as ImagePortrait,
    FaIndianRupeeSign as IndianRupeeSign,
    FaJ as J,
    FaJar as Jar,
    FaJarWheat as JarWheat,
    FaJetFighter as JetFighter,
    FaJetFighterUp as JetFighterUp,
    FaJugDetergent as JugDetergent,
    FaK as K,
    FaKipSign as KipSign,
    FaKitchenSet as KitchenSet,
    FaKitMedical as KitMedical,
    FaL as L,
    FaLandMineOn as LandMineOn,
    FaLandmarkDome as LandmarkDome,
    FaLandmarkFlag as LandmarkFlag,
    FaLaptopFile as LaptopFile,
    FaLariSign as LariSign,
    FaLeftLong as LeftLong,
    FaLeftRight as LeftRight,
    FaLinesLeaning as LinesLeaning,
    FaLinkSlash as LinkSlash,
    FaLitecoinSign as LitecoinSign,
    FaLocationCrosshairs as LocationCrosshairs,
    FaLocationDot as LocationDot,
    FaLocationPin as LocationPin,
    FaLocationPinLock as LocationPinLock,
    FaLocust as Locust,
    FaM as M,
    FaMagnifyingGlass as MagnifyingGlass,
    FaMagnifyingGlassArrowRight as MagnifyingGlassArrowRight,
    FaMagnifyingGlassChart as MagnifyingGlassChart,
    FaMagnifyingGlassDollar as MagnifyingGlassDollar,
    FaMagnifyingGlassLocation as MagnifyingGlassLocation,
    FaMagnifyingGlassMinus as MagnifyingGlassMinus,
    FaMagnifyingGlassPlus as MagnifyingGlassPlus,
    FaManatSign as ManatSign,
    FaMapLocation as MapLocation,
    FaMapLocationDot as MapLocationDot,
    FaMarsAndVenus as MarsAndVenus,
    FaMarsAndVenusBurst as MarsAndVenusBurst,
    FaMarsStrokeRight as MarsStrokeRight,
    FaMarsStrokeUp as MarsStrokeUp,
    FaMartiniGlass as MartiniGlass,
    FaMartiniGlassCitrus as MartiniGlassCitrus,
    FaMartiniGlassEmpty as MartiniGlassEmpty,
    FaMaskFace as MaskFace,
    FaMasksTheater as MasksTheater,
    FaMaskVentilator as MaskVentilator,
    FaMattressPillow as MattressPillow,
    FaMeta as Meta,
    FaMicrophoneLines as MicrophoneLines,
    FaMicrophoneLinesSlash as MicrophoneLinesSlash,
    FaMillSign as MillSign,
    FaMobileButton as MobileButton,
    FaMobileRetro as MobileRetro,
    FaMobileScreen as MobileScreen,
    FaMobileScreenButton as MobileScreenButton,
    FaMoneyBill1 as MoneyBill1,
    FaMoneyBill1Wave as MoneyBill1Wave,
    FaMoneyBills as MoneyBills,
    FaMoneyBillTransfer as MoneyBillTransfer,
    FaMoneyBillTrendUp as MoneyBillTrendUp,
    FaMoneyBillWheat as MoneyBillWheat,
    FaMoneyCheckDollar as MoneyCheckDollar,
    FaMosquito as Mosquito,
    FaMosquitoNet as MosquitoNet,
    FaMound as Mound,
    FaMountainCity as MountainCity,
    FaMountainSun as MountainSun,
    FaMugSaucer as MugSaucer,
    FaN as N,
    FaNairaSign as NairaSign,
    FaNfcDirectional as NfcDirectional,
    FaNfcSymbol as NfcSymbol,
    FaNotdef as Notdef,
    FaNoteSticky as NoteSticky,
    FaO as O,
    FaOdysee as Odysee,
    FaOilWell as OilWell,
    FaP as P,
    FaPadlet as Padlet,
    FaPaintbrush as Paintbrush,
    FaPenClip as PenClip,
    FaPenRuler as PenRuler,
    FaPenToSquare as PenToSquare,
    FaPeopleCarryBox as PeopleCarryBox,
    FaPeopleGroup as PeopleGroup,
    FaPeopleLine as PeopleLine,
    FaPeoplePulling as PeoplePulling,
    FaPeopleRobbery as PeopleRobbery,
    FaPeopleRoof as PeopleRoof,
    FaPersonArrowDownToLine as PersonArrowDownToLine,
    FaPersonArrowUpFromLine as PersonArrowUpFromLine,
    FaPersonBiking as PersonBiking,
    FaPersonBreastfeeding as PersonBreastfeeding,
    FaPersonBurst as PersonBurst,
    FaPersonCane as PersonCane,
    FaPersonChalkboard as PersonChalkboard,
    FaPersonCircleCheck as PersonCircleCheck,
    FaPersonCircleExclamation as PersonCircleExclamation,
    FaPersonCircleMinus as PersonCircleMinus,
    FaPersonCirclePlus as PersonCirclePlus,
    FaPersonCircleQuestion as PersonCircleQuestion,
    FaPersonCircleXmark as PersonCircleXmark,
    FaPersonDigging as PersonDigging,
    FaPersonDotsFromLine as PersonDotsFromLine,
    FaPersonDress as PersonDress,
    FaPersonDressBurst as PersonDressBurst,
    FaPersonDrowning as PersonDrowning,
    FaPersonFalling as PersonFalling,
    FaPersonFallingBurst as PersonFallingBurst,
    FaPersonHalfDress as PersonHalfDress,
    FaPersonHarassing as PersonHarassing,
    FaPersonHiking as PersonHiking,
    FaPersonMilitaryPointing as PersonMilitaryPointing,
    FaPersonMilitaryRifle as PersonMilitaryRifle,
    FaPersonMilitaryToPerson as PersonMilitaryToPerson,
    FaPersonPraying as PersonPraying,
    FaPersonPregnant as PersonPregnant,
    FaPersonRays as PersonRays,
    FaPersonRifle as PersonRifle,
    FaPersonRunning as PersonRunning,
    FaPersonShelter as PersonShelter,
    FaPersonSkating as PersonSkating,
    FaPersonSkiing as PersonSkiing,
    FaPersonSkiingNordic as PersonSkiingNordic,
    FaPersonSnowboarding as PersonSnowboarding,
    FaPersonSwimming as PersonSwimming,
    FaPersonThroughWindow as PersonThroughWindow,
    FaPersonWalking as PersonWalking,
    FaPersonWalkingArrowLoopLeft as PersonWalkingArrowLoopLeft,
    FaPersonWalkingArrowRight as PersonWalkingArrowRight,
    FaPersonWalkingDashedLineArrowRight as PersonWalkingDashedLineArrowRight,
    FaPersonWalkingLuggage as PersonWalkingLuggage,
    FaPersonWalkingWithCane as PersonWalkingWithCane,
    FaPesetaSign as PesetaSign,
    FaPesoSign as PesoSign,
    FaPhoneFlip as PhoneFlip,
    FaPhotoFilm as PhotoFilm,
    FaPlaneCircleCheck as PlaneCircleCheck,
    FaPlaneCircleExclamation as PlaneCircleExclamation,
    FaPlaneCircleXmark as PlaneCircleXmark,
    FaPlaneLock as PlaneLock,
    FaPlaneUp as PlaneUp,
    FaPlantWilt as PlantWilt,
    FaPlateWheat as PlateWheat,
    FaPlugCircleBolt as PlugCircleBolt,
    FaPlugCircleCheck as PlugCircleCheck,
    FaPlugCircleExclamation as PlugCircleExclamation,
    FaPlugCircleMinus as PlugCircleMinus,
    FaPlugCirclePlus as PlugCirclePlus,
    FaPlugCircleXmark as PlugCircleXmark,
    FaPlusMinus as PlusMinus,
    FaPrescriptionBottleMedical as PrescriptionBottleMedical,
    FaQ as Q,
    FaR as R,
    FaRankingStar as RankingStar,
    FaRectangleAd as RectangleAd,
    FaRectangleList as RectangleList,
    FaRectangleXmark as RectangleXmark,
    FaRegCalendarDays as RegCalendarDays,
    FaRegCalendarXmark as RegCalendarXmark,
    FaRegChessBishop as RegChessBishop,
    FaRegChessKing as RegChessKing,
    FaRegChessKnight as RegChessKnight,
    FaRegChessPawn as RegChessPawn,
    FaRegChessQueen as RegChessQueen,
    FaRegChessRook as RegChessRook,
    FaRegCircleCheck as RegCircleCheck,
    FaRegCircleDot as RegCircleDot,
    FaRegCircleDown as RegCircleDown,
    FaRegCircleLeft as RegCircleLeft,
    FaRegCirclePause as RegCirclePause,
    FaRegCirclePlay as RegCirclePlay,
    FaRegCircleQuestion as RegCircleQuestion,
    FaRegCircleRight as RegCircleRight,
    FaRegCircleStop as RegCircleStop,
    FaRegCircleUp as RegCircleUp,
    FaRegCircleUser as RegCircleUser,
    FaRegCircleXmark as RegCircleXmark,
    FaRegFaceAngry as RegFaceAngry,
    FaRegFaceDizzy as RegFaceDizzy,
    FaRegFaceFlushed as RegFaceFlushed,
    FaRegFaceFrown as RegFaceFrown,
    FaRegFaceFrownOpen as RegFaceFrownOpen,
    FaRegFaceGrimace as RegFaceGrimace,
    FaRegFaceGrin as RegFaceGrin,
    FaRegFaceGrinBeam as RegFaceGrinBeam,
    FaRegFaceGrinBeamSweat as RegFaceGrinBeamSweat,
    FaRegFaceGrinHearts as RegFaceGrinHearts,
    FaRegFaceGrinSquint as RegFaceGrinSquint,
    FaRegFaceGrinSquintTears as RegFaceGrinSquintTears,
    FaRegFaceGrinStars as RegFaceGrinStars,
    FaRegFaceGrinTears as RegFaceGrinTears,
    FaRegFaceGrinTongue as RegFaceGrinTongue,
    FaRegFaceGrinTongueSquint as RegFaceGrinTongueSquint,
    FaRegFaceGrinTongueWink as RegFaceGrinTongueWink,
    FaRegFaceGrinWide as RegFaceGrinWide,
    FaRegFaceGrinWink as RegFaceGrinWink,
    FaRegFaceKiss as RegFaceKiss,
    FaRegFaceKissBeam as RegFaceKissBeam,
    FaRegFaceKissWinkHeart as RegFaceKissWinkHeart,
    FaRegFaceLaugh as RegFaceLaugh,
    FaRegFaceLaughBeam as RegFaceLaughBeam,
    FaRegFaceLaughSquint as RegFaceLaughSquint,
    FaRegFaceLaughWink as RegFaceLaughWink,
    FaRegFaceMeh as RegFaceMeh,
    FaRegFaceMehBlank as RegFaceMehBlank,
    FaRegFaceRollingEyes as RegFaceRollingEyes,
    FaRegFaceSadCry as RegFaceSadCry,
    FaRegFaceSadTear as RegFaceSadTear,
    FaRegFaceSmile as RegFaceSmile,
    FaRegFaceSmileBeam as RegFaceSmileBeam,
    FaRegFaceSmileWink as RegFaceSmileWink,
    FaRegFaceSurprise as RegFaceSurprise,
    FaRegFaceTired as RegFaceTired,
    FaRegFileLines as RegFileLines,
    FaRegFileZipper as RegFileZipper,
    FaRegFloppyDisk as RegFloppyDisk,
    FaRegFolderClosed as RegFolderClosed,
    FaRegFontAwesome as RegFontAwesome,
    FaRegHand as RegHand,
    FaRegHandBackFist as RegHandBackFist,
    FaRegHardDrive as RegHardDrive,
    FaRegHourglassHalf as RegHourglassHalf,
    FaRegMessage as RegMessage,
    FaRegMoneyBill1 as RegMoneyBill1,
    FaRegNoteSticky as RegNoteSticky,
    FaRegPaste as RegPaste,
    FaRegPenToSquare as RegPenToSquare,
    FaRegRectangleList as RegRectangleList,
    FaRegRectangleXmark as RegRectangleXmark,
    FaRegShareFromSquare as RegShareFromSquare,
    FaRegSquareCaretDown as RegSquareCaretDown,
    FaRegSquareCaretLeft as RegSquareCaretLeft,
    FaRegSquareCaretRight as RegSquareCaretRight,
    FaRegSquareCaretUp as RegSquareCaretUp,
    FaRegSquareCheck as RegSquareCheck,
    FaRegSquareFull as RegSquareFull,
    FaRegSquareMinus as RegSquareMinus,
    FaRegSquarePlus as RegSquarePlus,
    FaRegStarHalfStroke as RegStarHalfStroke,
    FaRegTrashCan as RegTrashCan,
    FaRightFromBracket as RightFromBracket,
    FaRightLeft as RightLeft,
    FaRightLong as RightLong,
    FaRightToBracket as RightToBracket,
    FaRoadBarrier as RoadBarrier,
    FaRoadBridge as RoadBridge,
    FaRoadCircleCheck as RoadCircleCheck,
    FaRoadCircleExclamation as RoadCircleExclamation,
    FaRoadCircleXmark as RoadCircleXmark,
    FaRoadLock as RoadLock,
    FaRoadSpikes as RoadSpikes,
    FaRotate as Rotate,
    FaRug as Rug,
    FaRupiahSign as RupiahSign,
    FaS as S,
    FaSackDollar as SackDollar,
    FaSackXmark as SackXmark,
    FaSailboat as Sailboat,
    FaScaleBalanced as ScaleBalanced,
    FaScaleUnbalanced as ScaleUnbalanced,
    FaScaleUnbalancedFlip as ScaleUnbalancedFlip,
    FaSchoolCircleCheck as SchoolCircleCheck,
    FaSchoolCircleExclamation as SchoolCircleExclamation,
    FaSchoolCircleXmark as SchoolCircleXmark,
    FaSchoolFlag as SchoolFlag,
    FaSchoolLock as SchoolLock,
    FaScissors as Scissors,
    FaScreenpal as Screenpal,
    FaScrewdriverWrench as ScrewdriverWrench,
    FaScrollTorah as ScrollTorah,
    FaSection as Section,
    FaShareFromSquare as ShareFromSquare,
    FaShareNodes as ShareNodes,
    FaSheetPlastic as SheetPlastic,
    FaShieldCat as ShieldCat,
    FaShieldDog as ShieldDog,
    FaShieldHalved as ShieldHalved,
    FaShieldHeart as ShieldHeart,
    FaShirt as Shirt,
    FaShopLock as ShopLock,
    FaShopSlash as ShopSlash,
    FaShrimp as Shrimp,
    FaShuttleSpace as ShuttleSpace,
    FaSignHanging as SignHanging,
    FaSignsPost as SignsPost,
    FaSitrox as Sitrox,
    FaSliders as Sliders,
    FaSpaceAwesome as SpaceAwesome,
    FaSpaghettiMonsterFlying as SpaghettiMonsterFlying,
    FaSpoon as Spoon,
    FaSprayCanSparkles as SprayCanSparkles,
    FaSquareArrowUpRight as SquareArrowUpRight,
    FaSquareBehance as SquareBehance,
    FaSquareCaretDown as SquareCaretDown,
    FaSquareCaretLeft as SquareCaretLeft,
    FaSquareCaretRight as SquareCaretRight,
    FaSquareCaretUp as SquareCaretUp,
    FaSquareCheck as SquareCheck,
    FaSquareDribbble as SquareDribbble,
    FaSquareEnvelope as SquareEnvelope,
    FaSquareFacebook as SquareFacebook,
    FaSquareFontAwesome as SquareFontAwesome,
    FaSquareFontAwesomeStroke as SquareFontAwesomeStroke,
    FaSquareGit as SquareGit,
    FaSquareGithub as SquareGithub,
    FaSquareGitlab as SquareGitlab,
    FaSquareGooglePlus as SquareGooglePlus,
    FaSquareH as SquareH,
    FaSquareHackerNews as SquareHackerNews,
    FaSquareInstagram as SquareInstagram,
    FaSquareJs as SquareJs,
    FaSquareLastfm as SquareLastfm,
    FaSquareMinus as SquareMinus,
    FaSquareNfi as SquareNfi,
    FaSquareOdnoklassniki as SquareOdnoklassniki,
    FaSquareParking as SquareParking,
    FaSquarePen as SquarePen,
    FaSquarePersonConfined as SquarePersonConfined,
    FaSquarePhone as SquarePhone,
    FaSquarePhoneFlip as SquarePhoneFlip,
    FaSquarePiedPiper as SquarePiedPiper,
    FaSquarePinterest as SquarePinterest,
    FaSquarePlus as SquarePlus,
    FaSquarePollHorizontal as SquarePollHorizontal,
    FaSquarePollVertical as SquarePollVertical,
    FaSquareReddit as SquareReddit,
    FaSquareRootVariable as SquareRootVariable,
    FaSquareRss as SquareRss,
    FaSquareShareNodes as SquareShareNodes,
    FaSquareSnapchat as SquareSnapchat,
    FaSquareSteam as SquareSteam,
    FaSquareTumblr as SquareTumblr,
    FaSquareTwitter as SquareTwitter,
    FaSquareUpRight as SquareUpRight,
    FaSquareViadeo as SquareViadeo,
    FaSquareVimeo as SquareVimeo,
    FaSquareVirus as SquareVirus,
    FaSquareWhatsapp as SquareWhatsapp,
    FaSquareXing as SquareXing,
    FaSquareXmark as SquareXmark,
    FaSquareYoutube as SquareYoutube,
    FaStaffSnake as StaffSnake,
    FaStapler as Stapler,
    FaStarHalfStroke as StarHalfStroke,
    FaSterlingSign as SterlingSign,
    FaStubber as Stubber,
    FaSuitcaseMedical as SuitcaseMedical,
    FaSunPlantWilt as SunPlantWilt,
    FaT as T,
    FaTableCells as TableCells,
    FaTableCellsLarge as TableCellsLarge,
    FaTableColumns as TableColumns,
    FaTableList as TableList,
    FaTableTennisPaddleBall as TableTennisPaddleBall,
    FaTabletButton as TabletButton,
    FaTabletScreenButton as TabletScreenButton,
    FaTachographDigital as TachographDigital,
    FaTarp as Tarp,
    FaTarpDroplet as TarpDroplet,
    FaTemperatureArrowDown as TemperatureArrowDown,
    FaTemperatureArrowUp as TemperatureArrowUp,
    FaTemperatureEmpty as TemperatureEmpty,
    FaTemperatureFull as TemperatureFull,
    FaTemperatureHalf as TemperatureHalf,
    FaTemperatureQuarter as TemperatureQuarter,
    FaTemperatureThreeQuarters as TemperatureThreeQuarters,
    FaTengeSign as TengeSign,
    FaTent as Tent,
    FaTentArrowDownToLine as TentArrowDownToLine,
    FaTentArrowLeftRight as TentArrowLeftRight,
    FaTentArrowsDown as TentArrowsDown,
    FaTentArrowTurnLeft as TentArrowTurnLeft,
    FaTents as Tents,
    FaTextSlash as TextSlash,
    FaTicket as Ticket,
    FaTicketSimple as TicketSimple,
    FaToiletPortable as ToiletPortable,
    FaToiletsPortable as ToiletsPortable,
    FaTowerBroadcast as TowerBroadcast,
    FaTowerCell as TowerCell,
    FaTowerObservation as TowerObservation,
    FaTrainSubway as TrainSubway,
    FaTrainTram as TrainTram,
    FaTrashArrowUp as TrashArrowUp,
    FaTrashCan as TrashCan,
    FaTrashCanArrowUp as TrashCanArrowUp,
    FaTreeCity as TreeCity,
    FaTriangleExclamation as TriangleExclamation,
    FaTrowel as Trowel,
    FaTrowelBricks as TrowelBricks,
    FaTruckArrowRight as TruckArrowRight,
    FaTruckDroplet as TruckDroplet,
    FaTruckFast as TruckFast,
    FaTruckField as TruckField,
    FaTruckFieldUn as TruckFieldUn,
    FaTruckFront as TruckFront,
    FaTruckMedical as TruckMedical,
    FaTruckPlane as TruckPlane,
    FaTruckRampBox as TruckRampBox,
    FaTurkishLiraSign as TurkishLiraSign,
    FaTurnDown as TurnDown,
    FaTurnUp as TurnUp,
    FaU as U,
    FaUnlockKeyhole as UnlockKeyhole,
    FaUpDown as UpDown,
    FaUpDownLeftRight as UpDownLeftRight,
    FaUpLong as UpLong,
    FaUpRightAndDownLeftFromCenter as UpRightAndDownLeftFromCenter,
    FaUpRightFromSquare as UpRightFromSquare,
    FaUserDoctor as UserDoctor,
    FaUserGear as UserGear,
    FaUserGroup as UserGroup,
    FaUserLarge as UserLarge,
    FaUserLargeSlash as UserLargeSlash,
    FaUserPen as UserPen,
    FaUsersBetweenLines as UsersBetweenLines,
    FaUsersGear as UsersGear,
    FaUsersLine as UsersLine,
    FaUsersRays as UsersRays,
    FaUsersRectangle as UsersRectangle,
    FaUsersViewfinder as UsersViewfinder,
    FaUserXmark as UserXmark,
    FaV as V,
    FaVanShuttle as VanShuttle,
    FaVault as Vault,
    FaVialCircleCheck as VialCircleCheck,
    FaVialVirus as VialVirus,
    FaVirusCovid as VirusCovid,
    FaVirusCovidSlash as VirusCovidSlash,
    FaVolleyball as Volleyball,
    FaVolumeHigh as VolumeHigh,
    FaVolumeXmark as VolumeXmark,
    FaW as W,
    FaWalkieTalkie as WalkieTalkie,
    FaWandMagic as WandMagic,
    FaWandMagicSparkles as WandMagicSparkles,
    FaWandSparkles as WandSparkles,
    FaWaterLadder as WaterLadder,
    FaWeightScale as WeightScale,
    FaWheatAwn as WheatAwn,
    FaWheatAwnCircleExclamation as WheatAwnCircleExclamation,
    FaWheelchairMove as WheelchairMove,
    FaWhiskeyGlass as WhiskeyGlass,
    FaWineGlassEmpty as WineGlassEmpty,
    FaWirsindhandwerk as Wirsindhandwerk,
    FaWorm as Worm,
    FaXmark as Xmark,
    FaXmarksLines as XmarksLines,
    FaY as Y,
    FaZ as Z,
    FaZhihu as Zhihu,
} from 'react-icons/fa6';

export {
    A,
    AnchorCircleCheck,
    AnchorCircleExclamation,
    AnchorCircleXmark,
    AnchorLock,
    AnglesDown,
    AnglesLeft,
    AnglesRight,
    AnglesUp,
    AppleWhole,
    ArrowDown19,
    ArrowDown91,
    ArrowDownAZ,
    ArrowDownLong,
    ArrowDownShortWide,
    ArrowDownUpAcrossLine,
    ArrowDownUpLock,
    ArrowDownWideShort,
    ArrowDownZA,
    ArrowLeftLong,
    ArrowPointer,
    ArrowRightArrowLeft,
    ArrowRightFromBracket,
    ArrowRightLong,
    ArrowRightToBracket,
    ArrowRightToCity,
    ArrowRotateLeft,
    ArrowRotateRight,
    ArrowTrendDown,
    ArrowTrendUp,
    ArrowTurnDown,
    ArrowTurnUp,
    ArrowUp19,
    ArrowUp91,
    ArrowUpAZ,
    ArrowUpFromBracket,
    ArrowUpFromGroundWater,
    ArrowUpFromWaterPump,
    ArrowUpLong,
    ArrowUpRightDots,
    ArrowUpRightFromSquare,
    ArrowUpShortWide,
    ArrowUpWideShort,
    ArrowUpZA,
    ArrowsDownToLine,
    ArrowsDownToPeople,
    ArrowsLeftRight,
    ArrowsLeftRightToLine,
    ArrowsRotate,
    ArrowsSpin,
    ArrowsSplitUpAndLeft,
    ArrowsToCircle,
    ArrowsToDot,
    ArrowsToEye,
    ArrowsTurnRight,
    ArrowsTurnToDots,
    ArrowsUpDown,
    ArrowsUpDownLeftRight,
    ArrowsUpToLine,
    AustralSign,
    B,
    BackwardFast,
    BackwardStep,
    BagShopping,
    BahtSign,
    BanSmoking,
    Bandage,
    BangladeshiTakaSign,
    BarsProgress,
    BarsStaggered,
    BaseballBatBall,
    BasketShopping,
    BedPulse,
    BeerMugEmpty,
    BellConcierge,
    Bilibili,
    BitcoinSign,
    BoltLightning,
    BookAtlas,
    BookBible,
    BookJournalWhills,
    BookOpenReader,
    BookQuran,
    BookSkull,
    BookTanakh,
    BorderTopLeft,
    BoreHole,
    Bots,
    BottleDroplet,
    BottleWater,
    BowlFood,
    BoxArchive,
    BoxesPacking,
    BoxesStacked,
    BrazilianRealSign,
    Bridge,
    BridgeCircleCheck,
    BridgeCircleExclamation,
    BridgeCircleXmark,
    BridgeLock,
    BridgeWater,
    BroomBall,
    Bucket,
    BugSlash,
    Bugs,
    BuildingCircleArrowRight,
    BuildingCircleCheck,
    BuildingCircleExclamation,
    BuildingCircleXmark,
    BuildingColumns,
    BuildingFlag,
    BuildingLock,
    BuildingNgo,
    BuildingShield,
    BuildingUn,
    BuildingUser,
    BuildingWheat,
    Burger,
    Burst,
    BusSimple,
    C,
    CakeCandles,
    CalendarDays,
    CalendarXmark,
    CameraRotate,
    CarBurst,
    CarOn,
    CarRear,
    CarTunnel,
    CartFlatbed,
    CartFlatbedSuitcase,
    CartShopping,
    CediSign,
    CentSign,
    ChalkboardUser,
    ChampagneGlasses,
    ChartColumn,
    ChartGantt,
    ChartSimple,
    CheckToSlot,
    ChildCombatant,
    ChildDress,
    ChildReaching,
    Children,
    CircleArrowDown,
    CircleArrowLeft,
    CircleArrowRight,
    CircleArrowUp,
    CircleCheck,
    CircleChevronDown,
    CircleChevronLeft,
    CircleChevronRight,
    CircleChevronUp,
    CircleDollarToSlot,
    CircleDot,
    CircleDown,
    CircleExclamation,
    CircleH,
    CircleHalfStroke,
    CircleInfo,
    CircleLeft,
    CircleMinus,
    CircleNodes,
    CirclePause,
    CirclePlay,
    CirclePlus,
    CircleQuestion,
    CircleRadiation,
    CircleRight,
    CircleStop,
    CircleUp,
    CircleUser,
    CircleXmark,
    Clapperboard,
    ClipboardQuestion,
    ClipboardUser,
    ClockRotateLeft,
    CloudArrowDown,
    CloudArrowUp,
    CloudBolt,
    CloudShowersWater,
    Clover,
    Cmplid,
    CodeCommit,
    CodeCompare,
    CodeFork,
    CodeMerge,
    CodePullRequest,
    ColonSign,
    CommentSms,
    CompassDrafting,
    ComputerMouse,
    Cow,
    CropSimple,
    CruzeiroSign,
    CubesStacked,
    D,
    DeleteLeft,
    DiagramNext,
    DiagramPredecessor,
    DiagramProject,
    DiagramSuccessor,
    DiamondTurnRight,
    Display,
    DongSign,
    DownLeftAndUpRightToCenter,
    DownLong,
    DropletSlash,
    E,
    EarDeaf,
    EarListen,
    EarthAfrica,
    EarthAmericas,
    EarthAsia,
    EarthEurope,
    EarthOceania,
    Ellipsis,
    EllipsisVertical,
    EnvelopeCircleCheck,
    EnvelopesBulk,
    Explosion,
    EyeLowVision,
    F,
    FaceAngry,
    FaceDizzy,
    FaceFlushed,
    FaceFrown,
    FaceFrownOpen,
    FaceGrimace,
    FaceGrin,
    FaceGrinBeam,
    FaceGrinBeamSweat,
    FaceGrinHearts,
    FaceGrinSquint,
    FaceGrinSquintTears,
    FaceGrinStars,
    FaceGrinTears,
    FaceGrinTongue,
    FaceGrinTongueSquint,
    FaceGrinTongueWink,
    FaceGrinWide,
    FaceGrinWink,
    FaceKiss,
    FaceKissBeam,
    FaceKissWinkHeart,
    FaceLaugh,
    FaceLaughBeam,
    FaceLaughSquint,
    FaceLaughWink,
    FaceMeh,
    FaceMehBlank,
    FaceRollingEyes,
    FaceSadCry,
    FaceSadTear,
    FaceSmile,
    FaceSmileBeam,
    FaceSmileWink,
    FaceSurprise,
    FaceTired,
    FaucetDrip,
    FeatherPointed,
    Ferry,
    FileArrowDown,
    FileArrowUp,
    FileCircleCheck,
    FileCircleExclamation,
    FileCircleMinus,
    FileCirclePlus,
    FileCircleQuestion,
    FileCircleXmark,
    FileLines,
    FilePen,
    FileShield,
    FileWaveform,
    FileZipper,
    FilterCircleDollar,
    FilterCircleXmark,
    FireBurner,
    FireFlameCurved,
    FireFlameSimple,
    FishFins,
    FlaskVial,
    FloppyDisk,
    FlorinSign,
    FolderClosed,
    FolderTree,
    ForwardFast,
    ForwardStep,
    FrancSign,
    G,
    Gauge,
    GaugeHigh,
    GaugeSimple,
    GaugeSimpleHigh,
    Gear,
    Gears,
    GlassWater,
    GlassWaterDroplet,
    Golang,
    GolfBallTee,
    Grip,
    GroupArrowsRotate,
    GuaraniSign,
    Gun,
    H,
    Hand,
    HandBackFist,
    HandDots,
    HandFist,
    HandHoldingDollar,
    HandHoldingDroplet,
    HandHoldingHand,
    Handcuffs,
    HandsAslInterpreting,
    HandsBound,
    HandsBubbles,
    HandsClapping,
    HandsHolding,
    HandsHoldingChild,
    HandsHoldingCircle,
    HandsPraying,
    HandshakeAngle,
    HandshakeSimple,
    HandshakeSimpleSlash,
    HardDrive,
    Hashnode,
    HeadphonesSimple,
    HeartCircleBolt,
    HeartCircleCheck,
    HeartCircleExclamation,
    HeartCircleMinus,
    HeartCirclePlus,
    HeartCircleXmark,
    HeartCrack,
    HeartPulse,
    HelicopterSymbol,
    HelmetSafety,
    HelmetUn,
    HillAvalanche,
    HillRockslide,
    HotTubPerson,
    HouseChimney,
    HouseChimneyCrack,
    HouseChimneyMedical,
    HouseChimneyUser,
    HouseChimneyWindow,
    HouseCircleCheck,
    HouseCircleExclamation,
    HouseCircleXmark,
    HouseCrack,
    HouseFire,
    HouseFlag,
    HouseFloodWater,
    HouseFloodWaterCircleArrowRight,
    HouseLaptop,
    HouseLock,
    HouseMedical,
    HouseMedicalCircleCheck,
    HouseMedicalCircleExclamation,
    HouseMedicalCircleXmark,
    HouseMedicalFlag,
    HouseSignal,
    HouseTsunami,
    HryvniaSign,
    Hurricane,
    I,
    IdCardClip,
    ImagePortrait,
    IndianRupeeSign,
    J,
    Jar,
    JarWheat,
    JetFighter,
    JetFighterUp,
    JugDetergent,
    K,
    KipSign,
    KitMedical,
    KitchenSet,
    L,
    LandMineOn,
    LandmarkDome,
    LandmarkFlag,
    LaptopFile,
    LariSign,
    LeftLong,
    LeftRight,
    LinesLeaning,
    LinkSlash,
    LitecoinSign,
    LocationCrosshairs,
    LocationDot,
    LocationPin,
    LocationPinLock,
    Locust,
    M,
    MagnifyingGlass,
    MagnifyingGlassArrowRight,
    MagnifyingGlassChart,
    MagnifyingGlassDollar,
    MagnifyingGlassLocation,
    MagnifyingGlassMinus,
    MagnifyingGlassPlus,
    ManatSign,
    MapLocation,
    MapLocationDot,
    MarsAndVenus,
    MarsAndVenusBurst,
    MarsStrokeRight,
    MarsStrokeUp,
    MartiniGlass,
    MartiniGlassCitrus,
    MartiniGlassEmpty,
    MaskFace,
    MaskVentilator,
    MasksTheater,
    MattressPillow,
    Meta,
    MicrophoneLines,
    MicrophoneLinesSlash,
    MillSign,
    MobileButton,
    MobileRetro,
    MobileScreen,
    MobileScreenButton,
    MoneyBill1,
    MoneyBill1Wave,
    MoneyBillTransfer,
    MoneyBillTrendUp,
    MoneyBillWheat,
    MoneyBills,
    MoneyCheckDollar,
    Mosquito,
    MosquitoNet,
    Mound,
    MountainCity,
    MountainSun,
    MugSaucer,
    N,
    NairaSign,
    NfcDirectional,
    NfcSymbol,
    Notdef,
    NoteSticky,
    O,
    Odysee,
    OilWell,
    P,
    Padlet,
    Paintbrush,
    PenClip,
    PenRuler,
    PenToSquare,
    PeopleCarryBox,
    PeopleGroup,
    PeopleLine,
    PeoplePulling,
    PeopleRobbery,
    PeopleRoof,
    PersonArrowDownToLine,
    PersonArrowUpFromLine,
    PersonBiking,
    PersonBreastfeeding,
    PersonBurst,
    PersonCane,
    PersonChalkboard,
    PersonCircleCheck,
    PersonCircleExclamation,
    PersonCircleMinus,
    PersonCirclePlus,
    PersonCircleQuestion,
    PersonCircleXmark,
    PersonDigging,
    PersonDotsFromLine,
    PersonDress,
    PersonDressBurst,
    PersonDrowning,
    PersonFalling,
    PersonFallingBurst,
    PersonHalfDress,
    PersonHarassing,
    PersonHiking,
    PersonMilitaryPointing,
    PersonMilitaryRifle,
    PersonMilitaryToPerson,
    PersonPraying,
    PersonPregnant,
    PersonRays,
    PersonRifle,
    PersonRunning,
    PersonShelter,
    PersonSkating,
    PersonSkiing,
    PersonSkiingNordic,
    PersonSnowboarding,
    PersonSwimming,
    PersonThroughWindow,
    PersonWalking,
    PersonWalkingArrowLoopLeft,
    PersonWalkingArrowRight,
    PersonWalkingDashedLineArrowRight,
    PersonWalkingLuggage,
    PersonWalkingWithCane,
    PesetaSign,
    PesoSign,
    PhoneFlip,
    PhotoFilm,
    PlaneCircleCheck,
    PlaneCircleExclamation,
    PlaneCircleXmark,
    PlaneLock,
    PlaneUp,
    PlantWilt,
    PlateWheat,
    PlugCircleBolt,
    PlugCircleCheck,
    PlugCircleExclamation,
    PlugCircleMinus,
    PlugCirclePlus,
    PlugCircleXmark,
    PlusMinus,
    PrescriptionBottleMedical,
    Q,
    R,
    RankingStar,
    RectangleAd,
    RectangleList,
    RectangleXmark,
    RegCalendarDays,
    RegCalendarXmark,
    RegChessBishop,
    RegChessKing,
    RegChessKnight,
    RegChessPawn,
    RegChessQueen,
    RegChessRook,
    RegCircleCheck,
    RegCircleDot,
    RegCircleDown,
    RegCircleLeft,
    RegCirclePause,
    RegCirclePlay,
    RegCircleQuestion,
    RegCircleRight,
    RegCircleStop,
    RegCircleUp,
    RegCircleUser,
    RegCircleXmark,
    RegFaceAngry,
    RegFaceDizzy,
    RegFaceFlushed,
    RegFaceFrown,
    RegFaceFrownOpen,
    RegFaceGrimace,
    RegFaceGrin,
    RegFaceGrinBeam,
    RegFaceGrinBeamSweat,
    RegFaceGrinHearts,
    RegFaceGrinSquint,
    RegFaceGrinSquintTears,
    RegFaceGrinStars,
    RegFaceGrinTears,
    RegFaceGrinTongue,
    RegFaceGrinTongueSquint,
    RegFaceGrinTongueWink,
    RegFaceGrinWide,
    RegFaceGrinWink,
    RegFaceKiss,
    RegFaceKissBeam,
    RegFaceKissWinkHeart,
    RegFaceLaugh,
    RegFaceLaughBeam,
    RegFaceLaughSquint,
    RegFaceLaughWink,
    RegFaceMeh,
    RegFaceMehBlank,
    RegFaceRollingEyes,
    RegFaceSadCry,
    RegFaceSadTear,
    RegFaceSmile,
    RegFaceSmileBeam,
    RegFaceSmileWink,
    RegFaceSurprise,
    RegFaceTired,
    RegFileLines,
    RegFileZipper,
    RegFloppyDisk,
    RegFolderClosed,
    RegFontAwesome,
    RegHand,
    RegHandBackFist,
    RegHardDrive,
    RegHourglassHalf,
    RegMessage,
    RegMoneyBill1,
    RegNoteSticky,
    RegPaste,
    RegPenToSquare,
    RegRectangleList,
    RegRectangleXmark,
    RegShareFromSquare,
    RegSquareCaretDown,
    RegSquareCaretLeft,
    RegSquareCaretRight,
    RegSquareCaretUp,
    RegSquareCheck,
    RegSquareFull,
    RegSquareMinus,
    RegSquarePlus,
    RegStarHalfStroke,
    RegTrashCan,
    RightFromBracket,
    RightLeft,
    RightLong,
    RightToBracket,
    RoadBarrier,
    RoadBridge,
    RoadCircleCheck,
    RoadCircleExclamation,
    RoadCircleXmark,
    RoadLock,
    RoadSpikes,
    Rotate,
    Rug,
    RupiahSign,
    S,
    SackDollar,
    SackXmark,
    Sailboat,
    ScaleBalanced,
    ScaleUnbalanced,
    ScaleUnbalancedFlip,
    SchoolCircleCheck,
    SchoolCircleExclamation,
    SchoolCircleXmark,
    SchoolFlag,
    SchoolLock,
    Scissors,
    Screenpal,
    ScrewdriverWrench,
    ScrollTorah,
    Section,
    ShareFromSquare,
    ShareNodes,
    SheetPlastic,
    ShieldCat,
    ShieldDog,
    ShieldHalved,
    ShieldHeart,
    Shirt,
    ShopLock,
    ShopSlash,
    Shrimp,
    ShuttleSpace,
    SignHanging,
    SignsPost,
    Sitrox,
    Sliders,
    SpaceAwesome,
    SpaghettiMonsterFlying,
    Spoon,
    SprayCanSparkles,
    SquareArrowUpRight,
    SquareBehance,
    SquareCaretDown,
    SquareCaretLeft,
    SquareCaretRight,
    SquareCaretUp,
    SquareCheck,
    SquareDribbble,
    SquareEnvelope,
    SquareFacebook,
    SquareFontAwesome,
    SquareFontAwesomeStroke,
    SquareGit,
    SquareGithub,
    SquareGitlab,
    SquareGooglePlus,
    SquareH,
    SquareHackerNews,
    SquareInstagram,
    SquareJs,
    SquareLastfm,
    SquareMinus,
    SquareNfi,
    SquareOdnoklassniki,
    SquareParking,
    SquarePen,
    SquarePersonConfined,
    SquarePhone,
    SquarePhoneFlip,
    SquarePiedPiper,
    SquarePinterest,
    SquarePlus,
    SquarePollHorizontal,
    SquarePollVertical,
    SquareReddit,
    SquareRootVariable,
    SquareRss,
    SquareShareNodes,
    SquareSnapchat,
    SquareSteam,
    SquareTumblr,
    SquareTwitter,
    SquareUpRight,
    SquareViadeo,
    SquareVimeo,
    SquareVirus,
    SquareWhatsapp,
    SquareXing,
    SquareXmark,
    SquareYoutube,
    StaffSnake,
    Stapler,
    StarHalfStroke,
    SterlingSign,
    Stubber,
    SuitcaseMedical,
    SunPlantWilt,
    T,
    TableCells,
    TableCellsLarge,
    TableColumns,
    TableList,
    TableTennisPaddleBall,
    TabletButton,
    TabletScreenButton,
    TachographDigital,
    Tarp,
    TarpDroplet,
    TemperatureArrowDown,
    TemperatureArrowUp,
    TemperatureEmpty,
    TemperatureFull,
    TemperatureHalf,
    TemperatureQuarter,
    TemperatureThreeQuarters,
    TengeSign,
    Tent,
    TentArrowDownToLine,
    TentArrowLeftRight,
    TentArrowTurnLeft,
    TentArrowsDown,
    Tents,
    TextSlash,
    Ticket,
    TicketSimple,
    ToiletPortable,
    ToiletsPortable,
    TowerBroadcast,
    TowerCell,
    TowerObservation,
    TrainSubway,
    TrainTram,
    TrashArrowUp,
    TrashCan,
    TrashCanArrowUp,
    TreeCity,
    TriangleExclamation,
    Trowel,
    TrowelBricks,
    TruckArrowRight,
    TruckDroplet,
    TruckFast,
    TruckField,
    TruckFieldUn,
    TruckFront,
    TruckMedical,
    TruckPlane,
    TruckRampBox,
    TurkishLiraSign,
    TurnDown,
    TurnUp,
    U,
    UnlockKeyhole,
    UpDown,
    UpDownLeftRight,
    UpLong,
    UpRightAndDownLeftFromCenter,
    UpRightFromSquare,
    UserDoctor,
    UserGear,
    UserGroup,
    UserLarge,
    UserLargeSlash,
    UserPen,
    UserXmark,
    UsersBetweenLines,
    UsersGear,
    UsersLine,
    UsersRays,
    UsersRectangle,
    UsersViewfinder,
    V,
    VanShuttle,
    Vault,
    VialCircleCheck,
    VialVirus,
    VirusCovid,
    VirusCovidSlash,
    Volleyball,
    VolumeHigh,
    VolumeXmark,
    W,
    WalkieTalkie,
    WandMagic,
    WandMagicSparkles,
    WandSparkles,
    WaterLadder,
    WeightScale,
    WheatAwn,
    WheatAwnCircleExclamation,
    WheelchairMove,
    WhiskeyGlass,
    WineGlassEmpty,
    Wirsindhandwerk,
    Worm,
    Xmark,
    XmarksLines,
    Y,
    Z,
    Zhihu,
    _0,
    _1,
    _2,
    _3,
    _4,
    _42Group,
    _5,
    _6,
    _7,
    _8,
    _9,
};
// import * as fa6Icons from 'react-icons/fa6';
// import * as muiIcons from './materialUI';
// import * as faIcons from './fontAwesome';
// import * as biIcons from './boxIcons';

// const fa6IconsNames: string[] = [];
// console.log(
//     `import { ${Object.entries(fa6Icons)
//         .map((i) => {
//             let alias = i[0].substring(2); // remove first 2 characters

//             // If alias starts with a number, prepend it with an underscore
//             if (/^[0-9]/.test(alias)) {
//                 alias = `_${alias}`;
//             }
//             if (!Object.keys(muiIcons).includes(alias) && !Object.keys(faIcons).includes(alias) && !Object.keys(biIcons).includes(alias)) {
//                 fa6IconsNames.push(alias);
//                 return `${i[0]} as ${alias}`;
//             }
//             return ''; // return empty string when if condition is not met
//         })
//         .filter((item) => item) // filter out the empty strings
//         .join(', ')} } from 'react-icons/ai';`,
// );

// console.log(`export { ${fa6IconsNames.join(', ')} } `);

// export { fa6IconsIconsNames };
