// Icons 2
/** biome-ignore-all lint/suspicious/noShadowRestrictedNames: <explanation> */
import {
    Fa500Px as _500Px,
    FaAccessibleIcon as AccessibleIcon,
    FaAccusoft as Accusoft,
    FaAcquisitionsIncorporated as AcquisitionsIncorporated,
    FaAd as Ad,
    FaAddressBook as AddressBook,
    FaAddressCard as AddressCard,
    FaAdjust as Adjust2,
    FaAdn as Adn,
    FaAdversal as Adversal,
    FaAffiliatetheme as Affiliatetheme,
    FaAirbnb as Airbnb,
    FaAirFreshener as AirFreshener,
    FaAlgolia as Algolia,
    FaAlignCenter as AlignCenter,
    FaAlignJustify as AlignJustify,
    FaAlignLeft as AlignLeft,
    FaAlignRight as AlignRight,
    FaAlipay as Alipay,
    FaAllergies as Allergies,
    FaAmazon as Amazon,
    FaAmazonPay as AmazonPay,
    FaAmbulance as Ambulance,
    FaAmericanSignLanguageInterpreting as AmericanSignLanguageInterpreting,
    FaAmilia as Amilia,
    FaAnchor as Anchor2,
    FaAndroid as Android2,
    FaAngellist as Angellist,
    FaAngleDoubleDown as AngleDoubleDown,
    FaAngleDoubleLeft as AngleDoubleLeft,
    FaAngleDoubleRight as AngleDoubleRight,
    FaAngleDoubleUp as AngleDoubleUp,
    FaAngleDown as AngleDown,
    FaAngleLeft as AngleLeft,
    FaAngleRight as AngleRight,
    FaAngleUp as AngleUp,
    FaAngry as Angry,
    FaAngrycreative as Angrycreative,
    FaAngular as Angular,
    FaAnkh as Ankh,
    FaApper as Apper,
    FaApple as Apple2,
    FaAppleAlt as AppleAlt,
    FaApplePay as ApplePay,
    FaAppStore as AppStore,
    FaAppStoreIos as AppStoreIos,
    FaArchive as Archive2,
    FaArchway as Archway,
    FaArrowAltCircleDown as ArrowAltCircleDown,
    FaArrowAltCircleLeft as ArrowAltCircleLeft,
    FaArrowAltCircleRight as ArrowAltCircleRight,
    FaArrowAltCircleUp as ArrowAltCircleUp,
    FaArrowCircleDown as ArrowCircleDown2,
    FaArrowCircleLeft as ArrowCircleLeft2,
    FaArrowCircleRight as ArrowCircleRight2,
    FaArrowCircleUp as ArrowCircleUp2,
    FaArrowDown as ArrowDown,
    FaArrowLeft as ArrowLeft2,
    FaArrowRight as ArrowRight2,
    FaArrowsAlt as ArrowsAlt,
    FaArrowsAltH as ArrowsAltH,
    FaArrowsAltV as ArrowsAltV,
    FaArrowUp as ArrowUp,
    FaArtstation as Artstation,
    FaAssistiveListeningSystems as AssistiveListeningSystems,
    FaAsterisk as Asterisk,
    FaAsymmetrik as Asymmetrik,
    FaAt as At,
    FaAtlas as Atlas,
    FaAtlassian as Atlassian,
    FaAtom as Atom,
    FaAudible as Audible,
    FaAudioDescription as AudioDescription,
    FaAutoprefixer as Autoprefixer,
    FaAvianex as Avianex,
    FaAviato as Aviato,
    FaAward as Award,
    FaAws as Aws,
    FaBaby as Baby,
    FaBabyCarriage as BabyCarriage,
    FaBackspace as Backspace2,
    FaBackward as Backward,
    FaBacon as Bacon,
    FaBacteria as Bacteria,
    FaBacterium as Bacterium,
    FaBahai as Bahai,
    FaBalanceScale as BalanceScale,
    FaBalanceScaleLeft as BalanceScaleLeft,
    FaBalanceScaleRight as BalanceScaleRight,
    FaBan as Ban,
    FaBandAid as BandAid,
    FaBandcamp as Bandcamp,
    FaBarcode as Barcode,
    FaBars as Bars,
    FaBaseballBall as BaseballBall,
    FaBasketballBall as BasketballBall,
    FaBath as Bath,
    FaBatteryEmpty as BatteryEmpty,
    FaBatteryFull as BatteryFull2,
    FaBatteryHalf as BatteryHalf,
    FaBatteryQuarter as BatteryQuarter,
    FaBatteryThreeQuarters as BatteryThreeQuarters,
    FaBattleNet as BattleNet,
    FaBed as Bed2,
    FaBeer as Beer,
    FaBehance as Behance,
    FaBehanceSquare as BehanceSquare,
    FaBell as Bell,
    FaBellSlash as BellSlash,
    FaBezierCurve as BezierCurve,
    FaBible as Bible,
    FaBicycle as Bicycle,
    FaBiking as Biking,
    FaBimobject as Bimobject,
    FaBinoculars as Binoculars,
    FaBiohazard as Biohazard,
    FaBirthdayCake as BirthdayCake,
    FaBitbucket as Bitbucket,
    FaBitcoin as Bitcoin,
    FaBity as Bity,
    FaBlackberry as Blackberry,
    FaBlackTie as BlackTie,
    FaBlender as Blender2,
    FaBlenderPhone as BlenderPhone,
    FaBlind as Blind,
    FaBlog as Blog,
    FaBlogger as Blogger,
    FaBloggerB as BloggerB,
    FaBluetooth as Bluetooth2,
    FaBluetoothB as BluetoothB,
    FaBold as Bold,
    FaBolt as Bolt2,
    FaBomb as Bomb,
    FaBone as Bone,
    FaBong as Bong,
    FaBook as Book2,
    FaBookDead as BookDead,
    FaBookMedical as BookMedical,
    FaBookmark as Bookmark2,
    FaBookOpen as BookOpen,
    FaBookReader as BookReader,
    FaBootstrap as Bootstrap,
    FaBorderAll as BorderAll2,
    FaBorderNone as BorderNone,
    FaBorderStyle as BorderStyle2,
    FaBowlingBall as BowlingBall,
    FaBox as Box,
    FaBoxes as Boxes,
    FaBoxOpen as BoxOpen,
    FaBoxTissue as BoxTissue,
    FaBraille as Braille,
    FaBrain as Brain,
    FaBreadSlice as BreadSlice,
    FaBriefcase as Briefcase,
    FaBriefcaseMedical as BriefcaseMedical,
    FaBroadcastTower as BroadcastTower,
    FaBroom as Broom,
    FaBrush as Brush2,
    FaBtc as Btc,
    FaBuffer as Buffer,
    FaBug as Bug,
    FaBuilding as Building,
    FaBullhorn as Bullhorn,
    FaBullseye as Bullseye,
    FaBurn as Burn,
    FaBuromobelexperte as Buromobelexperte,
    FaBus as Bus,
    FaBusAlt as BusAlt,
    FaBusinessTime as BusinessTime,
    FaBuyNLarge as BuyNLarge,
    FaBuysellads as Buysellads,
    FaCalculator as Calculator,
    FaCalendar as Calendar,
    FaCalendarAlt as CalendarAlt,
    FaCalendarCheck as CalendarCheck,
    FaCalendarDay as CalendarDay,
    FaCalendarMinus as CalendarMinus,
    FaCalendarPlus as CalendarPlus,
    FaCalendarTimes as CalendarTimes,
    FaCalendarWeek as CalendarWeek,
    FaCamera as Camera2,
    FaCameraRetro as CameraRetro,
    FaCampground as Campground,
    FaCanadianMapleLeaf as CanadianMapleLeaf,
    FaCandyCane as CandyCane,
    FaCannabis as Cannabis,
    FaCapsules as Capsules,
    FaCar as Car,
    FaCarAlt as CarAlt,
    FaCaravan as Caravan,
    FaCarBattery as CarBattery,
    FaCarCrash as CarCrash2,
    FaCaretDown as CaretDown,
    FaCaretLeft as CaretLeft,
    FaCaretRight as CaretRight,
    FaCaretSquareDown as CaretSquareDown,
    FaCaretSquareLeft as CaretSquareLeft,
    FaCaretSquareRight as CaretSquareRight,
    FaCaretSquareUp as CaretSquareUp,
    FaCaretUp as CaretUp,
    FaCarrot as Carrot,
    FaCarSide as CarSide,
    FaCartArrowDown as CartArrowDown,
    FaCartPlus as CartPlus,
    FaCashRegister as CashRegister,
    FaCat as Cat,
    FaCcAmazonPay as CcAmazonPay,
    FaCcAmex as CcAmex,
    FaCcApplePay as CcApplePay,
    FaCcDinersClub as CcDinersClub,
    FaCcDiscover as CcDiscover,
    FaCcJcb as CcJcb,
    FaCcMastercard as CcMastercard,
    FaCcPaypal as CcPaypal,
    FaCcStripe as CcStripe,
    FaCcVisa as CcVisa,
    FaCentercode as Centercode,
    FaCentos as Centos,
    FaCertificate as Certificate,
    FaChair as Chair2,
    FaChalkboard as Chalkboard,
    FaChalkboardTeacher as ChalkboardTeacher,
    FaChargingStation as ChargingStation2,
    FaChartArea as ChartArea,
    FaChartBar as ChartBar,
    FaChartLine as ChartLine,
    FaChartPie as ChartPie,
    FaCheck as Check2,
    FaCheckCircle as CheckCircle2,
    FaCheckDouble as CheckDouble,
    FaCheckSquare as CheckSquare,
    FaCheese as Cheese,
    FaChess as Chess,
    FaChessBishop as ChessBishop,
    FaChessBoard as ChessBoard,
    FaChessKing as ChessKing,
    FaChessKnight as ChessKnight,
    FaChessPawn as ChessPawn,
    FaChessQueen as ChessQueen,
    FaChessRook as ChessRook,
    FaChevronCircleDown as ChevronCircleDown,
    FaChevronCircleLeft as ChevronCircleLeft,
    FaChevronCircleRight as ChevronCircleRight,
    FaChevronCircleUp as ChevronCircleUp,
    FaChevronDown as ChevronDown,
    FaChevronLeft as ChevronLeft2,
    FaChevronRight as ChevronRight2,
    FaChevronUp as ChevronUp,
    FaChild as Child,
    FaChrome as Chrome,
    FaChromecast as Chromecast,
    FaChurch as Church2,
    FaCircle as Circle2,
    FaCircleNotch as CircleNotch,
    FaCity as City,
    FaClinicMedical as ClinicMedical,
    FaClipboard as Clipboard,
    FaClipboardCheck as ClipboardCheck,
    FaClipboardList as ClipboardList,
    FaClock as Clock,
    FaClone as Clone,
    FaClosedCaptioning as ClosedCaptioning,
    FaCloud as Cloud2,
    FaCloudDownloadAlt as CloudDownloadAlt,
    FaCloudflare as Cloudflare,
    FaCloudMeatball as CloudMeatball,
    FaCloudMoon as CloudMoon,
    FaCloudMoonRain as CloudMoonRain,
    FaCloudRain as CloudRain,
    FaCloudShowersHeavy as CloudShowersHeavy,
    FaCloudSun as CloudSun,
    FaCloudSunRain as CloudSunRain,
    FaCloudscale as Cloudscale,
    FaCloudsmith as Cloudsmith,
    FaCloudUploadAlt as CloudUploadAlt,
    FaCloudversify as Cloudversify,
    FaCocktail as Cocktail,
    FaCode as Code2,
    FaCodeBranch as CodeBranch,
    FaCodepen as Codepen,
    FaCodiepie as Codiepie,
    FaCoffee as Coffee2,
    FaCog as Cog,
    FaCogs as Cogs,
    FaCoins as Coins,
    FaColumns as Columns,
    FaComment as Comment2,
    FaCommentAlt as CommentAlt,
    FaCommentDollar as CommentDollar,
    FaCommentDots as CommentDots,
    FaCommentMedical as CommentMedical,
    FaCommentSlash as CommentSlash,
    FaComments as Comments,
    FaCommentsDollar as CommentsDollar,
    FaCompactDisc as CompactDisc,
    FaCompass as Compass,
    FaCompress as Compress2,
    FaCompressAlt as CompressAlt,
    FaCompressArrowsAlt as CompressArrowsAlt,
    FaConciergeBell as ConciergeBell,
    FaConfluence as Confluence,
    FaConnectdevelop as Connectdevelop,
    FaContao as Contao,
    FaCookie as Cookie2,
    FaCookieBite as CookieBite,
    FaCopy as Copy,
    FaCopyright as Copyright2,
    FaCottonBureau as CottonBureau,
    FaCouch as Couch,
    FaCpanel as Cpanel,
    FaCreativeCommons as CreativeCommons,
    FaCreativeCommonsBy as CreativeCommonsBy,
    FaCreativeCommonsNc as CreativeCommonsNc,
    FaCreativeCommonsNcEu as CreativeCommonsNcEu,
    FaCreativeCommonsNcJp as CreativeCommonsNcJp,
    FaCreativeCommonsNd as CreativeCommonsNd,
    FaCreativeCommonsPd as CreativeCommonsPd,
    FaCreativeCommonsPdAlt as CreativeCommonsPdAlt,
    FaCreativeCommonsRemix as CreativeCommonsRemix,
    FaCreativeCommonsSa as CreativeCommonsSa,
    FaCreativeCommonsSampling as CreativeCommonsSampling,
    FaCreativeCommonsSamplingPlus as CreativeCommonsSamplingPlus,
    FaCreativeCommonsShare as CreativeCommonsShare,
    FaCreativeCommonsZero as CreativeCommonsZero,
    FaCreditCard as CreditCard2,
    FaCriticalRole as CriticalRole,
    FaCrop as Crop2,
    FaCropAlt as CropAlt,
    FaCross as Cross,
    FaCrosshairs as Crosshairs,
    FaCrow as Crow,
    FaCrown as Crown,
    FaCrutch as Crutch,
    FaCss3 as Css3,
    FaCss3Alt as Css3Alt,
    FaCube as Cube,
    FaCubes as Cubes,
    FaCut as Cut,
    FaCuttlefish as Cuttlefish,
    FaDAndD as DAndD,
    FaDAndDBeyond as DAndDBeyond,
    FaDailymotion as Dailymotion,
    FaDashcube as Dashcube,
    FaDatabase as Database,
    FaDeaf as Deaf,
    FaDeezer as Deezer,
    FaDelicious as Delicious,
    FaDemocrat as Democrat,
    FaDeploydog as Deploydog,
    FaDeskpro as Deskpro,
    FaDesktop as Desktop,
    FaDev as Dev,
    FaDeviantart as Deviantart,
    FaDharmachakra as Dharmachakra,
    FaDhl as Dhl,
    FaDiagnoses as Diagnoses,
    FaDiaspora as Diaspora,
    FaDice as Dice,
    FaDiceD6 as DiceD6,
    FaDiceD20 as DiceD20,
    FaDiceFive as DiceFive,
    FaDiceFour as DiceFour,
    FaDiceOne as DiceOne,
    FaDiceSix as DiceSix,
    FaDiceThree as DiceThree,
    FaDiceTwo as DiceTwo,
    FaDigg as Digg,
    FaDigitalOcean as DigitalOcean,
    FaDigitalTachograph as DigitalTachograph,
    FaDirections as Directions2,
    FaDiscord as Discord,
    FaDiscourse as Discourse,
    FaDisease as Disease,
    FaDivide as Divide,
    FaDizzy as Dizzy,
    FaDna as Dna,
    FaDochub as Dochub,
    FaDocker as Docker,
    FaDog as Dog,
    FaDollarSign as DollarSign,
    FaDolly as Dolly,
    FaDollyFlatbed as DollyFlatbed,
    FaDonate as Donate,
    FaDoorClosed as DoorClosed,
    FaDoorOpen as DoorOpen,
    FaDotCircle as DotCircle,
    FaDove as Dove,
    FaDownload as Download2,
    FaDraft2Digital as Draft2Digital,
    FaDraftingCompass as DraftingCompass,
    FaDragon as Dragon,
    FaDrawPolygon as DrawPolygon,
    FaDribbble as Dribbble,
    FaDribbbleSquare as DribbbleSquare,
    FaDropbox as Dropbox,
    FaDrum as Drum,
    FaDrumSteelpan as DrumSteelpan,
    FaDrumstickBite as DrumstickBite,
    FaDrupal as Drupal,
    FaDumbbell as Dumbbell,
    FaDumpster as Dumpster,
    FaDumpsterFire as DumpsterFire,
    FaDungeon as Dungeon,
    FaDyalog as Dyalog,
    FaEarlybirds as Earlybirds,
    FaEbay as Ebay,
    FaEdge as Edge,
    FaEdgeLegacy as EdgeLegacy,
    FaEdit as Edit2,
    FaEgg as Egg2,
    FaEject as Eject2,
    FaElementor as Elementor,
    FaEllipsisH as EllipsisH,
    FaEllipsisV as EllipsisV,
    FaEllo as Ello,
    FaEmber as Ember,
    FaEmpire as Empire,
    FaEnvelope as Envelope,
    FaEnvelopeOpen as EnvelopeOpen,
    FaEnvelopeOpenText as EnvelopeOpenText,
    FaEnvelopeSquare as EnvelopeSquare,
    FaEnvira as Envira,
    FaEquals as Equals,
    FaEraser as Eraser,
    FaErlang as Erlang,
    FaEthereum as Ethereum,
    FaEthernet as Ethernet,
    FaEtsy as Etsy,
    FaEuroSign as EuroSign,
    FaEvernote as Evernote,
    FaExchangeAlt as ExchangeAlt,
    FaExclamation as Exclamation,
    FaExclamationCircle as ExclamationCircle,
    FaExclamationTriangle as ExclamationTriangle,
    FaExpand as Expand2,
    FaExpandAlt as ExpandAlt,
    FaExpandArrowsAlt as ExpandArrowsAlt,
    FaExpeditedssl as Expeditedssl,
    FaExternalLinkAlt as ExternalLinkAlt,
    FaExternalLinkSquareAlt as ExternalLinkSquareAlt,
    FaEye as Eye,
    FaEyeDropper as EyeDropper,
    FaEyeSlash as EyeSlash,
    FaFacebook as Facebook2,
    FaFacebookF as FacebookF,
    FaFacebookMessenger as FacebookMessenger,
    FaFacebookSquare as FacebookSquare,
    FaFan as Fan,
    FaFantasyFlightGames as FantasyFlightGames,
    FaFastBackward as FastBackward,
    FaFastForward as FastForward2,
    FaFaucet as Faucet,
    FaFax as Fax2,
    FaZhihu,
    FaFeather as Feather,
    FaFeatherAlt as FeatherAlt,
    FaFedex as Fedex,
    FaFedora as Fedora,
    FaFemale as Female2,
    FaFighterJet as FighterJet,
    FaFigma as Figma,
    FaFile as File,
    FaFileAlt as FileAlt,
    FaFileArchive as FileArchive,
    FaFileAudio as FileAudio,
    FaFileCode as FileCode,
    FaFileContract as FileContract,
    FaFileCsv as FileCsv,
    FaFileDownload as FileDownload2,
    FaFileExcel as FileExcel,
    FaFileExport as FileExport,
    FaFileImage as FileImage,
    FaFileImport as FileImport,
    FaFileInvoice as FileInvoice,
    FaFileInvoiceDollar as FileInvoiceDollar,
    FaFileMedical as FileMedical,
    FaFileMedicalAlt as FileMedicalAlt,
    FaFilePdf as FilePdf,
    FaFilePowerpoint as FilePowerpoint,
    FaFilePrescription as FilePrescription,
    FaFileSignature as FileSignature,
    FaFileUpload as FileUpload2,
    FaFileVideo as FileVideo,
    FaFileWord as FileWord,
    FaFill as Fill,
    FaFillDrip as FillDrip,
    FaFilm as Film,
    FaFingerprint as Fingerprint2,
    FaFire as Fire,
    FaFireAlt as FireAlt,
    FaFireExtinguisher as FireExtinguisher2,
    FaFirefox as Firefox,
    FaFirefoxBrowser as FirefoxBrowser,
    FaFirstAid as FirstAid,
    FaFirstdraft as Firstdraft,
    FaFirstOrder as FirstOrder,
    FaFirstOrderAlt as FirstOrderAlt,
    FaFish as Fish,
    FaFistRaised as FistRaised,
    FaFlag as Flag2,
    FaFlagCheckered as FlagCheckered,
    FaFlagUsa as FlagUsa,
    FaFlask as Flask,
    FaFlickr as Flickr,
    FaFlipboard as Flipboard,
    FaFlushed as Flushed,
    FaFly as Fly,
    FaFolder as Folder2,
    FaFolderMinus as FolderMinus,
    FaFolderOpen as FolderOpen2,
    FaFolderPlus as FolderPlus,
    FaFont as Font,
    FaFontAwesome as FontAwesome,
    FaFontAwesomeAlt as FontAwesomeAlt,
    FaFontAwesomeFlag as FontAwesomeFlag,
    FaFontAwesomeLogoFull as FontAwesomeLogoFull,
    FaFonticons as Fonticons,
    FaFonticonsFi as FonticonsFi,
    FaFootballBall as FootballBall,
    FaFortAwesome as FortAwesome,
    FaFortAwesomeAlt as FortAwesomeAlt,
    FaForumbee as Forumbee,
    FaForward as Forward2,
    FaFoursquare as Foursquare,
    FaFreebsd as Freebsd,
    FaFreeCodeCamp as FreeCodeCamp,
    FaFrog as Frog,
    FaFrown as Frown,
    FaFrownOpen as FrownOpen,
    FaFulcrum as Fulcrum,
    FaFunnelDollar as FunnelDollar,
    FaFutbol as Futbol,
    FaGalacticRepublic as GalacticRepublic,
    FaGalacticSenate as GalacticSenate,
    FaGamepad as Gamepad2,
    FaGasPump as GasPump,
    FaGavel as Gavel2,
    FaGem as Gem,
    FaGenderless as Genderless,
    FaGetPocket as GetPocket,
    FaGg as Gg,
    FaGgCircle as GgCircle,
    FaGhost as Ghost,
    FaGift as Gift,
    FaGifts as Gifts,
    FaGit as Git,
    FaGitAlt as GitAlt,
    FaGithub as Github,
    FaGithubAlt as GithubAlt,
    FaGithubSquare as GithubSquare,
    FaGitkraken as Gitkraken,
    FaGitlab as Gitlab,
    FaGitSquare as GitSquare,
    FaGitter as Gitter,
    FaGlassCheers as GlassCheers,
    FaGlasses as Glasses,
    FaGlassMartini as GlassMartini,
    FaGlassMartiniAlt as GlassMartiniAlt,
    FaGlassWhiskey as GlassWhiskey,
    FaGlide as Glide,
    FaGlideG as GlideG,
    FaGlobe as Globe,
    FaGlobeAfrica as GlobeAfrica,
    FaGlobeAmericas as GlobeAmericas,
    FaGlobeAsia as GlobeAsia,
    FaGlobeEurope as GlobeEurope,
    FaGofore as Gofore,
    FaGolfBall as GolfBall,
    FaGoodreads as Goodreads,
    FaGoodreadsG as GoodreadsG,
    FaGoogle as Google2,
    FaGoogleDrive as GoogleDrive,
    FaGooglePay as GooglePay,
    FaGooglePlay as GooglePlay,
    FaGooglePlus as GooglePlus,
    FaGooglePlusG as GooglePlusG,
    FaGooglePlusSquare as GooglePlusSquare,
    FaGoogleWallet as GoogleWallet,
    FaGopuram as Gopuram,
    FaGraduationCap as GraduationCap,
    FaGratipay as Gratipay,
    FaGrav as Grav,
    FaGreaterThan as GreaterThan,
    FaGreaterThanEqual as GreaterThanEqual,
    FaGrimace as Grimace,
    FaGrin as Grin,
    FaGrinAlt as GrinAlt,
    FaGrinBeam as GrinBeam,
    FaGrinBeamSweat as GrinBeamSweat,
    FaGrinHearts as GrinHearts,
    FaGrinSquint as GrinSquint,
    FaGrinSquintTears as GrinSquintTears,
    FaGrinStars as GrinStars,
    FaGrinTears as GrinTears,
    FaGrinTongue as GrinTongue,
    FaGrinTongueSquint as GrinTongueSquint,
    FaGrinTongueWink as GrinTongueWink,
    FaGrinWink as GrinWink,
    FaGripfire as Gripfire,
    FaGripHorizontal as GripHorizontal,
    FaGripLines as GripLines,
    FaGripLinesVertical as GripLinesVertical,
    FaGripVertical as GripVertical,
    FaGrunt as Grunt,
    FaGuilded as Guilded,
    FaGuitar as Guitar,
    FaGulp as Gulp,
    FaHackerNews as HackerNews,
    FaHackerNewsSquare as HackerNewsSquare,
    FaHackerrank as Hackerrank,
    FaHamburger as Hamburger,
    FaHammer as Hammer,
    FaHamsa as Hamsa,
    FaHandHolding as HandHolding,
    FaHandHoldingHeart as HandHoldingHeart,
    FaHandHoldingMedical as HandHoldingMedical,
    FaHandHoldingUsd as HandHoldingUsd,
    FaHandHoldingWater as HandHoldingWater,
    FaHandLizard as HandLizard,
    FaHandMiddleFinger as HandMiddleFinger,
    FaHandPaper as HandPaper,
    FaHandPeace as HandPeace,
    FaHandPointDown as HandPointDown,
    FaHandPointer as HandPointer,
    FaHandPointLeft as HandPointLeft,
    FaHandPointRight as HandPointRight,
    FaHandPointUp as HandPointUp,
    FaHandRock as HandRock,
    FaHandScissors as HandScissors,
    FaHandSparkles as HandSparkles,
    FaHandSpock as HandSpock,
    FaHands as Hands,
    FaHandsHelping as HandsHelping,
    FaHandshake as Handshake2,
    FaHandshakeAltSlash as HandshakeAltSlash,
    FaHandshakeSlash as HandshakeSlash,
    FaHandsWash as HandsWash,
    FaHanukiah as Hanukiah,
    FaHardHat as HardHat,
    FaHashtag as Hashtag,
    FaHatCowboy as HatCowboy,
    FaHatCowboySide as HatCowboySide,
    FaHatWizard as HatWizard,
    FaHdd as Hdd,
    FaHeading as Heading,
    FaHeadphones as Headphones2,
    FaHeadphonesAlt as HeadphonesAlt,
    FaHeadSideCough as HeadSideCough,
    FaHeadSideCoughSlash as HeadSideCoughSlash,
    FaHeadSideMask as HeadSideMask,
    FaHeadSideVirus as HeadSideVirus,
    FaHeadset as Headset2,
    FaHeart as Heart,
    FaHeartBroken as HeartBroken2,
    FaHeartbeat as Heartbeat,
    FaHelicopter as Helicopter,
    FaHighlighter as Highlighter,
    FaHiking as Hiking2,
    FaHippo as Hippo,
    FaHips as Hips,
    FaHireAHelper as HireAHelper,
    FaHistory as History2,
    FaHive as Hive2,
    FaHockeyPuck as HockeyPuck,
    FaHollyBerry as HollyBerry,
    FaHome as Home2,
    FaHooli as Hooli,
    FaHornbill as Hornbill,
    FaHorse as Horse,
    FaHorseHead as HorseHead,
    FaHospital as Hospital,
    FaHospitalAlt as HospitalAlt,
    FaHospitalSymbol as HospitalSymbol,
    FaHospitalUser as HospitalUser,
    FaHotdog as Hotdog,
    FaHotel as Hotel2,
    FaHotjar as Hotjar,
    FaHotTub as HotTub2,
    FaHourglass as Hourglass,
    FaHourglassEnd as HourglassEnd,
    FaHourglassHalf as HourglassHalf,
    FaHourglassStart as HourglassStart,
    FaHouseDamage as HouseDamage,
    FaHouseUser as HouseUser,
    FaHouzz as Houzz,
    FaHryvnia as Hryvnia,
    FaHSquare as HSquare,
    FaHtml5 as Html5,
    FaHubspot as Hubspot,
    FaICursor as ICursor,
    FaIceCream as IceCream,
    FaIcicles as Icicles,
    FaIcons as Icons,
    FaIdBadge as IdBadge,
    FaIdCard as IdCard,
    FaIdCardAlt as IdCardAlt,
    FaIdeal as Ideal,
    FaIgloo as Igloo,
    FaImage as Image2,
    FaImages as Images,
    FaImdb as Imdb,
    FaInbox as Inbox2,
    FaIndent as Indent,
    FaIndustry as Industry,
    FaInfinity as Infinity,
    FaInfo as Info2,
    FaInfoCircle as InfoCircle,
    FaInnosoft as Innosoft,
    FaInstagram as Instagram2,
    FaInstagramSquare as InstagramSquare,
    FaInstalod as Instalod,
    FaIntercom as Intercom,
    FaInternetExplorer as InternetExplorer,
    FaInvision as Invision,
    FaIoxhost as Ioxhost,
    FaItalic as Italic,
    FaItchIo as ItchIo,
    FaItunes as Itunes,
    FaItunesNote as ItunesNote,
    FaJava as Java,
    FaJedi as Jedi,
    FaJediOrder as JediOrder,
    FaJenkins as Jenkins,
    FaJira as Jira,
    FaJoget as Joget,
    FaJoint as Joint,
    FaJoomla as Joomla,
    FaJournalWhills as JournalWhills,
    FaJs as Js,
    FaJsfiddle as Jsfiddle,
    FaJsSquare as JsSquare,
    FaKaaba as Kaaba,
    FaKaggle as Kaggle,
    FaKey as Key2,
    FaKeybase as Keybase,
    FaKeyboard as Keyboard2,
    FaKeycdn as Keycdn,
    FaKhanda as Khanda,
    FaKickstarter as Kickstarter,
    FaKickstarterK as KickstarterK,
    FaKiss as Kiss,
    FaKissBeam as KissBeam,
    FaKissWinkHeart as KissWinkHeart,
    FaKiwiBird as KiwiBird,
    FaKorvue as Korvue,
    FaLandmark as Landmark,
    FaLanguage as Language2,
    FaLaptop as Laptop2,
    FaLaptopCode as LaptopCode,
    FaLaptopHouse as LaptopHouse,
    FaLaptopMedical as LaptopMedical,
    FaLaravel as Laravel,
    FaLastfm as Lastfm,
    FaLastfmSquare as LastfmSquare,
    FaLaugh as Laugh,
    FaLaughBeam as LaughBeam,
    FaLaughSquint as LaughSquint,
    FaLaughWink as LaughWink,
    FaLayerGroup as LayerGroup,
    FaLeaf as Leaf,
    FaLeanpub as Leanpub,
    FaLemon as Lemon,
    FaLess as Less,
    FaLessThan as LessThan,
    FaLessThanEqual as LessThanEqual,
    FaLevelDownAlt as LevelDownAlt,
    FaLevelUpAlt as LevelUpAlt,
    FaLifeRing as LifeRing,
    FaLightbulb as Lightbulb2,
    FaLine as Line,
    FaLink as Link2,
    FaLinkedin as Linkedin,
    FaLinkedinIn as LinkedinIn,
    FaLinode as Linode,
    FaLinux as Linux,
    FaLiraSign as LiraSign,
    FaList as List2,
    FaListAlt as ListAlt2,
    FaListOl as ListOl,
    FaListUl as ListUl,
    FaLocationArrow as LocationArrow,
    FaLock as Lock2,
    FaLockOpen as LockOpen2,
    FaLongArrowAltDown as LongArrowAltDown,
    FaLongArrowAltLeft as LongArrowAltLeft,
    FaLongArrowAltRight as LongArrowAltRight,
    FaLongArrowAltUp as LongArrowAltUp,
    FaLowVision as LowVision,
    FaLuggageCart as LuggageCart,
    FaLungs as Lungs,
    FaLungsVirus as LungsVirus,
    FaLyft as Lyft,
    FaMagento as Magento,
    FaMagic as Magic,
    FaMagnet as Magnet,
    FaMailBulk as MailBulk,
    FaMailchimp as Mailchimp,
    FaMale as Male2,
    FaMandalorian as Mandalorian,
    FaMap as Map2,
    FaMapMarked as MapMarked,
    FaMapMarkedAlt as MapMarkedAlt,
    FaMapMarker as MapMarker,
    FaMapMarkerAlt as MapMarkerAlt,
    FaMapPin as MapPin,
    FaMapSigns as MapSigns,
    FaMarkdown as Markdown,
    FaMarker as Marker,
    FaMars as Mars,
    FaMarsDouble as MarsDouble,
    FaMarsStroke as MarsStroke,
    FaMarsStrokeH as MarsStrokeH,
    FaMarsStrokeV as MarsStrokeV,
    FaMask as Mask,
    FaMastodon as Mastodon,
    FaMaxcdn as Maxcdn,
    FaMdb as Mdb,
    FaMedal as Medal,
    FaMedapps as Medapps,
    FaMedium as Medium,
    FaMediumM as MediumM,
    FaMedkit as Medkit,
    FaMedrt as Medrt,
    FaMeetup as Meetup,
    FaMegaport as Megaport,
    FaMeh as Meh,
    FaMehBlank as MehBlank,
    FaMehRollingEyes as MehRollingEyes,
    FaMemory as Memory2,
    FaMendeley as Mendeley,
    FaMenorah as Menorah,
    FaMercury as Mercury,
    FaMeteor as Meteor,
    FaMicroblog as Microblog,
    FaMicrochip as Microchip,
    FaMicrophone as Microphone,
    FaMicrophoneAlt as MicrophoneAlt,
    FaMicrophoneAltSlash as MicrophoneAltSlash,
    FaMicrophoneSlash as MicrophoneSlash,
    FaMicroscope as Microscope,
    FaMicrosoft as Microsoft,
    FaMinus as Minus,
    FaMinusCircle as MinusCircle,
    FaMinusSquare as MinusSquare,
    FaMitten as Mitten,
    FaMix as Mix,
    FaMixcloud as Mixcloud,
    FaMixer as Mixer,
    FaMizuni as Mizuni,
    FaMobile as Mobile,
    FaMobileAlt as MobileAlt,
    FaModx as Modx,
    FaMonero as Monero,
    FaMoneyBill as MoneyBill,
    FaMoneyBillAlt as MoneyBillAlt,
    FaMoneyBillWave as MoneyBillWave,
    FaMoneyBillWaveAlt as MoneyBillWaveAlt,
    FaMoneyCheck as MoneyCheck,
    FaMoneyCheckAlt as MoneyCheckAlt,
    FaMonument as Monument,
    FaMoon as Moon,
    FaMortarPestle as MortarPestle,
    FaMosque as Mosque2,
    FaMotorcycle as Motorcycle,
    FaMountain as Mountain,
    FaMouse as Mouse2,
    FaMousePointer as MousePointer,
    FaMugHot as MugHot,
    FaMusic as Music,
    FaNapster as Napster,
    FaNeos as Neos,
    FaNetworkWired as NetworkWired,
    FaNeuter as Neuter,
    FaNewspaper as Newspaper2,
    FaNimblr as Nimblr,
    FaNode as Node,
    FaNodeJs as NodeJs,
    FaNotEqual as NotEqual,
    FaNotesMedical as NotesMedical,
    FaNpm as Npm,
    FaNs8 as Ns8,
    FaNutritionix as Nutritionix,
    FaObjectGroup as ObjectGroup,
    FaObjectUngroup as ObjectUngroup,
    FaOctopusDeploy as OctopusDeploy,
    FaOdnoklassniki as Odnoklassniki,
    FaOdnoklassnikiSquare as OdnoklassnikiSquare,
    FaOilCan as OilCan,
    FaOldRepublic as OldRepublic,
    FaOm as Om,
    FaOpencart as Opencart,
    FaOpenid as Openid,
    FaOpera as Opera,
    FaOptinMonster as OptinMonster,
    FaOrcid as Orcid,
    FaOsi as Osi,
    FaOtter as Otter,
    FaOutdent as Outdent,
    FaPage4 as Page4,
    FaPagelines as Pagelines,
    FaPager as Pager,
    FaPaintBrush as PaintBrush,
    FaPaintRoller as PaintRoller,
    FaPalette as Palette2,
    FaPalfed as Palfed,
    FaPallet as Pallet,
    FaPaperclip as Paperclip,
    FaPaperPlane as PaperPlane,
    FaParachuteBox as ParachuteBox,
    FaParagraph as Paragraph,
    FaParking as Parking,
    FaPassport as Passport,
    FaPastafarianism as Pastafarianism,
    FaPaste as Paste,
    FaPatreon as Patreon,
    FaPause as Pause2,
    FaPauseCircle as PauseCircle2,
    FaPaw as Paw,
    FaPaypal as Paypal,
    FaPeace as Peace,
    FaPen as Pen,
    FaPenAlt as PenAlt,
    FaPencilAlt as PencilAlt,
    FaPencilRuler as PencilRuler,
    FaPenFancy as PenFancy,
    FaPenNib as PenNib,
    FaPennyArcade as PennyArcade,
    FaPenSquare as PenSquare,
    FaPeopleArrows as PeopleArrows,
    FaPeopleCarry as PeopleCarry,
    FaPepperHot as PepperHot,
    FaPerbyte as Perbyte,
    FaPercent as Percent2,
    FaPercentage as Percentage,
    FaPeriscope as Periscope,
    FaPersonBooth as PersonBooth,
    FaPhabricator as Phabricator,
    FaPhoenixFramework as PhoenixFramework,
    FaPhoenixSquadron as PhoenixSquadron,
    FaPhone as Phone2,
    FaPhoneAlt as PhoneAlt,
    FaPhoneSlash as PhoneSlash,
    FaPhoneSquare as PhoneSquare,
    FaPhoneSquareAlt as PhoneSquareAlt,
    FaPhoneVolume as PhoneVolume,
    FaPhotoVideo as PhotoVideo,
    FaPhp as Php2,
    FaPiedPiper as PiedPiper,
    FaPiedPiperAlt as PiedPiperAlt,
    FaPiedPiperHat as PiedPiperHat,
    FaPiedPiperPp as PiedPiperPp,
    FaPiedPiperSquare as PiedPiperSquare,
    FaPiggyBank as PiggyBank,
    FaPills as Pills,
    FaPinterest as Pinterest2,
    FaPinterestP as PinterestP,
    FaPinterestSquare as PinterestSquare,
    FaPizzaSlice as PizzaSlice,
    FaPlaceOfWorship as PlaceOfWorship,
    FaPlane as Plane,
    FaPlaneArrival as PlaneArrival,
    FaPlaneDeparture as PlaneDeparture,
    FaPlaneSlash as PlaneSlash,
    FaPlay as Play,
    FaPlayCircle as PlayCircle2,
    FaPlaystation as Playstation,
    FaPlug as Plug,
    FaPlus as Plus,
    FaPlusCircle as PlusCircle,
    FaPlusSquare as PlusSquare,
    FaPodcast as Podcast,
    FaPoll as Poll2,
    FaPollH as PollH,
    FaPoo as Poo,
    FaPoop as Poop,
    FaPooStorm as PooStorm,
    FaPortrait as Portrait2,
    FaPoundSign as PoundSign,
    FaPowerOff as PowerOff2,
    FaPray as Pray,
    FaPrayingHands as PrayingHands,
    FaPrescription as Prescription,
    FaPrescriptionBottle as PrescriptionBottle,
    FaPrescriptionBottleAlt as PrescriptionBottleAlt,
    FaPrint as Print2,
    FaProcedures as Procedures,
    FaProductHunt as ProductHunt,
    FaProjectDiagram as ProjectDiagram,
    FaPumpMedical as PumpMedical,
    FaPumpSoap as PumpSoap,
    FaPushed as Pushed,
    FaPuzzlePiece as PuzzlePiece,
    FaPython as Python,
    FaQq as Qq,
    FaQrcode as Qrcode,
    FaQuestion as Question,
    FaQuestionCircle as QuestionCircle,
    FaQuidditch as Quidditch,
    FaQuinscape as Quinscape,
    FaQuora as Quora,
    FaQuoteLeft as QuoteLeft,
    FaQuoteRight as QuoteRight,
    FaQuran as Quran,
    FaRadiation as Radiation,
    FaRadiationAlt as RadiationAlt,
    FaRainbow as Rainbow,
    FaRandom as Random,
    FaRaspberryPi as RaspberryPi,
    FaRavelry as Ravelry,
    FaReact as React,
    FaReacteurope as Reacteurope,
    FaReadme as Readme,
    FaRebel as Rebel,
    FaReceipt as Receipt2,
    FaRecordVinyl as RecordVinyl,
    FaRecycle as Recycle,
    FaReddit as Reddit2,
    FaRedditAlien as RedditAlien,
    FaRedditSquare as RedditSquare,
    FaRedhat as Redhat,
    FaRedo as Redo2,
    FaRedoAlt as RedoAlt,
    FaRedRiver as RedRiver,
    FaRegAddressBook as RegAddressBook,
    FaRegAddressCard as RegAddressCard,
    FaRegAngry as RegAngry,
    FaRegArrowAltCircleDown as RegArrowAltCircleDown,
    FaRegArrowAltCircleLeft as RegArrowAltCircleLeft,
    FaRegArrowAltCircleRight as RegArrowAltCircleRight,
    FaRegArrowAltCircleUp as RegArrowAltCircleUp,
    FaRegBell as RegBell,
    FaRegBellSlash as RegBellSlash,
    FaRegBookmark as RegBookmark,
    FaRegBuilding as RegBuilding,
    FaRegCalendar as RegCalendar,
    FaRegCalendarAlt as RegCalendarAlt,
    FaRegCalendarCheck as RegCalendarCheck,
    FaRegCalendarMinus as RegCalendarMinus,
    FaRegCalendarPlus as RegCalendarPlus,
    FaRegCalendarTimes as RegCalendarTimes,
    FaRegCaretSquareDown as RegCaretSquareDown,
    FaRegCaretSquareLeft as RegCaretSquareLeft,
    FaRegCaretSquareRight as RegCaretSquareRight,
    FaRegCaretSquareUp as RegCaretSquareUp,
    FaRegChartBar as RegChartBar,
    FaRegCheckCircle as RegCheckCircle,
    FaRegCheckSquare as RegCheckSquare,
    FaRegCircle as RegCircle,
    FaRegClipboard as RegClipboard,
    FaRegClock as RegClock,
    FaRegClone as RegClone,
    FaRegClosedCaptioning as RegClosedCaptioning,
    FaRegComment as RegComment,
    FaRegCommentAlt as RegCommentAlt,
    FaRegCommentDots as RegCommentDots,
    FaRegComments as RegComments,
    FaRegCompass as RegCompass,
    FaRegCopy as RegCopy,
    FaRegCopyright as RegCopyright,
    FaRegCreditCard as RegCreditCard,
    FaRegDizzy as RegDizzy,
    FaRegDotCircle as RegDotCircle,
    FaRegEdit as RegEdit,
    FaRegEnvelope as RegEnvelope,
    FaRegEnvelopeOpen as RegEnvelopeOpen,
    FaRegEye as RegEye,
    FaRegEyeSlash as RegEyeSlash,
    FaRegFile as RegFile,
    FaRegFileAlt as RegFileAlt,
    FaRegFileArchive as RegFileArchive,
    FaRegFileAudio as RegFileAudio,
    FaRegFileCode as RegFileCode,
    FaRegFileExcel as RegFileExcel,
    FaRegFileImage as RegFileImage,
    FaRegFilePdf as RegFilePdf,
    FaRegFilePowerpoint as RegFilePowerpoint,
    FaRegFileVideo as RegFileVideo,
    FaRegFileWord as RegFileWord,
    FaRegFlag as RegFlag,
    FaRegFlushed as RegFlushed,
    FaRegFolder as RegFolder,
    FaRegFolderOpen as RegFolderOpen,
    FaRegFontAwesomeLogoFull as RegFontAwesomeLogoFull,
    FaRegFrown as RegFrown,
    FaRegFrownOpen as RegFrownOpen,
    FaRegFutbol as RegFutbol,
    FaRegGem as RegGem,
    FaRegGrimace as RegGrimace,
    FaRegGrin as RegGrin,
    FaRegGrinAlt as RegGrinAlt,
    FaRegGrinBeam as RegGrinBeam,
    FaRegGrinBeamSweat as RegGrinBeamSweat,
    FaRegGrinHearts as RegGrinHearts,
    FaRegGrinSquint as RegGrinSquint,
    FaRegGrinSquintTears as RegGrinSquintTears,
    FaRegGrinStars as RegGrinStars,
    FaRegGrinTears as RegGrinTears,
    FaRegGrinTongue as RegGrinTongue,
    FaRegGrinTongueSquint as RegGrinTongueSquint,
    FaRegGrinTongueWink as RegGrinTongueWink,
    FaRegGrinWink as RegGrinWink,
    FaRegHandLizard as RegHandLizard,
    FaRegHandPaper as RegHandPaper,
    FaRegHandPeace as RegHandPeace,
    FaRegHandPointDown as RegHandPointDown,
    FaRegHandPointer as RegHandPointer,
    FaRegHandPointLeft as RegHandPointLeft,
    FaRegHandPointRight as RegHandPointRight,
    FaRegHandPointUp as RegHandPointUp,
    FaRegHandRock as RegHandRock,
    FaRegHandScissors as RegHandScissors,
    FaRegHandSpock as RegHandSpock,
    FaRegHandshake as RegHandshake,
    FaRegHdd as RegHdd,
    FaRegHeart as RegHeart,
    FaRegHospital as RegHospital,
    FaRegHourglass as RegHourglass,
    FaRegIdBadge as RegIdBadge,
    FaRegIdCard as RegIdCard,
    FaRegImage as RegImage,
    FaRegImages as RegImages,
    FaRegistered as Registered,
    FaRegKeyboard as RegKeyboard,
    FaRegKiss as RegKiss,
    FaRegKissBeam as RegKissBeam,
    FaRegKissWinkHeart as RegKissWinkHeart,
    FaRegLaugh as RegLaugh,
    FaRegLaughBeam as RegLaughBeam,
    FaRegLaughSquint as RegLaughSquint,
    FaRegLaughWink as RegLaughWink,
    FaRegLemon as RegLemon,
    FaRegLifeRing as RegLifeRing,
    FaRegLightbulb as RegLightbulb,
    FaRegListAlt as RegListAlt,
    FaRegMap as RegMap,
    FaRegMeh as RegMeh,
    FaRegMehBlank as RegMehBlank,
    FaRegMehRollingEyes as RegMehRollingEyes,
    FaRegMinusSquare as RegMinusSquare,
    FaRegMoneyBillAlt as RegMoneyBillAlt,
    FaRegMoon as RegMoon,
    FaRegNewspaper as RegNewspaper,
    FaRegObjectGroup as RegObjectGroup,
    FaRegObjectUngroup as RegObjectUngroup,
    FaRegPaperPlane as RegPaperPlane,
    FaRegPauseCircle as RegPauseCircle,
    FaRegPlayCircle as RegPlayCircle,
    FaRegPlusSquare as RegPlusSquare,
    FaRegQuestionCircle as RegQuestionCircle,
    FaRegRegistered as RegRegistered,
    FaRegSadCry as RegSadCry,
    FaRegSadTear as RegSadTear,
    FaRegSave as RegSave,
    FaRegShareSquare as RegShareSquare,
    FaRegSmile as RegSmile,
    FaRegSmileBeam as RegSmileBeam,
    FaRegSmileWink as RegSmileWink,
    FaRegSnowflake as RegSnowflake,
    FaRegSquare as RegSquare,
    FaRegStar as RegStar,
    FaRegStarHalf as RegStarHalf,
    FaRegStickyNote as RegStickyNote,
    FaRegStopCircle as RegStopCircle,
    FaRegSun as RegSun,
    FaRegSurprise as RegSurprise,
    FaRegThumbsDown as RegThumbsDown,
    FaRegThumbsUp as RegThumbsUp,
    FaRegTimesCircle as RegTimesCircle,
    FaRegTired as RegTired,
    FaRegTrashAlt as RegTrashAlt,
    FaRegUser as RegUser,
    FaRegUserCircle as RegUserCircle,
    FaRegWindowClose as RegWindowClose,
    FaRegWindowMaximize as RegWindowMaximize,
    FaRegWindowMinimize as RegWindowMinimize,
    FaRegWindowRestore as RegWindowRestore,
    FaRemoveFormat as RemoveFormat,
    FaRenren as Renren,
    FaReply as Reply2,
    FaReplyAll as ReplyAll2,
    FaReplyd as Replyd,
    FaRepublican as Republican,
    FaResearchgate as Researchgate,
    FaResolving as Resolving,
    FaRestroom as Restroom,
    FaRetweet as Retweet,
    FaRev as Rev,
    FaRibbon as Ribbon,
    FaRing as Ring,
    FaRoad as Road,
    FaRobot as Robot,
    FaRocket as Rocket2,
    FaRocketchat as Rocketchat,
    FaRockrms as Rockrms,
    FaRoute as Route2,
    FaRProject as RProject,
    FaRss as Rss,
    FaRssSquare as RssSquare,
    FaRubleSign as RubleSign,
    FaRuler as Ruler,
    FaRulerCombined as RulerCombined,
    FaRulerHorizontal as RulerHorizontal,
    FaRulerVertical as RulerVertical,
    FaRunning as Running,
    FaRupeeSign as RupeeSign,
    FaRust as Rust,
    FaSadCry as SadCry,
    FaSadTear as SadTear,
    FaSafari as Safari,
    FaSalesforce as Salesforce,
    FaSass as Sass,
    FaSatellite as Satellite2,
    FaSatelliteDish as SatelliteDish,
    FaSave as Save2,
    FaSchlix as Schlix,
    FaSchool as School2,
    FaScrewdriver as Screwdriver,
    FaScribd as Scribd,
    FaScroll as Scroll,
    FaSdCard as SdCard2,
    FaSearch as Search2,
    FaSearchDollar as SearchDollar,
    FaSearchengin as Searchengin,
    FaSearchLocation as SearchLocation,
    FaSearchMinus as SearchMinus,
    FaSearchPlus as SearchPlus,
    FaSeedling as Seedling,
    FaSellcast as Sellcast,
    FaSellsy as Sellsy,
    FaServer as Server,
    FaServicestack as Servicestack,
    FaShapes as Shapes,
    FaShare as Share2,
    FaShareAlt as ShareAlt,
    FaShareAltSquare as ShareAltSquare,
    FaShareSquare as ShareSquare,
    FaShekelSign as ShekelSign,
    FaShieldAlt as ShieldAlt,
    FaShieldVirus as ShieldVirus,
    FaShip as Ship,
    FaShippingFast as ShippingFast,
    FaShirtsinbulk as Shirtsinbulk,
    FaShoePrints as ShoePrints,
    FaShopify as Shopify,
    FaShoppingBag as ShoppingBag2,
    FaShoppingBasket as ShoppingBasket2,
    FaShoppingCart as ShoppingCart2,
    FaShopware as Shopware,
    FaShower as Shower2,
    FaShuttleVan as ShuttleVan,
    FaSign as Sign,
    FaSignal as Signal,
    FaSignature as Signature,
    FaSignInAlt as SignInAlt,
    FaSignLanguage as SignLanguage2,
    FaSignOutAlt as SignOutAlt,
    FaSimCard as SimCard2,
    FaSimplybuilt as Simplybuilt,
    FaSink as Sink,
    FaSistrix as Sistrix,
    FaSitemap as Sitemap,
    FaSith as Sith,
    FaSkating as Skating,
    FaSketch as Sketch,
    FaSkiing as Skiing,
    FaSkiingNordic as SkiingNordic,
    FaSkull as Skull,
    FaSkullCrossbones as SkullCrossbones,
    FaSkyatlas as Skyatlas,
    FaSkype as Skype,
    FaSlack as Slack,
    FaSlackHash as SlackHash,
    FaSlash as Slash,
    FaSleigh as Sleigh,
    FaSlidersH as SlidersH,
    FaSlideshare as Slideshare,
    FaSmile as Smile,
    FaSmileBeam as SmileBeam,
    FaSmileWink as SmileWink,
    FaSmog as Smog,
    FaSmoking as Smoking,
    FaSmokingBan as SmokingBan,
    FaSms as Sms2,
    FaSnapchat as Snapchat,
    FaSnapchatGhost as SnapchatGhost,
    FaSnapchatSquare as SnapchatSquare,
    FaSnowboarding as Snowboarding2,
    FaSnowflake as Snowflake,
    FaSnowman as Snowman,
    FaSnowplow as Snowplow,
    FaSoap as Soap2,
    FaSocks as Socks,
    FaSolarPanel as SolarPanel,
    FaSort as Sort2,
    FaSortAlphaDown as SortAlphaDown,
    FaSortAlphaDownAlt as SortAlphaDownAlt,
    FaSortAlphaUp as SortAlphaUp,
    FaSortAlphaUpAlt as SortAlphaUpAlt,
    FaSortAmountDown as SortAmountDown,
    FaSortAmountDownAlt as SortAmountDownAlt,
    FaSortAmountUp as SortAmountUp,
    FaSortAmountUpAlt as SortAmountUpAlt,
    FaSortDown as SortDown,
    FaSortNumericDown as SortNumericDown,
    FaSortNumericDownAlt as SortNumericDownAlt,
    FaSortNumericUp as SortNumericUp,
    FaSortNumericUpAlt as SortNumericUpAlt,
    FaSortUp as SortUp,
    FaSoundcloud as Soundcloud,
    FaSourcetree as Sourcetree,
    FaSpa as Spa2,
    FaSpaceShuttle as SpaceShuttle,
    FaSpeakap as Speakap,
    FaSpeakerDeck as SpeakerDeck,
    FaSpellCheck as SpellCheck,
    FaSpider as Spider,
    FaSpinner as Spinner,
    FaSplotch as Splotch,
    FaSpotify as Spotify,
    FaSprayCan as SprayCan,
    FaSquare as Square2,
    FaSquareFull as SquareFull,
    FaSquareRootAlt as SquareRootAlt,
    FaSquarespace as Squarespace,
    FaStackExchange as StackExchange,
    FaStackOverflow as StackOverflow,
    FaStackpath as Stackpath,
    FaStamp as Stamp,
    FaStar as Star2,
    FaStarAndCrescent as StarAndCrescent,
    FaStarHalf as StarHalf2,
    FaStarHalfAlt as StarHalfAlt,
    FaStarOfDavid as StarOfDavid,
    FaStarOfLife as StarOfLife,
    FaStaylinked as Staylinked,
    FaSteam as Steam,
    FaSteamSquare as SteamSquare,
    FaSteamSymbol as SteamSymbol,
    FaStepBackward as StepBackward,
    FaStepForward as StepForward,
    FaStethoscope as Stethoscope,
    FaStickerMule as StickerMule,
    FaStickyNote as StickyNote,
    FaStop as Stop2,
    FaStopCircle as StopCircle2,
    FaStopwatch as Stopwatch,
    FaStopwatch20 as Stopwatch20,
    FaStore as Store2,
    FaStoreAlt as StoreAlt,
    FaStoreAltSlash as StoreAltSlash,
    FaStoreSlash as StoreSlash,
    FaStrava as Strava,
    FaStream as Stream2,
    FaStreetView as StreetView,
    FaStrikethrough as Strikethrough,
    FaStripe as Stripe,
    FaStripeS as StripeS,
    FaStroopwafel as Stroopwafel,
    FaStudiovinari as Studiovinari,
    FaStumbleupon as Stumbleupon,
    FaStumbleuponCircle as StumbleuponCircle,
    FaSubscript as Subscript2,
    FaSubway as Subway2,
    FaSuitcase as Suitcase,
    FaSuitcaseRolling as SuitcaseRolling,
    FaSun as Sun,
    FaSuperpowers as Superpowers,
    FaSuperscript as Superscript2,
    FaSupple as Supple,
    FaSurprise as Surprise,
    FaSuse as Suse,
    FaSwatchbook as Swatchbook,
    FaSwift as Swift,
    FaSwimmer as Swimmer,
    FaSwimmingPool as SwimmingPool,
    FaSymfony as Symfony,
    FaSynagogue as Synagogue2,
    FaSync as Sync2,
    FaSyncAlt as SyncAlt2,
    FaSyringe as Syringe,
    FaTable as Table,
    FaTableTennis as TableTennis,
    FaTablet as Tablet2,
    FaTabletAlt as TabletAlt,
    FaTablets as Tablets,
    FaTachometerAlt as TachometerAlt,
    FaTag as Tag2,
    FaTags as Tags,
    FaTape as Tape,
    FaTasks as Tasks,
    FaTaxi as Taxi,
    FaTeamspeak as Teamspeak,
    FaTeeth as Teeth,
    FaTeethOpen as TeethOpen,
    FaTelegram as Telegram2,
    FaTelegramPlane as TelegramPlane,
    FaTemperatureHigh as TemperatureHigh,
    FaTemperatureLow as TemperatureLow,
    FaTencentWeibo as TencentWeibo,
    FaTenge as Tenge,
    FaTerminal as Terminal2,
    FaTextHeight as TextHeight,
    FaTextWidth as TextWidth,
    FaTh as Th,
    FaTheaterMasks as TheaterMasks,
    FaThemeco as Themeco,
    FaThemeisle as Themeisle,
    FaTheRedYeti as TheRedYeti,
    FaThermometer as Thermometer,
    FaThermometerEmpty as ThermometerEmpty,
    FaThermometerFull as ThermometerFull,
    FaThermometerHalf as ThermometerHalf,
    FaThermometerQuarter as ThermometerQuarter,
    FaThermometerThreeQuarters as ThermometerThreeQuarters,
    FaThinkPeaks as ThinkPeaks,
    FaThLarge as ThLarge,
    FaThList as ThList,
    FaThumbsDown as ThumbsDown,
    FaThumbsUp as ThumbsUp,
    FaThumbtack as Thumbtack,
    FaTicketAlt as TicketAlt,
    FaTiktok as Tiktok,
    FaTimes as Times,
    FaTimesCircle as TimesCircle,
    FaTint as Tint,
    FaTintSlash as TintSlash,
    FaTired as Tired,
    FaToggleOff as ToggleOff2,
    FaToggleOn as ToggleOn2,
    FaToilet as Toilet,
    FaToiletPaper as ToiletPaper,
    FaToiletPaperSlash as ToiletPaperSlash,
    FaToolbox as Toolbox,
    FaTools as Tools,
    FaTooth as Tooth,
    FaTorah as Torah,
    FaToriiGate as ToriiGate,
    FaTractor as Tractor,
    FaTradeFederation as TradeFederation,
    FaTrademark as Trademark,
    FaTrafficLight as TrafficLight,
    FaTrailer as Trailer,
    FaTrain as Train2,
    FaTram as Tram2,
    FaTransgender as Transgender2,
    FaTransgenderAlt as TransgenderAlt,
    FaTrash as Trash,
    FaTrashAlt as TrashAlt,
    FaTrashRestore as TrashRestore,
    FaTrashRestoreAlt as TrashRestoreAlt,
    FaTree as Tree,
    FaTrello as Trello,
    FaTripadvisor as Tripadvisor,
    FaTrophy as Trophy,
    FaTruck as Truck,
    FaTruckLoading as TruckLoading,
    FaTruckMonster as TruckMonster,
    FaTruckMoving as TruckMoving,
    FaTruckPickup as TruckPickup,
    FaTshirt as Tshirt,
    FaTty as Tty2,
    FaTumblr as Tumblr,
    FaTumblrSquare as TumblrSquare,
    FaTv as Tv2,
    FaTwitch as Twitch,
    FaTwitter as Twitter2,
    FaTwitterSquare as TwitterSquare,
    FaTypo3 as Typo3,
    FaUber as Uber,
    FaUbuntu as Ubuntu,
    FaUikit as Uikit,
    FaUmbraco as Umbraco,
    FaUmbrella as Umbrella2,
    FaUmbrellaBeach as UmbrellaBeach,
    FaUncharted as Uncharted,
    FaUnderline as Underline,
    FaUndo as Undo2,
    FaUndoAlt as UndoAlt,
    FaUniregistry as Uniregistry,
    FaUnity as Unity,
    FaUniversalAccess as UniversalAccess,
    FaUniversity as University,
    FaUnlink as Unlink,
    FaUnlock as Unlock,
    FaUnlockAlt as UnlockAlt,
    FaUnsplash as Unsplash,
    FaUntappd as Untappd,
    FaUpload as Upload2,
    FaUps as Ups,
    FaUsb as Usb2,
    FaUser as User,
    FaUserAlt as UserAlt,
    FaUserAltSlash as UserAltSlash,
    FaUserAstronaut as UserAstronaut,
    FaUserCheck as UserCheck,
    FaUserCircle as UserCircle,
    FaUserClock as UserClock,
    FaUserCog as UserCog,
    FaUserEdit as UserEdit,
    FaUserFriends as UserFriends,
    FaUserGraduate as UserGraduate,
    FaUserInjured as UserInjured,
    FaUserLock as UserLock,
    FaUserMd as UserMd,
    FaUserMinus as UserMinus,
    FaUserNinja as UserNinja,
    FaUserNurse as UserNurse,
    FaUserPlus as UserPlus,
    FaUserSecret as UserSecret,
    FaUserShield as UserShield,
    FaUserSlash as UserSlash,
    FaUsers as Users,
    FaUsersCog as UsersCog,
    FaUsersSlash as UsersSlash,
    FaUserTag as UserTag,
    FaUserTie as UserTie,
    FaUserTimes as UserTimes,
    FaUsps as Usps,
    FaUssunnah as Ussunnah,
    FaUtensilSpoon as UtensilSpoon,
    FaUtensils as Utensils,
    FaVaadin as Vaadin,
    FaVectorSquare as VectorSquare,
    FaVenus as Venus,
    FaVenusDouble as VenusDouble,
    FaVenusMars as VenusMars,
    FaVest as Vest,
    FaVestPatches as VestPatches,
    FaViacoin as Viacoin,
    FaViadeo as Viadeo,
    FaViadeoSquare as ViadeoSquare,
    FaVial as Vial,
    FaVials as Vials,
    FaViber as Viber,
    FaVideo as Video,
    FaVideoSlash as VideoSlash,
    FaVihara as Vihara,
    FaVimeo as Vimeo,
    FaVimeoSquare as VimeoSquare,
    FaVimeoV as VimeoV,
    FaVine as Vine,
    FaVirus as Virus,
    FaViruses as Viruses,
    FaVirusSlash as VirusSlash,
    FaVk as Vk,
    FaVnv as Vnv,
    FaVoicemail as Voicemail2,
    FaVolleyballBall as VolleyballBall,
    FaVolumeDown as VolumeDown2,
    FaVolumeMute as VolumeMute2,
    FaVolumeOff as VolumeOff2,
    FaVolumeUp as VolumeUp2,
    FaVoteYea as VoteYea,
    FaVrCardboard as VrCardboard,
    FaVuejs as Vuejs,
    FaWalking as Walking,
    FaWallet as Wallet,
    FaWarehouse as Warehouse2,
    FaWatchmanMonitoring as WatchmanMonitoring,
    FaWater as Water2,
    FaWaveSquare as WaveSquare,
    FaWaze as Waze,
    FaWeebly as Weebly,
    FaWeibo as Weibo,
    FaWeight as Weight,
    FaWeightHanging as WeightHanging,
    FaWeixin as Weixin,
    FaWhatsapp as Whatsapp,
    FaWhatsappSquare as WhatsappSquare,
    FaWheelchair as Wheelchair,
    FaWhmcs as Whmcs,
    FaWifi as Wifi2,
    FaWikipediaW as WikipediaW,
    FaWind as Wind,
    FaWindowClose as WindowClose,
    FaWindowMaximize as WindowMaximize,
    FaWindowMinimize as WindowMinimize,
    FaWindowRestore as WindowRestore,
    FaWindows as Windows,
    FaWineBottle as WineBottle,
    FaWineGlass as WineGlass,
    FaWineGlassAlt as WineGlassAlt,
    FaWix as Wix,
    FaWizardsOfTheCoast as WizardsOfTheCoast,
    FaWodu as Wodu,
    FaWolfPackBattalion as WolfPackBattalion,
    FaWonSign as WonSign,
    FaWordpress as Wordpress,
    FaWordpressSimple as WordpressSimple,
    FaWpbeginner as Wpbeginner,
    FaWpexplorer as Wpexplorer,
    FaWpforms as Wpforms,
    FaWpressr as Wpressr,
    FaWrench as Wrench,
    FaXbox as Xbox,
    FaXing as Xing,
    FaXingSquare as XingSquare,
    FaXRay as XRay,
    FaYahoo as Yahoo,
    FaYammer as Yammer,
    FaYandex as Yandex,
    FaYandexInternational as YandexInternational,
    FaYarn as Yarn,
    FaYCombinator as YCombinator,
    FaYelp as Yelp,
    FaYenSign as YenSign,
    FaYinYang as YinYang,
    FaYoast as Yoast,
    FaYoutube as Youtube,
    FaYoutubeSquare as YoutubeSquare,
} from 'react-icons/fa';

export {
    _500Px,
    AccessibleIcon,
    Accusoft,
    AcquisitionsIncorporated,
    Ad,
    AddressBook,
    AddressCard,
    Adjust2,
    Adn,
    Adversal,
    Affiliatetheme,
    AirFreshener,
    Airbnb,
    Algolia,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Alipay,
    Allergies,
    Amazon,
    AmazonPay,
    Ambulance,
    AmericanSignLanguageInterpreting,
    Amilia,
    Anchor2,
    Android2,
    Angellist,
    AngleDoubleDown,
    AngleDoubleLeft,
    AngleDoubleRight,
    AngleDoubleUp,
    AngleDown,
    AngleLeft,
    AngleRight,
    AngleUp,
    Angry,
    Angrycreative,
    Angular,
    Ankh,
    AppStore,
    AppStoreIos,
    Apper,
    Apple2,
    AppleAlt,
    ApplePay,
    Archive2,
    Archway,
    ArrowAltCircleDown,
    ArrowAltCircleLeft,
    ArrowAltCircleRight,
    ArrowAltCircleUp,
    ArrowCircleDown2,
    ArrowCircleLeft2,
    ArrowCircleRight2,
    ArrowCircleUp2,
    ArrowDown,
    ArrowLeft2,
    ArrowRight2,
    ArrowUp,
    ArrowsAlt,
    ArrowsAltH,
    ArrowsAltV,
    Artstation,
    AssistiveListeningSystems,
    Asterisk,
    Asymmetrik,
    At,
    Atlas,
    Atlassian,
    Atom,
    Audible,
    AudioDescription,
    Autoprefixer,
    Avianex,
    Aviato,
    Award,
    Aws,
    Baby,
    BabyCarriage,
    Backspace2,
    Backward,
    Bacon,
    Bacteria,
    Bacterium,
    Bahai,
    BalanceScale,
    BalanceScaleLeft,
    BalanceScaleRight,
    Ban,
    BandAid,
    Bandcamp,
    Barcode,
    Bars,
    BaseballBall,
    BasketballBall,
    Bath,
    BatteryEmpty,
    BatteryFull2,
    BatteryHalf,
    BatteryQuarter,
    BatteryThreeQuarters,
    BattleNet,
    Bed2,
    Beer,
    Behance,
    BehanceSquare,
    Bell,
    BellSlash,
    BezierCurve,
    Bible,
    Bicycle,
    Biking,
    Bimobject,
    Binoculars,
    Biohazard,
    BirthdayCake,
    Bitbucket,
    Bitcoin,
    Bity,
    BlackTie,
    Blackberry,
    Blender2,
    BlenderPhone,
    Blind,
    Blog,
    Blogger,
    BloggerB,
    Bluetooth2,
    BluetoothB,
    Bold,
    Bolt2,
    Bomb,
    Bone,
    Bong,
    Book2,
    BookDead,
    BookMedical,
    BookOpen,
    BookReader,
    Bookmark2,
    Bootstrap,
    BorderAll2,
    BorderNone,
    BorderStyle2,
    BowlingBall,
    Box,
    BoxOpen,
    BoxTissue,
    Boxes,
    Braille,
    Brain,
    BreadSlice,
    Briefcase,
    BriefcaseMedical,
    BroadcastTower,
    Broom,
    Brush2,
    Btc,
    Buffer,
    Bug,
    Building,
    Bullhorn,
    Bullseye,
    Burn,
    Buromobelexperte,
    Bus,
    BusAlt,
    BusinessTime,
    BuyNLarge,
    Buysellads,
    Calculator,
    Calendar,
    CalendarAlt,
    CalendarCheck,
    CalendarDay,
    CalendarMinus,
    CalendarPlus,
    CalendarTimes,
    CalendarWeek,
    Camera2,
    CameraRetro,
    Campground,
    CanadianMapleLeaf,
    CandyCane,
    Cannabis,
    Capsules,
    Car,
    CarAlt,
    CarBattery,
    CarCrash2,
    CarSide,
    Caravan,
    CaretDown,
    CaretLeft,
    CaretRight,
    CaretSquareDown,
    CaretSquareLeft,
    CaretSquareRight,
    CaretSquareUp,
    CaretUp,
    Carrot,
    CartArrowDown,
    CartPlus,
    CashRegister,
    Cat,
    CcAmazonPay,
    CcAmex,
    CcApplePay,
    CcDinersClub,
    CcDiscover,
    CcJcb,
    CcMastercard,
    CcPaypal,
    CcStripe,
    CcVisa,
    Centercode,
    Centos,
    Certificate,
    Chair2,
    Chalkboard,
    ChalkboardTeacher,
    ChargingStation2,
    ChartArea,
    ChartBar,
    ChartLine,
    ChartPie,
    Check2,
    CheckCircle2,
    CheckDouble,
    CheckSquare,
    Cheese,
    Chess,
    ChessBishop,
    ChessBoard,
    ChessKing,
    ChessKnight,
    ChessPawn,
    ChessQueen,
    ChessRook,
    ChevronCircleDown,
    ChevronCircleLeft,
    ChevronCircleRight,
    ChevronCircleUp,
    ChevronDown,
    ChevronLeft2,
    ChevronRight2,
    ChevronUp,
    Child,
    Chrome,
    Chromecast,
    Church2,
    Circle2,
    CircleNotch,
    City,
    ClinicMedical,
    Clipboard,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Clone,
    ClosedCaptioning,
    Cloud2,
    CloudDownloadAlt,
    CloudMeatball,
    CloudMoon,
    CloudMoonRain,
    CloudRain,
    CloudShowersHeavy,
    CloudSun,
    CloudSunRain,
    CloudUploadAlt,
    Cloudflare,
    Cloudscale,
    Cloudsmith,
    Cloudversify,
    Cocktail,
    Code2,
    CodeBranch,
    Codepen,
    Codiepie,
    Coffee2,
    Cog,
    Cogs,
    Coins,
    Columns,
    Comment2,
    CommentAlt,
    CommentDollar,
    CommentDots,
    CommentMedical,
    CommentSlash,
    Comments,
    CommentsDollar,
    CompactDisc,
    Compass,
    Compress2,
    CompressAlt,
    CompressArrowsAlt,
    ConciergeBell,
    Confluence,
    Connectdevelop,
    Contao,
    Cookie2,
    CookieBite,
    Copy,
    Copyright2,
    CottonBureau,
    Couch,
    Cpanel,
    CreativeCommons,
    CreativeCommonsBy,
    CreativeCommonsNc,
    CreativeCommonsNcEu,
    CreativeCommonsNcJp,
    CreativeCommonsNd,
    CreativeCommonsPd,
    CreativeCommonsPdAlt,
    CreativeCommonsRemix,
    CreativeCommonsSa,
    CreativeCommonsSampling,
    CreativeCommonsSamplingPlus,
    CreativeCommonsShare,
    CreativeCommonsZero,
    CreditCard2,
    CriticalRole,
    Crop2,
    CropAlt,
    Cross,
    Crosshairs,
    Crow,
    Crown,
    Crutch,
    Css3,
    Css3Alt,
    Cube,
    Cubes,
    Cut,
    Cuttlefish,
    DAndD,
    DAndDBeyond,
    Dailymotion,
    Dashcube,
    Database,
    Deaf,
    Deezer,
    Delicious,
    Democrat,
    Deploydog,
    Deskpro,
    Desktop,
    Dev,
    Deviantart,
    Dharmachakra,
    Dhl,
    Diagnoses,
    Diaspora,
    Dice,
    DiceD20,
    DiceD6,
    DiceFive,
    DiceFour,
    DiceOne,
    DiceSix,
    DiceThree,
    DiceTwo,
    Digg,
    DigitalOcean,
    DigitalTachograph,
    Directions2,
    Discord,
    Discourse,
    Disease,
    Divide,
    Dizzy,
    Dna,
    Dochub,
    Docker,
    Dog,
    DollarSign,
    Dolly,
    DollyFlatbed,
    Donate,
    DoorClosed,
    DoorOpen,
    DotCircle,
    Dove,
    Download2,
    Draft2Digital,
    DraftingCompass,
    Dragon,
    DrawPolygon,
    Dribbble,
    DribbbleSquare,
    Dropbox,
    Drum,
    DrumSteelpan,
    DrumstickBite,
    Drupal,
    Dumbbell,
    Dumpster,
    DumpsterFire,
    Dungeon,
    Dyalog,
    Earlybirds,
    Ebay,
    Edge,
    EdgeLegacy,
    Edit2,
    Egg2,
    Eject2,
    Elementor,
    EllipsisH,
    EllipsisV,
    Ello,
    Ember,
    Empire,
    Envelope,
    EnvelopeOpen,
    EnvelopeOpenText,
    EnvelopeSquare,
    Envira,
    Equals,
    Eraser,
    Erlang,
    Ethereum,
    Ethernet,
    Etsy,
    EuroSign,
    Evernote,
    ExchangeAlt,
    Exclamation,
    ExclamationCircle,
    ExclamationTriangle,
    Expand2,
    ExpandAlt,
    ExpandArrowsAlt,
    Expeditedssl,
    ExternalLinkAlt,
    ExternalLinkSquareAlt,
    Eye,
    EyeDropper,
    EyeSlash,
    Facebook2,
    FacebookF,
    FacebookMessenger,
    FacebookSquare,
    Fan,
    FantasyFlightGames,
    FastBackward,
    FastForward2,
    Faucet,
    Fax2,
    Feather,
    FeatherAlt,
    Fedex,
    Fedora,
    Female2,
    FighterJet,
    Figma,
    File,
    FileAlt,
    FileArchive,
    FileAudio,
    FileCode,
    FileContract,
    FileCsv,
    FileDownload2,
    FileExcel,
    FileExport,
    FileImage,
    FileImport,
    FileInvoice,
    FileInvoiceDollar,
    FileMedical,
    FileMedicalAlt,
    FilePdf,
    FilePowerpoint,
    FilePrescription,
    FileSignature,
    FileUpload2,
    FileVideo,
    FileWord,
    Fill,
    FillDrip,
    Film,
    Fingerprint2,
    Fire,
    FireAlt,
    FireExtinguisher2,
    Firefox,
    FirefoxBrowser,
    FirstAid,
    FirstOrder,
    FirstOrderAlt,
    Firstdraft,
    Fish,
    FistRaised,
    Flag2,
    FlagCheckered,
    FlagUsa,
    Flask,
    Flickr,
    Flipboard,
    Flushed,
    Fly,
    Folder2,
    FolderMinus,
    FolderOpen2,
    FolderPlus,
    Font,
    FontAwesome,
    FontAwesomeAlt,
    FontAwesomeFlag,
    FontAwesomeLogoFull,
    Fonticons,
    FonticonsFi,
    FootballBall,
    FortAwesome,
    FortAwesomeAlt,
    Forumbee,
    Forward2,
    Foursquare,
    FreeCodeCamp,
    Freebsd,
    Frog,
    Frown,
    FrownOpen,
    Fulcrum,
    FunnelDollar,
    Futbol,
    GalacticRepublic,
    GalacticSenate,
    Gamepad2,
    GasPump,
    Gavel2,
    Gem,
    Genderless,
    GetPocket,
    Gg,
    GgCircle,
    Ghost,
    Gift,
    Gifts,
    Git,
    GitAlt,
    GitSquare,
    Github,
    GithubAlt,
    GithubSquare,
    Gitkraken,
    Gitlab,
    Gitter,
    GlassCheers,
    GlassMartini,
    GlassMartiniAlt,
    GlassWhiskey,
    Glasses,
    Glide,
    GlideG,
    Globe,
    GlobeAfrica,
    GlobeAmericas,
    GlobeAsia,
    GlobeEurope,
    Gofore,
    GolfBall,
    Goodreads,
    GoodreadsG,
    Google2,
    GoogleDrive,
    GooglePay,
    GooglePlay,
    GooglePlus,
    GooglePlusG,
    GooglePlusSquare,
    GoogleWallet,
    Gopuram,
    GraduationCap,
    Gratipay,
    Grav,
    GreaterThan,
    GreaterThanEqual,
    Grimace,
    Grin,
    GrinAlt,
    GrinBeam,
    GrinBeamSweat,
    GrinHearts,
    GrinSquint,
    GrinSquintTears,
    GrinStars,
    GrinTears,
    GrinTongue,
    GrinTongueSquint,
    GrinTongueWink,
    GrinWink,
    GripHorizontal,
    GripLines,
    GripLinesVertical,
    GripVertical,
    Gripfire,
    Grunt,
    Guilded,
    Guitar,
    Gulp,
    HSquare,
    HackerNews,
    HackerNewsSquare,
    Hackerrank,
    Hamburger,
    Hammer,
    Hamsa,
    HandHolding,
    HandHoldingHeart,
    HandHoldingMedical,
    HandHoldingUsd,
    HandHoldingWater,
    HandLizard,
    HandMiddleFinger,
    HandPaper,
    HandPeace,
    HandPointDown,
    HandPointLeft,
    HandPointRight,
    HandPointUp,
    HandPointer,
    HandRock,
    HandScissors,
    HandSparkles,
    HandSpock,
    Hands,
    HandsHelping,
    HandsWash,
    Handshake2,
    HandshakeAltSlash,
    HandshakeSlash,
    Hanukiah,
    HardHat,
    Hashtag,
    HatCowboy,
    HatCowboySide,
    HatWizard,
    Hdd,
    HeadSideCough,
    HeadSideCoughSlash,
    HeadSideMask,
    HeadSideVirus,
    Heading,
    Headphones2,
    HeadphonesAlt,
    Headset2,
    Heart,
    HeartBroken2,
    Heartbeat,
    Helicopter,
    Highlighter,
    Hiking2,
    Hippo,
    Hips,
    HireAHelper,
    History2,
    Hive2,
    HockeyPuck,
    HollyBerry,
    Home2,
    Hooli,
    Hornbill,
    Horse,
    HorseHead,
    Hospital,
    HospitalAlt,
    HospitalSymbol,
    HospitalUser,
    HotTub2,
    Hotdog,
    Hotel2,
    Hotjar,
    Hourglass,
    HourglassEnd,
    HourglassHalf,
    HourglassStart,
    HouseDamage,
    HouseUser,
    Houzz,
    Hryvnia,
    Html5,
    Hubspot,
    ICursor,
    IceCream,
    Icicles,
    Icons,
    IdBadge,
    IdCard,
    IdCardAlt,
    Ideal,
    Igloo,
    Image2,
    Images,
    Imdb,
    Inbox2,
    Indent,
    Industry,
    Infinity,
    Info2,
    InfoCircle,
    Innosoft,
    Instagram2,
    InstagramSquare,
    Instalod,
    Intercom,
    InternetExplorer,
    Invision,
    Ioxhost,
    Italic,
    ItchIo,
    Itunes,
    ItunesNote,
    Java,
    Jedi,
    JediOrder,
    Jenkins,
    Jira,
    Joget,
    Joint,
    Joomla,
    JournalWhills,
    Js,
    JsSquare,
    Jsfiddle,
    Kaaba,
    Kaggle,
    Key2,
    Keybase,
    Keyboard2,
    Keycdn,
    Khanda,
    Kickstarter,
    KickstarterK,
    Kiss,
    KissBeam,
    KissWinkHeart,
    KiwiBird,
    Korvue,
    Landmark,
    Language2,
    Laptop2,
    LaptopCode,
    LaptopHouse,
    LaptopMedical,
    Laravel,
    Lastfm,
    LastfmSquare,
    Laugh,
    LaughBeam,
    LaughSquint,
    LaughWink,
    LayerGroup,
    Leaf,
    Leanpub,
    Lemon,
    Less,
    LessThan,
    LessThanEqual,
    LevelDownAlt,
    LevelUpAlt,
    LifeRing,
    Lightbulb2,
    Line,
    Link2,
    Linkedin,
    LinkedinIn,
    Linode,
    Linux,
    LiraSign,
    List2,
    ListAlt2,
    ListOl,
    ListUl,
    LocationArrow,
    Lock2,
    LockOpen2,
    LongArrowAltDown,
    LongArrowAltLeft,
    LongArrowAltRight,
    LongArrowAltUp,
    LowVision,
    LuggageCart,
    Lungs,
    LungsVirus,
    Lyft,
    Magento,
    Magic,
    Magnet,
    MailBulk,
    Mailchimp,
    Male2,
    Mandalorian,
    Map2,
    MapMarked,
    MapMarkedAlt,
    MapMarker,
    MapMarkerAlt,
    MapPin,
    MapSigns,
    Markdown,
    Marker,
    Mars,
    MarsDouble,
    MarsStroke,
    MarsStrokeH,
    MarsStrokeV,
    Mask,
    Mastodon,
    Maxcdn,
    Mdb,
    Medal,
    Medapps,
    Medium,
    MediumM,
    Medkit,
    Medrt,
    Meetup,
    Megaport,
    Meh,
    MehBlank,
    MehRollingEyes,
    Memory2,
    Mendeley,
    Menorah,
    Mercury,
    Meteor,
    Microblog,
    Microchip,
    Microphone,
    MicrophoneAlt,
    MicrophoneAltSlash,
    MicrophoneSlash,
    Microscope,
    Microsoft,
    Minus,
    MinusCircle,
    MinusSquare,
    Mitten,
    Mix,
    Mixcloud,
    Mixer,
    Mizuni,
    Mobile,
    MobileAlt,
    Modx,
    Monero,
    MoneyBill,
    MoneyBillAlt,
    MoneyBillWave,
    MoneyBillWaveAlt,
    MoneyCheck,
    MoneyCheckAlt,
    Monument,
    Moon,
    MortarPestle,
    Mosque2,
    Motorcycle,
    Mountain,
    Mouse2,
    MousePointer,
    MugHot,
    Music,
    Napster,
    Neos,
    NetworkWired,
    Neuter,
    Newspaper2,
    Nimblr,
    Node,
    NodeJs,
    NotEqual,
    NotesMedical,
    Npm,
    Ns8,
    Nutritionix,
    ObjectGroup,
    ObjectUngroup,
    OctopusDeploy,
    Odnoklassniki,
    OdnoklassnikiSquare,
    OilCan,
    OldRepublic,
    Om,
    Opencart,
    Openid,
    Opera,
    OptinMonster,
    Orcid,
    Osi,
    Otter,
    Outdent,
    Page4,
    Pagelines,
    Pager,
    PaintBrush,
    PaintRoller,
    Palette2,
    Palfed,
    Pallet,
    PaperPlane,
    Paperclip,
    ParachuteBox,
    Paragraph,
    Parking,
    Passport,
    Pastafarianism,
    Paste,
    Patreon,
    Pause2,
    PauseCircle2,
    Paw,
    Paypal,
    Peace,
    Pen,
    PenAlt,
    PenFancy,
    PenNib,
    PenSquare,
    PencilAlt,
    PencilRuler,
    PennyArcade,
    PeopleArrows,
    PeopleCarry,
    PepperHot,
    Perbyte,
    Percent2,
    Percentage,
    Periscope,
    PersonBooth,
    Phabricator,
    PhoenixFramework,
    PhoenixSquadron,
    Phone2,
    PhoneAlt,
    PhoneSlash,
    PhoneSquare,
    PhoneSquareAlt,
    PhoneVolume,
    PhotoVideo,
    Php2,
    PiedPiper,
    PiedPiperAlt,
    PiedPiperHat,
    PiedPiperPp,
    PiedPiperSquare,
    PiggyBank,
    Pills,
    Pinterest2,
    PinterestP,
    PinterestSquare,
    PizzaSlice,
    PlaceOfWorship,
    Plane,
    PlaneArrival,
    PlaneDeparture,
    PlaneSlash,
    Play,
    PlayCircle2,
    Playstation,
    Plug,
    Plus,
    PlusCircle,
    PlusSquare,
    Podcast,
    Poll2,
    PollH,
    Poo,
    PooStorm,
    Poop,
    Portrait2,
    PoundSign,
    PowerOff2,
    Pray,
    PrayingHands,
    Prescription,
    PrescriptionBottle,
    PrescriptionBottleAlt,
    Print2,
    Procedures,
    ProductHunt,
    ProjectDiagram,
    PumpMedical,
    PumpSoap,
    Pushed,
    PuzzlePiece,
    Python,
    Qq,
    Qrcode,
    Question,
    QuestionCircle,
    Quidditch,
    Quinscape,
    Quora,
    QuoteLeft,
    QuoteRight,
    Quran,
    RProject,
    Radiation,
    RadiationAlt,
    Rainbow,
    Random,
    RaspberryPi,
    Ravelry,
    React,
    Reacteurope,
    Readme,
    Rebel,
    Receipt2,
    RecordVinyl,
    Recycle,
    RedRiver,
    Reddit2,
    RedditAlien,
    RedditSquare,
    Redhat,
    Redo2,
    RedoAlt,
    RegAddressBook,
    RegAddressCard,
    RegAngry,
    RegArrowAltCircleDown,
    RegArrowAltCircleLeft,
    RegArrowAltCircleRight,
    RegArrowAltCircleUp,
    RegBell,
    RegBellSlash,
    RegBookmark,
    RegBuilding,
    RegCalendar,
    RegCalendarAlt,
    RegCalendarCheck,
    RegCalendarMinus,
    RegCalendarPlus,
    RegCalendarTimes,
    RegCaretSquareDown,
    RegCaretSquareLeft,
    RegCaretSquareRight,
    RegCaretSquareUp,
    RegChartBar,
    RegCheckCircle,
    RegCheckSquare,
    RegCircle,
    RegClipboard,
    RegClock,
    RegClone,
    RegClosedCaptioning,
    RegComment,
    RegCommentAlt,
    RegCommentDots,
    RegComments,
    RegCompass,
    RegCopy,
    RegCopyright,
    RegCreditCard,
    RegDizzy,
    RegDotCircle,
    RegEdit,
    RegEnvelope,
    RegEnvelopeOpen,
    RegEye,
    RegEyeSlash,
    RegFile,
    RegFileAlt,
    RegFileArchive,
    RegFileAudio,
    RegFileCode,
    RegFileExcel,
    RegFileImage,
    RegFilePdf,
    RegFilePowerpoint,
    RegFileVideo,
    RegFileWord,
    RegFlag,
    RegFlushed,
    RegFolder,
    RegFolderOpen,
    RegFontAwesomeLogoFull,
    RegFrown,
    RegFrownOpen,
    RegFutbol,
    RegGem,
    RegGrimace,
    RegGrin,
    RegGrinAlt,
    RegGrinBeam,
    RegGrinBeamSweat,
    RegGrinHearts,
    RegGrinSquint,
    RegGrinSquintTears,
    RegGrinStars,
    RegGrinTears,
    RegGrinTongue,
    RegGrinTongueSquint,
    RegGrinTongueWink,
    RegGrinWink,
    RegHandLizard,
    RegHandPaper,
    RegHandPeace,
    RegHandPointDown,
    RegHandPointLeft,
    RegHandPointRight,
    RegHandPointUp,
    RegHandPointer,
    RegHandRock,
    RegHandScissors,
    RegHandSpock,
    RegHandshake,
    RegHdd,
    RegHeart,
    RegHospital,
    RegHourglass,
    RegIdBadge,
    RegIdCard,
    RegImage,
    RegImages,
    RegKeyboard,
    RegKiss,
    RegKissBeam,
    RegKissWinkHeart,
    RegLaugh,
    RegLaughBeam,
    RegLaughSquint,
    RegLaughWink,
    RegLemon,
    RegLifeRing,
    RegLightbulb,
    RegListAlt,
    RegMap,
    RegMeh,
    RegMehBlank,
    RegMehRollingEyes,
    RegMinusSquare,
    RegMoneyBillAlt,
    RegMoon,
    RegNewspaper,
    RegObjectGroup,
    RegObjectUngroup,
    RegPaperPlane,
    RegPauseCircle,
    RegPlayCircle,
    RegPlusSquare,
    RegQuestionCircle,
    RegRegistered,
    RegSadCry,
    RegSadTear,
    RegSave,
    RegShareSquare,
    RegSmile,
    RegSmileBeam,
    RegSmileWink,
    RegSnowflake,
    RegSquare,
    RegStar,
    RegStarHalf,
    RegStickyNote,
    RegStopCircle,
    RegSun,
    RegSurprise,
    RegThumbsDown,
    RegThumbsUp,
    RegTimesCircle,
    RegTired,
    RegTrashAlt,
    RegUser,
    RegUserCircle,
    RegWindowClose,
    RegWindowMaximize,
    RegWindowMinimize,
    RegWindowRestore,
    Registered,
    RemoveFormat,
    Renren,
    Reply2,
    ReplyAll2,
    Replyd,
    Republican,
    Researchgate,
    Resolving,
    Restroom,
    Retweet,
    Rev,
    Ribbon,
    Ring,
    Road,
    Robot,
    Rocket2,
    Rocketchat,
    Rockrms,
    Route2,
    Rss,
    RssSquare,
    RubleSign,
    Ruler,
    RulerCombined,
    RulerHorizontal,
    RulerVertical,
    Running,
    RupeeSign,
    Rust,
    SadCry,
    SadTear,
    Safari,
    Salesforce,
    Sass,
    Satellite2,
    SatelliteDish,
    Save2,
    Schlix,
    School2,
    Screwdriver,
    Scribd,
    Scroll,
    SdCard2,
    Search2,
    SearchDollar,
    SearchLocation,
    SearchMinus,
    SearchPlus,
    Searchengin,
    Seedling,
    Sellcast,
    Sellsy,
    Server,
    Servicestack,
    Shapes,
    Share2,
    ShareAlt,
    ShareAltSquare,
    ShareSquare,
    ShekelSign,
    ShieldAlt,
    ShieldVirus,
    Ship,
    ShippingFast,
    Shirtsinbulk,
    ShoePrints,
    Shopify,
    ShoppingBag2,
    ShoppingBasket2,
    ShoppingCart2,
    Shopware,
    Shower2,
    ShuttleVan,
    Sign,
    SignInAlt,
    SignLanguage2,
    SignOutAlt,
    Signal,
    Signature,
    SimCard2,
    Simplybuilt,
    Sink,
    Sistrix,
    Sitemap,
    Sith,
    Skating,
    Sketch,
    Skiing,
    SkiingNordic,
    Skull,
    SkullCrossbones,
    Skyatlas,
    Skype,
    Slack,
    SlackHash,
    Slash,
    Sleigh,
    SlidersH,
    Slideshare,
    Smile,
    SmileBeam,
    SmileWink,
    Smog,
    Smoking,
    SmokingBan,
    Sms2,
    Snapchat,
    SnapchatGhost,
    SnapchatSquare,
    Snowboarding2,
    Snowflake,
    Snowman,
    Snowplow,
    Soap2,
    Socks,
    SolarPanel,
    Sort2,
    SortAlphaDown,
    SortAlphaDownAlt,
    SortAlphaUp,
    SortAlphaUpAlt,
    SortAmountDown,
    SortAmountDownAlt,
    SortAmountUp,
    SortAmountUpAlt,
    SortDown,
    SortNumericDown,
    SortNumericDownAlt,
    SortNumericUp,
    SortNumericUpAlt,
    SortUp,
    Soundcloud,
    Sourcetree,
    Spa2,
    SpaceShuttle,
    Speakap,
    SpeakerDeck,
    SpellCheck,
    Spider,
    Spinner,
    Splotch,
    Spotify,
    SprayCan,
    Square2,
    SquareFull,
    SquareRootAlt,
    Squarespace,
    StackExchange,
    StackOverflow,
    Stackpath,
    Stamp,
    Star2,
    StarAndCrescent,
    StarHalf2,
    StarHalfAlt,
    StarOfDavid,
    StarOfLife,
    Staylinked,
    Steam,
    SteamSquare,
    SteamSymbol,
    StepBackward,
    StepForward,
    Stethoscope,
    StickerMule,
    StickyNote,
    Stop2,
    StopCircle2,
    Stopwatch,
    Stopwatch20,
    Store2,
    StoreAlt,
    StoreAltSlash,
    StoreSlash,
    Strava,
    Stream2,
    StreetView,
    Strikethrough,
    Stripe,
    StripeS,
    Stroopwafel,
    Studiovinari,
    Stumbleupon,
    StumbleuponCircle,
    Subscript2,
    Subway2,
    Suitcase,
    SuitcaseRolling,
    Sun,
    Superpowers,
    Superscript2,
    Supple,
    Surprise,
    Suse,
    Swatchbook,
    Swift,
    Swimmer,
    SwimmingPool,
    Symfony,
    Synagogue2,
    Sync2,
    SyncAlt2,
    Syringe,
    Table,
    TableTennis,
    Tablet2,
    TabletAlt,
    Tablets,
    TachometerAlt,
    Tag2,
    Tags,
    Tape,
    Tasks,
    Taxi,
    Teamspeak,
    Teeth,
    TeethOpen,
    Telegram2,
    TelegramPlane,
    TemperatureHigh,
    TemperatureLow,
    TencentWeibo,
    Tenge,
    Terminal2,
    TextHeight,
    TextWidth,
    Th,
    ThLarge,
    ThList,
    TheRedYeti,
    TheaterMasks,
    Themeco,
    Themeisle,
    Thermometer,
    ThermometerEmpty,
    ThermometerFull,
    ThermometerHalf,
    ThermometerQuarter,
    ThermometerThreeQuarters,
    ThinkPeaks,
    ThumbsDown,
    ThumbsUp,
    Thumbtack,
    TicketAlt,
    Tiktok,
    Times,
    TimesCircle,
    Tint,
    TintSlash,
    Tired,
    ToggleOff2,
    ToggleOn2,
    Toilet,
    ToiletPaper,
    ToiletPaperSlash,
    Toolbox,
    Tools,
    Tooth,
    Torah,
    ToriiGate,
    Tractor,
    TradeFederation,
    Trademark,
    TrafficLight,
    Trailer,
    Train2,
    Tram2,
    Transgender2,
    TransgenderAlt,
    Trash,
    TrashAlt,
    TrashRestore,
    TrashRestoreAlt,
    Tree,
    Trello,
    Tripadvisor,
    Trophy,
    Truck,
    TruckLoading,
    TruckMonster,
    TruckMoving,
    TruckPickup,
    Tshirt,
    Tty2,
    Tumblr,
    TumblrSquare,
    Tv2,
    Twitch,
    Twitter2,
    TwitterSquare,
    Typo3,
    Uber,
    Ubuntu,
    Uikit,
    Umbraco,
    Umbrella2,
    UmbrellaBeach,
    Uncharted,
    Underline,
    Undo2,
    UndoAlt,
    Uniregistry,
    Unity,
    UniversalAccess,
    University,
    Unlink,
    Unlock,
    UnlockAlt,
    Unsplash,
    Untappd,
    Upload2,
    Ups,
    Usb2,
    User,
    UserAlt,
    UserAltSlash,
    UserAstronaut,
    UserCheck,
    UserCircle,
    UserClock,
    UserCog,
    UserEdit,
    UserFriends,
    UserGraduate,
    UserInjured,
    UserLock,
    UserMd,
    UserMinus,
    UserNinja,
    UserNurse,
    UserPlus,
    UserSecret,
    UserShield,
    UserSlash,
    UserTag,
    UserTie,
    UserTimes,
    Users,
    UsersCog,
    UsersSlash,
    Usps,
    Ussunnah,
    UtensilSpoon,
    Utensils,
    Vaadin,
    VectorSquare,
    Venus,
    VenusDouble,
    VenusMars,
    Vest,
    VestPatches,
    Viacoin,
    Viadeo,
    ViadeoSquare,
    Vial,
    Vials,
    Viber,
    Video,
    VideoSlash,
    Vihara,
    Vimeo,
    VimeoSquare,
    VimeoV,
    Vine,
    Virus,
    VirusSlash,
    Viruses,
    Vk,
    Vnv,
    Voicemail2,
    VolleyballBall,
    VolumeDown2,
    VolumeMute2,
    VolumeOff2,
    VolumeUp2,
    VoteYea,
    VrCardboard,
    Vuejs,
    Walking,
    Wallet,
    Warehouse2,
    WatchmanMonitoring,
    Water2,
    WaveSquare,
    Waze,
    Weebly,
    Weibo,
    Weight,
    WeightHanging,
    Weixin,
    Whatsapp,
    WhatsappSquare,
    Wheelchair,
    Whmcs,
    Wifi2,
    WikipediaW,
    Wind,
    WindowClose,
    WindowMaximize,
    WindowMinimize,
    WindowRestore,
    Windows,
    WineBottle,
    WineGlass,
    WineGlassAlt,
    Wix,
    WizardsOfTheCoast,
    Wodu,
    WolfPackBattalion,
    WonSign,
    Wordpress,
    WordpressSimple,
    Wpbeginner,
    Wpexplorer,
    Wpforms,
    Wpressr,
    Wrench,
    XRay,
    Xbox,
    Xing,
    XingSquare,
    YCombinator,
    Yahoo,
    Yammer,
    Yandex,
    YandexInternational,
    Yarn,
    Yelp,
    YenSign,
    YinYang,
    Yoast,
    Youtube,
    YoutubeSquare,
    FaZhihu,
};

// import * as faIcons from 'react-icons/fa';
// import * as maIcons from './materialUI'
// const faIconsNames: string[] = [];
// console.log(
//     `import { ${Object.entries(faIcons)
//         .map((i) => {
//             let alias = i[0].substring(2); // remove first 2 characters

//             // If alias starts with a number, prepend it with an underscore
//             if (/^[0-9]/.test(alias)) {
//                 alias = '_' + alias;
//             }
//             if (Object.keys(maIcons).includes(alias)) alias = alias + '2';
//             faIconsNames.push(alias);
//             return `${i[0]} as ${alias}`;
//         })
//         .join(', ')} } from 'react-icons/fa';`,
// );

// console.log(`export { ${faIconsNames.join(', ')} } `);
