input {
   beats{
      port => 5044
   }
}

filter {
   json {
      source => "message"
   }

   mutate {
      remove_field => [
         "_index", "_type", "_version", "_score", "[_source][timestamp]",
         "[_source][level]", "[_source][message]", "[_source][label]", "[_source][agent]", 
         "[_source][tags]", "[_source][@version]", "[_source][ecs]", "[_source][host]", 
         "[_source][log]", "[_source][input]", "[_source][extra][serviceName]", "[_source][extra][environment]", 
         "[_source][fields]", "[_source][sort]", "[_source][@timestamp]", "host", "tags", "@version", "ecs", "agent",
         "log"
      ]
   }
}

output {
   if [label] == "logs" {
      elasticsearch {
         hosts => "http://elastic:9200"
         index => "%{[extra][environment]}-logs"
         user => "elastic"
         password => "password"
      }
   } else {
      elasticsearch {
         hosts => "http://elastic:9200"
         index => "%{[extra][environment]}-%{[message]}"
         user => "elastic"
         password => "password"
      }
   }
}