input {
   beats{
      port => 5044
   }
}

filter {
   json {
      source => "message"
   }
}

output {
   if [label] == "logs" {
      elasticsearch {
         hosts => "http://elastic:9200"
         index => "%{[extra][environment]}-%{[extra][serviceName]}-%{+YYYY.MM.DD}"
         user => "elastic"
         password => "password"
      }
   } else {
      elasticsearch {
         hosts => "http://elastic:9200"
         index => "%{[extra][environment]}-%{[label]}-%{+YYYY.MM.DD}"
         user => "elastic"
         password => "password"
      }
   }
}