name: "mock"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/mock
  tag: latest

service:
  ports: 

config:
  configmaps: []
  env:
    - name: ENTITY_TEMPLATE_MANAGER_URI
      value: http://entity-template-manager:8000
    - name: RELATIONSHIP_TEMPLATE_MANAGER_URI
      value: http://relationship-template-manager:8000
    - name: INSTANCE_MANAGER_URI
      value: http://instance-manager:8000
    - name: PERMISSIONS_API_URI
      value: http://permission-api:8000
    - name: PROCESS_SERVICE_URI
      value: http://process-service:8000
    - name: KARTOFFEL_IDS
      value: 61d37cb5e4de0300121e31ef
