name: 'workspace-service'
replicaCount: 1

images:
    PullSecrets: [jawsreg]
    repository: jawsproject.azurecr.io/workspace-service
    tag: latest

service:
    ports:
        - name: http
          port: '8000'

livenessProbe:
    httpGet:
        path: /isAlive
        port: 8000

readinessProbe:
    httpGet:
        path: /isAlive
        port: 8000

config:
    configmaps: []
    env:
        - name: PORT
          value: 8000
        - name: MONGO_URL
          value: mongodb+srv://jaws:jcfVBJQW73BobDvr@cluster0.t8onr.mongodb.net/workspace-service?retryWrites=true&w=majority
        - name: MONGO_WORKSPACES_COLLECTION_NAME
          value: 'workspaces'
