version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  gateway-service:
    build: .
    environment:
      PORT: 8000
      MONGO_URL: mongodb://mongo
      MONGO_IFRAMES_COLLECTION_NAME: iFrames
      MONGO_CHARTS_COLLECTION_NAME: charts
      TOKEN_SECRET: secret
      ENTITY_TEMPLATE_SERVICE_URL: http://entity-template-service:8000
      STORAGE_SERVICE_URL: http://storage-service:8000
      TEMPLATE_SERVICE_URL: http://template-service:8000
      INSTANCE_SERVICE_URL: http://instance-service:8000
      PERMISSION_SERVICE_BASE_URL: http://permission-service:8000
      CALLBACK_URL: http://localhost/api/auth/callback
      KARTOFFEL_BASE_URL: http://kartoffel-tmp:3000
      SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
      ACCESS_TOKEN_NAME: rabaz-access-token
      SYSTEM_UNAVAILABLE_URL: /unavailable
      SYSTEM_MELTA_BASE_URL: http://localhost
      PREVIEW_SERVICE_URL: http://preview-service:8000
