# syntax=docker/dockerfile:1.4
FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./
COPY shared/package*.json ./shared/
COPY gateway-service/package*.json ./gateway-service/
COPY gateway-service/.npmrc ./gateway-service/.npmrc
COPY .npmrc ./

RUN --mount=type=secret,id=npm_token \
    NPM_TOKEN=$(cat /run/secrets/npm_token) \
    npm ci --silent --progress=false

COPY shared/ ./shared/
COPY gateway-service ./gateway-service

RUN npm run build -w @microservices/shared
RUN npm run build -w gateway-service

RUN rm -f .npmrc

EXPOSE 8000

CMD ["npm", "run", "dev:nodemon", "-w", "gateway-service"]
