name: "instance-service"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/instance-service
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /isAlive
    port: 8000

readinessProbe:
  httpGet:
    path: /isAlive
    port: 8000

config:
  configmaps: []
  env:
    - name: PORT
      value: 8000
    - name: NEO4J_USERNAME
      value: neo4j
    - name: NEO4J_PASSWORD
      value: test
    - name: NEO4J_DATABASE
      value: neo4j
    - name: NEO4J_URL
      value: neo4j://neo4j
    - name: ENTITY_TEMPLATE_SERVICE_URL
      value: http://entity-template-service:8000
    - name: RELATIONSHIP_TEMPLATE_SERVICE_URL
      value: http://relationship-template-service:8000      
    - name: REDIS_HOST
      value: redis://:ZjtUJvwPOY@redis:6379
