name: "instance-manager"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/instance-manager
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /isAlive
    port: 8000

readinessProbe:
  httpGet:
    path: /isAlive
    port: 8000

config:
  configmaps: []
  env:
    - name: PORT
      value: 8000
    - name: NEO4J_USERNAME
      value: neo4j
    - name: NEO4J_PASSWORD
      value: O7iiktQ9YjB2jBVvGXt0w8nqhV6bW7CawkraxZ3e-gA
    - name: NEO4J_DATABASE
      value: neo4j
    - name: NEO4J_URL
      value: neo4j+s://35e30c09.databases.neo4j.io
    - name: TEMPLATE_MANAGER_URL
      value: http://entity-template-manager:8000
    - name: RELATIONSHIP_MANAGER_URL
      value: http://relationship-template-manager:8000      
    - name: REDIS_HOST
      value: redis://:ZjtUJvwPOY@redis:6379
