#!/usr/bin/env sh

# FOR ALL OF OUR MONO REPO
# IMAGES=$(cat ./scripts/docker-compose.yml | grep "build:" | awk '{print $2}' | grep -v -F -f ./scripts/forbidden-images.txt | sed -e 's|^\./||' -e 's/^/melta-/' -e '/^melta_build:/d')

# for image in $IMAGES; do
#   cd "$image"
#   npm run build && npm run lint
#   cd ..
# done

# git commit --no-verify for override
cd ./frontend-service/ && npm run lint && node --max_old_space_size=16384 && npm run build
