name: "storage-service"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/storage-service
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /isAlive
    port: 8000

readinessProbe:
  httpGet:
    path: /isAlive
    port: 8000

config:
  configmaps: []
  env:
    - name: MINIO_PORT
      value: 9000
    - name: MINIO_ACCESS_KEY
      value: admin
    - name: MINIO_SECRET_KEY
      value: yesodot12345
    - name: MINIO_BUCKET_NAME
      value: files
    - name: MINIO_ENDPOINT
      value: minio
