name: "entity-template-manager"
replicaCount: 1

images:
  PullSecrets: [jawsreg]
  repository: jawsproject.azurecr.io/entity-template-manager
  tag: latest

service:
  ports:
  - name: http
    port: "8000"

livenessProbe:
  httpGet:
    path: /health
    port: 8000

readinessProbe:
  httpGet:
    path: /health
    port: 8000

config:
  configmaps: []
  env:
    - name: PORT
      value: 8000
    - name: MONGO_URI
      value: mongodb+srv://jaws:jcfVBJQW73BobDvr@cluster0.t8onr.mongodb.net/templates?retryWrites=true&w=majority
    - name: MONGO_ENTITY_TEMPLATE_COLLECTION_NAME
      value: entityTemplate
    - name: MONGO_CATEGORY_COLLECTION_NAME
      value: category
    - name: RELATIONSHIP_TEMPLATE_MANAGER_URI
      value: http://relationship-template-manager:8000
    - name: STORAGE_SERVICE_URI
      value: http://storage-service:8000
    - name: STORAGE_SERVICE_UPLOAD_FILE_ROUTE
      value: api/files
    - name: STORAGE_SERVICE_DOWNLOAD_FILE_ROUTE
      value: api/files
    - name: STORAGE_SERVICE_DELETE_FILE_ROUTE
      value: api/files
    - name: RABBIT_URI
      value: amqp://user:McgIwOn8Yh@my-release-rabbitmq
