import { UiSchema } from '@rjsf/utils';
import _ from 'lodash';
import { IEntitySingleProperty, IMongoEntityTemplatePopulated, IProperties } from '../../../interfaces/entityTemplates';
import { EntityWizardValues } from '../../dialogs/entity';
import i18next from 'i18next';
import { FormikHelpers } from 'formik';
import { IKartoffelUser } from '../../../interfaces/users';
import { flatten } from 'flat';
import { kartoffelPersonalDataFields } from '../../wizards/entityTemplate/KartoffelUserField';

const changeRelatedUserFields = (properties: IProperties['properties'], changedUserKey: string, user: IKartoffelUser | null) => {
    return Object.entries(properties).reduce((acc, [key, value]) => {
        if (changedUserKey === key) {
            acc[key] = user
                ? JSON.stringify({
                      _id: user?._id || user?.id,
                      fullName: user?.fullName,
                      jobTitle: user?.jobTitle,
                      hierarchy: user?.hierarchy,
                      mail: user?.mail,
                      userType: user?.entityType,
                  })
                : undefined;
        }
        if (value.properties) {
            acc[key] = changeRelatedUserFields(value.properties, changedUserKey, user);
        } else if (value.expandedUserField?.relatedUserField === changedUserKey) {
            acc[key] = user?.[value.expandedUserField.kartoffelField];
        }

        return acc;
    }, {});
};

const getFieldUiSchema = (
    schema: IMongoEntityTemplatePopulated['properties'],
    values: EntityWizardValues,
    setValues: FormikHelpers<any>['setValues'],
    isEditMode: boolean,
    toPrint: boolean,
    propertyKey: string,
    propertySchema: IEntitySingleProperty,
    unitsOptions?: string[],
): UiSchema => {
    const defaultValue = values.template?.properties?.properties?.[propertyKey]?.defaultValue ?? undefined;
    const enumPropertiesColors = values.template?.enumPropertiesColors;
    if (propertySchema.archive) return {};

    if (propertySchema.format === 'kartoffelUserField' && propertySchema?.expandedUserField?.kartoffelField === 'image') {
        const userProperty = propertySchema?.expandedUserField?.relatedUserField;
        const user = userProperty && values.properties?.[userProperty] ? JSON.parse(values.properties?.[userProperty]) : undefined;
        return { 'ui:widget': 'UserAvatarWidget', 'ui:options': { user } };
    }

    if (propertySchema.format === 'comment')
        return {
            'ui:options': {
                hide: schema.hide.includes(propertyKey),
            },
            'ui:classNames': 'fullWidth',
            'ui:widget': 'CommentWidget',
        };
    if (propertySchema.format === 'signature')
        return {
            'ui:widget': 'SignatureWidget',
            'ui:classNames': 'fullWidth',
        };
    if (propertySchema.readOnly) {
        const isGoalUser =
            propertySchema.format === 'kartoffelUserField' &&
            !!values.properties[propertySchema?.expandedUserField?.relatedUserField!] &&
            JSON.parse(values.properties[propertySchema?.expandedUserField?.relatedUserField!])?.userType === 'GoalUser' &&
            kartoffelPersonalDataFields.includes((propertySchema.expandedUserField?.kartoffelField ?? '').trim());

        return {
            'ui:options': {
                disabled: !(propertySchema.accountBalance && !isEditMode) || !isGoalUser,
                readonly: !isGoalUser,
                defaultValue,
            },
        };
    }
    if (propertySchema.serialCurrent !== undefined)
        return {
            'ui:options': {
                inputType: 'text',
                disabled: true,
                hardCodedValue: isEditMode ? undefined : i18next.t('wizard.entity.serialNumberAutoGenerated'),
            },
        };
    if (propertySchema.format === 'unitField') {
        return {
            'ui:widget': 'SelectWidget',
            'ui:options': {
                defaultValue,
                enumOptions: unitsOptions?.map((option) => ({
                    label: option,
                    value: option,
                    color: enumPropertiesColors?.[propertyKey]?.[option],
                })),
            },
        };
    }
    if (propertySchema.items?.enum || propertySchema?.enum) {
        return {
            'ui:widget': 'SelectWidget',
            'ui:options': {
                defaultValue,
                enumOptions: (propertySchema.items?.enum || propertySchema?.enum)!.map((option) => ({
                    label: option,
                    value: option,
                    color: enumPropertiesColors?.[propertyKey]?.[option],
                })),
            },
        };
    }

    if (propertySchema.type === 'array' && propertySchema.items?.format === 'user') {
        return {
            'ui:widget': 'UserArrayWidget',
            'ui:options': {
                defaultValue,
            },
        };
    }
    if (propertySchema.format === 'user') {
        return {
            'ui:widget': 'UserWidget',
            'ui:options': {
                globalValues: values,
                updateExpandedUserFields: (user: IKartoffelUser | null, curValues: any) => {
                    // TODO: refactor - this code gets the fields that need to be modified so the displayed fields will be set in a nested way..
                    const changedPropertiesOfUser = changeRelatedUserFields(schema.properties, propertyKey, user);

                    // in order to set the values in the backend, we need to send the updated fields flatten
                    const flattenChangedPropertiesOfUser: Object = flatten(changedPropertiesOfUser, { maxDepth: Infinity });

                    const updatedFlattenFields = {};

                    Object.keys(flattenChangedPropertiesOfUser).forEach((key) => {
                        updatedFlattenFields[key.split('.').pop() || key] = flattenChangedPropertiesOfUser[key];
                    });

                    setValues({
                        ...curValues.properties,
                        ...changedPropertiesOfUser,
                        ...updatedFlattenFields,
                    });
                },
            },
        };
    }
    if (propertySchema.format === 'text-area')
        return {
            'ui:widget': 'TextAreaWidget',
            'ui:classNames': 'fullWidth',
            'ui:options': { toPrint, defaultValue },
        };
    if (propertySchema.format === 'relationshipReference')
        return {
            'ui:widget': 'TemplateReferenceWidget',
        };
    if (propertySchema.format === 'location')
        return {
            'ui:widget': 'LocationWidget',
        };

    return {
        'ui:options': { defaultValue },
    };
};

export const uiSchemaUtils = (
    schema: IMongoEntityTemplatePopulated['properties'],
    values: EntityWizardValues,
    setValues: FormikHelpers<any>['setValues'],
    isEditMode: boolean,
    toPrint: boolean,
    groupTitleColor: string,
    unitsOptions?: string[],
): Record<string, UiSchema> => {
    const uiSchema: ReturnType<typeof uiSchemaUtils> = {};

    for (const [propertyKey, propertySchema] of Object.entries(schema.properties)) {
        // is property in group
        if (propertySchema.properties) {
            if (!uiSchema[propertyKey]) uiSchema[propertyKey] = { 'ui:style': { color: groupTitleColor }, 'ui:classNames': 'fullWidth' };

            for (const [groupedPropertyKey, groupedPropertySchema] of Object.entries(propertySchema.properties)) {
                const groupedUiSchema = getFieldUiSchema(
                    schema,
                    values,
                    setValues,
                    isEditMode,
                    toPrint,
                    groupedPropertyKey,
                    groupedPropertySchema,
                    unitsOptions,
                );

                uiSchema[propertyKey][groupedPropertyKey] = groupedUiSchema;
            }
        } else uiSchema[propertyKey] = getFieldUiSchema(schema, values, setValues, isEditMode, toPrint, propertyKey, propertySchema, unitsOptions);
    }

    return uiSchema;
};
