import { UiSchema } from '@rjsf/utils';
import { cloneDeep } from 'lodash';
import { IEntitySingleProperty, IMongoEntityTemplatePopulated } from '../../../interfaces/entityTemplates';
import { EntityWizardValues } from '../../dialogs/entity';
import i18next from 'i18next';
import { FormikHelpers } from 'formik';
import { IKartoffelUser } from '../../../interfaces/users';

const getFieldUiSchema = (
    schema: IMongoEntityTemplatePopulated['properties'],
    values: EntityWizardValues,
    setValues: FormikHelpers<any>['setValues'],
    isEditMode: boolean,
    toPrint: boolean,
    propertyKey: string,
    propertySchema: IEntitySingleProperty,
): UiSchema => {
    const defaultValue = values.template?.properties?.properties?.[propertyKey]?.defaultValue ?? undefined;
    if (propertySchema.archive) return {};
    if (propertySchema.format === 'comment')
        return {
            'ui:options': {
                hide: schema.hide.includes(propertyKey),
            },
            'ui:classNames': 'fullWidth',
            'ui:widget': 'CommentWidget',
        };
    if (propertySchema.format === 'signature')
        return {
            'ui:widget': 'SignatureWidget',
            'ui:classNames': 'fullWidth',
        };
    if (propertySchema.readOnly)
        return {
            'ui:options': {
                disabled: true,
                defaultValue,
            },
        };
    if (propertySchema.serialCurrent !== undefined)
        return {
            'ui:options': {
                inputType: 'text',
                disabled: true,
                hardCodedValue: isEditMode ? undefined : i18next.t('wizard.entity.serialNumberAutoGenerated'),
            },
        };

    if (propertySchema.items?.enum || propertySchema?.enum) {
        return {
            'ui:widget': 'SelectWidget',
            'ui:options': {
                defaultValue,
                enumOptions: (propertySchema.items?.enum || propertySchema?.enum)!.map((option) => ({
                    label: option,
                    value: option,
                    color: values.template?.enumPropertiesColors?.[propertyKey]?.[option],
                })),
            },
        };
    }

    if (propertySchema.type === 'array' && propertySchema.items?.format === 'user') {
        return {
            'ui:widget': 'UserArrayWidget',
            'ui:options': {
                defaultValue,
            },
        };
    }
    if (propertySchema.format === 'user') {
        return {
            'ui:widget': 'UserWidget',
            'ui:options': {
                globalValues: values,
                updateExpandedUserFields: (user: IKartoffelUser | null, curValues: any) => {
                    const userFieldsToUpdate = Object.keys(schema.properties).filter(
                        (key) => schema.properties[key].expandedUserField?.relatedUserField === propertyKey,
                    );

                    const clonedValues = cloneDeep(curValues);

                    const propertiesToUpdate = clonedValues.properties;

                    userFieldsToUpdate.forEach((key) => {
                        const kartoffelField = schema.properties[key].expandedUserField?.kartoffelField;
                        propertiesToUpdate[key] = user && kartoffelField ? user[kartoffelField] : undefined;
                    });

                    propertiesToUpdate[propertyKey] = user
                        ? JSON.stringify({
                              _id: user?._id || user?.id,
                              fullName: user?.fullName,
                              jobTitle: user?.jobTitle,
                              hierarchy: user?.hierarchy,
                              mail: user?.mail,
                          })
                        : undefined;

                    setValues({
                        ...propertiesToUpdate,
                    });
                },
            },
        };
    }
    if (propertySchema.format === 'text-area')
        return {
            'ui:widget': 'TextAreaWidget',
            'ui:classNames': 'fullWidth',
            'ui:options': { toPrint, defaultValue },
        };
    if (propertySchema.format === 'relationshipReference')
        return {
            'ui:widget': 'TemplateReferenceWidget',
        };
    if (propertySchema.format === 'location')
        return {
            'ui:widget': 'LocationWidget',
        };
    return {
        'ui:options': { defaultValue },
    };
};

export const uiSchemaUtils = (
    schema: IMongoEntityTemplatePopulated['properties'],
    values: EntityWizardValues,
    setValues: FormikHelpers<any>['setValues'],
    isEditMode: boolean,
    toPrint: boolean,
    groupTitleColor: string,
): Record<string, UiSchema> => {
    const uiSchema: ReturnType<typeof uiSchemaUtils> = {};

    for (const [propertyKey, propertySchema] of Object.entries(schema.properties)) {
        // is property in group
        if (propertySchema.properties) {
            if (!uiSchema[propertyKey]) uiSchema[propertyKey] = { 'ui:style': { color: groupTitleColor }, 'ui:classNames': 'fullWidth' };

            for (const [groupedPropertyKey, groupedPropertySchema] of Object.entries(propertySchema.properties)) {
                const groupedUiSchema = getFieldUiSchema(schema, values, setValues, isEditMode, toPrint, groupedPropertyKey, groupedPropertySchema);

                if (!groupedUiSchema['ui:classNames']) groupedUiSchema['ui:classNames'] = 'half-width-field';

                uiSchema[propertyKey][groupedPropertyKey] = groupedUiSchema;
            }
        } else uiSchema[propertyKey] = getFieldUiSchema(schema, values, setValues, isEditMode, toPrint, propertyKey, propertySchema);
    }

    return uiSchema;
};
