name: CI

on:
  pull_request:
  push:
    branches: [dev, main, preprod]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8000

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Configure pnpm for GitLab registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat <<EOF > ~/.npmrc
          @yesodot:registry=https://gitlab.com/api/v4/projects/29372887/packages/npm/
          //gitlab.com/api/v4/projects/29372887/packages/npm/:_authToken=${{ secrets.NPM_TOKEN }}
          always-auth=true
          EOF

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Biome
        run: pnpm run biome

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8000
      
      - name: Run tests
        run: pnpm test