export const excelConfig = {
    excelDefaultColumns: [
        { key: 'disabled', header: '?מושבת', width: 20 },
        { key: 'createdAt', header: 'תאריך יצירה', width: 20 },
        { key: 'updatedAt', header: 'תאריך עדכון', width: 20 },
    ],
    excelDefaultColumnsOnlyColumns: [
        { key: 'disabled', header: '?מושבת(בוליאני)', width: 20 },
        { key: 'createdAt', header: 'תאריך יצירה(תאריך)', width: 20 },
        { key: 'updatedAt', header: 'תאריך עדכון(תאריך)', width: 20 },
    ],
    TRUE_TO_HEBREW: 'כן',
    FALSE_TO_HEBREW: 'לא',
    DATE_TIMEZONE: 'Israel',
    DATE_LOCALES: 'en-UK',
    regexOfDateFormat: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])/,
    regexOfTextAreaFormat: /<[a-z][\s\S]*>/i,
    propertyType: {
        string: 'טקסט',
        number: 'מספר',
        boolean: 'בולאני',
        date: 'תאריך',
        time: 'שעה',
        'date-time': 'תאריך ושעה',
        email: 'כתובת מייל',
        pattern: 'תבנית (regex)',
        enum: 'רשימה',
        relationshipReference: 'שיוך לקשר',
        dateNotification: 'התראה לפני סיום',
        entityReference: 'שיוך לישות',
        serialNumber: 'מספר סידורי',
        enumArray: 'רשימה מרובה',
        array: 'מערך',
        'text-area': 'טקסט ארוך',
        fileId: 'קובץ יחיד',
        multipleFiles: 'קבצים מרובים',
    },
    unique: 'ייחודי',
};
