export const excelConfig = {
    excelDefaultColumns: [
        { key: 'disabled', header: '?מושבת', width: 20 },
        { key: 'createdAt', header: 'תאריך יצירה', width: 20 },
        { key: 'updatedAt', header: 'תאריך עדכון', width: 20 },
    ],
    TRUE_TO_HEBREW: 'כן',
    FALSE_TO_HEBREW: 'לא',
    failedEntities: 'יישויות שכשלו להטען',
    DATE_TIMEZONE: 'Israel',
    DATE_LOCALES: 'en-UK',
    regexOfDateFormat: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])/,
    regexOfTextAreaFormat: /<[a-z][\s\S]*>/i,
    propertyType: {
        string: 'טקסט',
        number: 'מספר',
        boolean: 'כן/לא',
        date: 'תאריך',
        time: 'שעה',
        'date-time': 'תאריך ושעה',
        email: 'כתובת מייל',
        pattern: 'תבנית (regex)',
        dateNotification: 'התראה לפני סיום',
        entityReference: 'שיוך לישות',
        serialNumber: 'מספר סידורי',
        array: 'מערך',
        'text-area': 'טקסט ארוך',
    },
    formulae: {
        errorTitle: 'אופציה לא תקינה',
        errorDescription: 'בבקשה תבחר',
        boolean: 'כן, לא',
        numberError: 'נא להזין מספר חוקי',
        dateError: 'נא להזין תאריך חוקי',
        mailError: 'נא להזין מייל חוקי',
    },
};
